### ISSUE TITLE
set -Dpackaging.type=jar spark.driver.extraJavaOptions | spec.driver.javaOptions 

### ISSUE THREAD

**Issue by sulthonzh** [kubeflow/spark-operator#1011]
Hello @reviewers i need set `-Dpackaging.type=jar ` on driver

I have used the methods below, but it still doesn't work

```
spec:
  driver:
    javaOptions: '-Dpackaging.type=jar'
```

```
spec:
  sparkConf:
    'spark.driver.extraJavaOptions': '-Dpackaging.type=jar'
```

What should I do?

**Comment by Charmelionag** [comment]
Did you find a solution for your issue? I am experiencing just the same problem.
