### ISSUE TITLE
Spark application CRD upgrades

### ISSUE THREAD

**Issue by shensonj** [kubeflow/spark-operator#1026]
I would like to know how are we planning to handle sparkApplication and scheduledSparkApplication CRD upgrades when spark applications are running.
Let us say we have installed sparkApplication CRD version v1beta1 in our cluster and few streaming spark jobs are running (using this sparkApplication)
Now if we want to upgrade sparkApplication CRD to v1beta2. Our understanding is that we have to delete the v1beta1 version and then install v1beta2. Is this correct understanding?
If so, we observe that the running spark jobs are stopped (because all the sparkApplications are deleted when CRD is deleted).
Do we have any view on this?

**Comment by shensonj** [comment]
@liyinan926

**Comment by jinxingwang** [comment]
What if you keep both versions of CRD, and upgrade your Spark operator pod to only submit a new version of CRDs.
Hopefully, the behavior will be the old version of sparkapplication that will still be able to run, and only the new version of CRDs will get created.
Spark operator may failed to manage(watch/update) the old sparkapplication.

**Comment by shensonj** [comment]
@jinxingwang after CRD upgrade, we should only have new spark applications. So we try to delete old sparkapplication instance and try to create new one. But we have noticed that after spark operator doesn't create drivers for newly created CRD. Any solution/suggestion for this?

**Comment by jinxingwang** [comment]
When you say after CRD upgrade. Can you check a few things? 
What is the CRD version spark operator is trying to submit?
What is the CRD version that exists in the k8s object?
What does the `describe sparkapplication` say?
