### ISSUE TITLE
CRD upgrade error with crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml

### ISSUE THREAD

**Issue by renjigeorge** [kubeflow/spark-operator#1043]
Hi 
I am getting this error message in the pods of sparkoperator. 

E1017 01:22:50.178928      10 reflector.go:123] pkg/mod/k8s.io/client-go@v0.16.6/tools/cache/reflector.go:96: Failed to list *v1beta2.ScheduledSparkApplication: the server could not find the requested resource (get scheduledsparkapplications.sparkoperator.k8s.io)

Also when I try to install the latest release crds I get this issue too. 

kubectl create -f crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml --validate=false
The CustomResourceDefinition "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: metadata.annotations[api-approved.kubernetes.io]: Required value: protected groups must have approval annotation "api-approved.kubernetes.io", see https://github.com/kubernetes/enhancements/pull/1111

any one help me troubleshoot this issue

**Comment by shardulsrivastava** [comment]
@renjigeorge how did you install the operator and which version did you install also your Kubernetes version ??
