### ISSUE TITLE
ScheduledSparkApplication application metrics

### ISSUE THREAD

**Issue by kobikis** [kubeflow/spark-operator#1068]
Hi,

Since ScheduledSparkApplication name contains generated suffix for example: my-app-name-1605592986890316782 it impossible to create ServiceMonitor.
In ServiceMonitor I'm configuring a selector to the Service , but since sparkoperator.k8s.io/app-name value is generated it's not match.

**ServiceMonitor:**
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
...
  namespaceSelector:
     matchNames:
     - mynamespace
  selector:
     matchLabels:
       sparkoperator.k8s.io/app-name: **my-app-name**

**Generated Service:**
Name:              my-app-name-1605592986890316782-ui-svc
Namespace:         mynamespace
Labels:            **sparkoperator.k8s.io/app-name=my-app-name-1605592986890316782**
                       sparkoperator.k8s.io/submission-id=9bb436c8-a342-401c-8cb3-e95fdd883b28
Annotations:       <none>
Selector:          spark-role=driver,sparkoperator.k8s.io/app-name=my-app-name-1605592986890316782
Type:              ClusterIP
IP:                100.71.177.33
Port:              spark-driver-ui-port  4040/TCP
TargetPort:        4040/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>

**Comment by suvashishtha** [comment]
@kobikis did you managed to make it work somehow?
