### ISSUE TITLE
Manage SparkApplications with different Spark versions by specifying Spark version inside manifest

### ISSUE THREAD

**Issue by jenoOvchi** [kubeflow/spark-operator#1069]
Hi!
Is it possible to use two different Spark Operator instances to run SparkApplications with different Spark versions by specifying Spark version inside manifest?
For example:
We have 2 Spark Operators inside Kubernetes cluster - 1 from Cloudflow with version 2.4.5 and 1 installed manualy from official Helm repo with version 3.0.0. We deploy SparkApplications manifest, where we specify sparkVersion: "2.4.5" and it is running with Cloudflow Spark Operator, than we deploy SparkApplications manifest, where we specify sparkVersion: "3.0.0" and it is running with Spark Operator with 3.0.0 version support.

**Comment by kz33** [comment]
@jenoOvchi  Your 2.4.x job can't run  with spark 3.0 via the spark-operator 3.x ?

**Comment by kz33** [comment]
I remember there was the same issue before #961

**Comment by jenoOvchi** [comment]
> @jenoOvchi Your 2.4.x job can't run with spark 3.0 via the spark-operator 3.x ?

I don't know, but Spark Operator with Spark 3.0.0 not supported by Cloudflow - his lead developer says that now Cloudflow not working correctly with newest version of Spark Operator and support of this not in the roadmap.

**Comment by kz33** [comment]
> > @jenoOvchi Your 2.4.x job can't run with spark 3.0 via the spark-operator 3.x ?
> 
> I don't know, but Spark Operator with Spark 3.0.0 not supported by Cloudflow - his lead developer says that now Cloudflow not working correctly with newest version of Spark Operator and support of this not in the roadmap.


Well, I think that if the two operators are not watch the same crd version, they can work normally

**Comment by jenoOvchi** [comment]
> > > @jenoOvchi Your 2.4.x job can't run with spark 3.0 via the spark-operator 3.x ?
> > 
> > 
> > I don't know, but Spark Operator with Spark 3.0.0 not supported by Cloudflow - his lead developer says that now Cloudflow not working correctly with newest version of Spark Operator and support of this not in the roadmap.
> 
> Well, I think that if the two operators are not watch the same crd version, they can work normally

This is exactly what my problem is - all this operators use the sam API version (v1beta2 - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator#version-matrix) and different CRDs.
