### ISSUE TITLE
Executor is dead but kubectl describe still shows as RUNNING

### ISSUE THREAD

**Issue by FloraZhang** [kubeflow/spark-operator#1076]
Hi expert,

I noticed sometimes there's a mismatch between executor state shown in "kubectl describe sparkapplications" and the actual executor state. In a recent helm deploy, for example, the executor1 is already dead, but it's still showing as running in "kubectl describe sparkapplications": 

```
[root@k8s-node1 ~]# kubectl describe sparkapplications.sparkoperator.k8s.io spark-test-app
Status:
  Application State:
    State:  RUNNING
  Driver Info:
    Pod Name:             spark-test-app-driver
    Web UI Address:       10.233.15.219:40450
    Web UI Port:          40450
    Web UI Service Name:  spark-test-app-ui-svc
  Execution Attempts:     3
  Executor State:
    spark-test-app-evaluator-1605721320126-exec-1:  RUNNING
    spark-test-app-evaluator-1605774718513-exec-2:  RUNNING
```

Could it be a similar issue like this one? https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/689

Thanks,
Wenjing

**Comment by fisache** [comment]
it's resolved at https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1074

**Comment by FloraZhang** [comment]
@fisache Thank you. Good to know that. I'll grab the latest operator and give it another try.

**Comment by jystephan** [comment]
Hello guys -- we ran into the same issue today at [Data Mechanics](https://www.datamechanics.co).

@fisache are you sure that https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1074 fixes it?

In this case, the application is running, and there are executors that appear are running, even though they're actually dead. In #1074, the logic only applies when the application is completed. So it's not clear to me that it fixes this issue.

Thank you for your help (and thanks for #1074).

**Comment by fisache** [comment]
@jystephan hello,
Actually, the state sync by spark-operator is triggered not only application state changed but only pod states including driver and executors changed(add, update, delete).
Even though the app is COMPLETED with running state of executor pods, the executor pod is deleted eventually, it's triggered again with the app is completed state.

If any question or suggestion, please reply about that.
Thanks for your comment

**Comment by jrj-d** [comment]
Hey @fisache, chiming in. Thanks for your work!
I work with @jystephan .

In this case we had:
- in the status section of the `sparkapplication`:
    - app marked as `RUNNING`
    - two executors marked as `RUNNING`
- in reality (by listing pods):
    - the app is indeed running (the driver pod is `RUNNING`)
    - no executor pod is running

Does this kind of error has something to do with the fix in #1074 ? It seems that this PR fixes something that happens at the end of the life of an application, which is not the case here.

Could it be possible that some types of deaths of executors are not picked up by the spark-operator? (eg spot kill)

**Comment by fisache** [comment]
@jrj-d hello.
As your mention, the PR fixes only last of spark application life (completed or failed).

I did some experimental about deleting executor pod forcely (`exec-1` and `exec-2` executor pods delete).
```sh
$ sparkctl status spark-pi-volcano5 -n spark-job
application state:
+---------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
|  STATE  | SUBMISSION AGE | COMPLETION AGE |        DRIVER POD        |     DRIVER UI      | SUBMISSIONATTEMPTS | EXECUTIONATTEMPTS |
+---------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
| RUNNING | 3m             | N.A.           | spark-pi-volcano5-driver | xx.xx.x.xxx:4040 |                  1 |                 1 |
+---------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
executor state:
+----------------------------------+---------+
|           EXECUTOR POD           |  STATE  |
+----------------------------------+---------+
| spark-pi-ca86d075f51428f1-exec-1 | PENDING |
| spark-pi-ca86d075f51428f1-exec-2 | PENDING |
| spark-pi-ca86d075f51428f1-exec-3 | RUNNING |
+----------------------------------+---------+
```
and after driver is completed, it shows
```sh
$ sparkctl status spark-pi-volcano5 -n spark-job
application state:
+-----------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
|   STATE   | SUBMISSION AGE | COMPLETION AGE |        DRIVER POD        |     DRIVER UI      | SUBMISSIONATTEMPTS | EXECUTIONATTEMPTS |
+-----------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
| COMPLETED | 5m             | 28s            | spark-pi-volcano5-driver | xx.xx.x.xxx:4040 |                  1 |                 1 |
+-----------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
executor state:
+----------------------------------+-----------+
|           EXECUTOR POD           |   STATE   |
+----------------------------------+-----------+
| spark-pi-ca86d075f51428f1-exec-3 | COMPLETED |
| spark-pi-ca86d075f51428f1-exec-1 | FAILED    |
| spark-pi-ca86d075f51428f1-exec-2 | FAILED    |
+----------------------------------+-----------+
```

If what you said is similar to the above, I think I should check

**Comment by jrj-d** [comment]
This is not exactly the same issue, but it might be related indeed.
I have a hard time reproducing it, but I'll give it a try!

In our case we saw something like this (this is taken from your example):
```
$ sparkctl status spark-pi-volcano5 -n spark-job
application state:
+---------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
|  STATE  | SUBMISSION AGE | COMPLETION AGE |        DRIVER POD        |     DRIVER UI      | SUBMISSIONATTEMPTS | EXECUTIONATTEMPTS |
+---------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
| RUNNING | 3m             | N.A.           | spark-pi-volcano5-driver | xx.xx.x.xxx:4040 |                  1 |                 1 |
+---------+----------------+----------------+--------------------------+--------------------+--------------------+-------------------+
executor state:
+----------------------------------+---------+
|           EXECUTOR POD           |  STATE  |
+----------------------------------+---------+
| spark-pi-ca86d075f51428f1-exec-1 | PENDING |
| spark-pi-ca86d075f51428f1-exec-2 | PENDING |
| spark-pi-ca86d075f51428f1-exec-3 | RUNNING |
+----------------------------------+---------+
```
when list pods with k8s gave:
```
$ kubectl get pods -n spark-job

```
NAME                                             READY   STATUS    RESTARTS   AGE
spark-pi-ca86d075f51428f1-exec-1                 1/1     Pending   0          2m
spark-pi-ca86d075f51428f1-exec-2                 1/1     Pending   0          3m
```
Note that there is no mention of pod `spark-pi-ca86d075f51428f1-exec-3` in the pods list.

Note that this example is made up, I'll try to reproduce the bug on my end.
