### ISSUE TITLE
Configuring the webhook manually

### ISSUE THREAD

**Issue by jutley** [kubeflow/spark-operator#1094]
I am looking into what it will take for my organization to run this operator, and have same security concerns based on how the webhook is configured.

This application seems to want to manage its own webhook, which means giving it permissions to create, update, and delete mutation webhooks. This is a huge permission, because webhooks can be used to mutate any request or send any request to an external host.

I would really like to be able to enable the webhook functionality, but configure the resources for the webhook myself. This way, there is no possibility of the spark-operator service account creating unexpected webhook configurations.

Is this type of configuration possible? Based on the documentation, it seems like there is only a single flag to enable the webhook functionality and the webhook management functionality.

**Comment by liyinan926** [comment]
So basically what you would like to see is a way to plugin your own CA bundle in the `MutatingWebhookConfiguration`?

**Comment by jutley** [comment]
Perhaps. Truthfully I'm not really sure what the spark-operator does with regards to managing the webhook. If it's all about generating certs, then yes, plugging in my own CA bundle seems sufficient.

This would probably only require mounting a key and cert, then passing some flags to point to them, correct?
