### ISSUE TITLE
Passing virtualenv through conf in sparkonk8s - Is it possible ?

### ISSUE THREAD

**Issue by deveshcode** [kubeflow/spark-operator#1118]
Is it possible to pass a python custom virtualenv containing the supporting packages for the python file being passed. 
The dependencies for my pyspark code to run cannot be all accomodated using the deps -> PyFiles part as they contain transitive dependencies.
I could not find any info regarding this via stackoverflow / quick start / user guide / api docs
Apart from the info that spark config can be set via the "sparkConf" variable.

Would appreciate any help / inputs on this matter. 
Thanks in advance !

**Comment by slvn-lefebvre** [comment]
Hello @deveshcode 

I don't know if it is the best place to share this, but I managed to make it work on my infra by following these steps: 
1.  Package a virtualenv as specified in : https://spark.apache.org/docs/latest/api/python/user_guide/python_packaging.html#using-virtualenv
2.  Upload the packaged venv to my HDFS storage : hdfs://namenode:1234/URI/of/venv.tgz
3.  In the manifest for the spark application
    3.1  Set the "spark.archives" value in spec.sparkConf to  "hdfs://namenode:1234/URI/of/venv.tgz#environment"
    3.2 Set the PYSPARK_PYTHON  environment variable for the spark driver to ./environment/python
