### ISSUE TITLE
Long delay between SparkApplicationAdded and SparkApplicationSubmitted

### ISSUE THREAD

**Issue by jystephan** [kubeflow/spark-operator#1138]
Hello all,

There's a small delay (usually 3-4 seconds) between the events SparkApplicationAdded and SparkApplicationSubmitted, as in the logs below:

```
16:41:08: [spark-operator] SparkApplicationAdded: SparkApplication word-count-20210121-164108-feuds was added, enqueuing it for submission 
16:41:11: [driver:default-scheduler] Scheduled: Successfully assigned spark-apps/word-count-20210121-164108-feuds-driver to <node-pool>
16:41:11: [driver:kubelet] FailedMount: MountVolume.SetUp failed for volume "spark-conf-volume" : configmap "word-count-20210121-164108-feuds-e635b37725d239f6-driver-conf-map" not found 
16:41:12: [spark-operator] SparkApplicationSubmitted: SparkApplication word-count-20210121-164108-feuds was submitted successfully 
```

I've observed that this delay increases when many applications are submitted roughly at the same time. 
In my test, I submitted 4 applications, and here are the times I got:

* App 1: delay of 10 seconds (SparkApplicationAdded 16:37:25, SparkApplicationSubmitted 16:37:35)
* App 2: delay of 13 seconds (SparkApplicationAdded 16:37:26, SparkApplicationSubmitted 16:37:39)
* App 3: delay of 14 seconds (SparkApplicationAdded 16:37:27, SparkApplicationSubmitted 16:37:41)
* App 4: delay of 16 seconds (SparkApplicationAdded 16:37:29, SparkApplicationSubmitted 16:37:45)

If I submit 10 applications, the delay grows to 35 seconds in my tests, and I think that by submitting even more applications I can make this delay arbitrarily large. 

My questions:
* What is the source of the delay? What is the main bottleneck?
* How can we troubleshoot this (which kind of logs should we look at, if any)? 
* How can we reduce this delay (e.g. spark-operator properties, or other changes)?

Advice/Feedback from the community much appreciated -- Thank you!

**Comment by shinen** [comment]
Having similar issue. My case is even worst that usually 30~mins needed for an added sparkApplication to be submitted by the operator. 

Using latest helm chart to deploy to aks.

During the delay, no event is watched by the spark operator. What I can observe is that only the sparkApplication is created. No driver no executor and no events in spark operator log. 

The same also happens to delete event that terminated spark-driver does not get cleaned up after deleting the sparkApplication.

**Comment by shinen** [comment]
In my case, I find that webhook is doing some work and seems it takes such long time.
During this period, all the sparkapplication CRD events are not watched by the spark-operator.
```
I0127 03:00:07.190490       9 webhook.go:246] Serving admission request
I0127 03:00:07.191837       9 webhook.go:540] Pod  in namespace {ns1} is not subject to mutation
I0127 03:01:29.193931       9 webhook.go:246] Serving admission request
I0127 03:01:29.194462       9 webhook.go:540] Pod  in namespace {ns2} is not subject to mutation
I0127 03:05:08.694685       9 webhook.go:246] Serving admission request
I0127 03:05:08.696249       9 webhook.go:540] Pod  in namespace {ns3} is not subject to mutation
I0127 03:10:10.138694       9 webhook.go:246] Serving admission request
I0127 03:10:10.140625       9 webhook.go:540] Pod  in namespace {ns4} is not subject to mutation
```

Will spark-operator start to watch the event again only after handling all the admission request? Any way to configure spark-operator webhook to only handle few namespaces?

**Comment by renanxx1** [comment]
@shinen Did you find any solution for this problem ?
