### ISSUE TITLE
Missing option to set spec.strategy.type to RollingUpdate

### ISSUE THREAD

**Issue by Toerq** [kubeflow/spark-operator#1139]
Hello,

To enable zero-downtime updates of the Spark Operator deployment, it should be possible to set spec.strategy.type to RollingUpdate. This option is not possible to set when installing via helm without downloading the chart.

Can this option be added? Or is there a risk involved with having two different Spark operator versions running in parallel?

**Comment by AliGouta** [comment]
`spec.strategy.type` does not appear in the CRD, and this is not how the operator works. The operator implementes a state machine to start/stop/terminate a spark job. Now regarding the second part of your question, you may have two operators installed on the same cluster (and different versions) and each one filters sparkAapplications on specific labels. You just need to carefully configure the operator c.f. [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#running-multiple-instances-of-the-operator-within-the-same-k8s-cluster).
