### ISSUE TITLE
Migrate Spark 3 metrics to use PrometheusServlet

### ISSUE THREAD

**Issue by dszakallas** [kubeflow/spark-operator#1141]
We could utilize Spark 3's prometheus support, instead of using the JMX exporter. This would get rid of the additional complexity and CPU overhead of running the exporter agent. However, I am almost 100% sure this is going to change the exposed set of metrics and their names. Spark's documentation is not to great on the PrometheusServlet usage, here's a better tutorial: https://dzlab.github.io/bigdata/2020/07/03/spark3-monitoring-1/.

**Comment by arghya18** [comment]
Any update on this?
