### ISSUE TITLE
Spark-operator issue with istio

### ISSUE THREAD

**Issue by shinen** [kubeflow/spark-operator#1148]
Currently I have istio enabled on the aks cluster.

However, even though the istio-proxy & spark-operator container are running, there are still some issue.

1. The webhook fails to communicate and kubectl logs {operator-pod} -c {operator-container} give the following for action in webhook.go.
It is quite hard to debug, even by checking istiod logs and istio proxy log. 
```
yyyy/MM/dd 03:40:00 http: TLS handshake error from 127.0.0.1:port: EOF
yyyy/MM/dd  03:40:00 http: TLS handshake error from 127.0.0.1:port: EOF
```
After installing spark-operator without istio, we find that corresponding log should be 
```
I0xxx 03:30:05.xxxx       9 webhook.go:246] Serving admission request
I0xxx 03:30:05.xxxx       9 webhook.go:540] Pod  in namespace xxx is not subject to mutation
```

2. After submitting a sparkapplication, it is found that sparkapplication is successfully created/deleted by checking "kubectl get sparkapplication", but the corresponding actions on driver podwould be performed only after an nondeterministic period (maybe few hours).  Operator logs will also be flooded after this period. Within this nondeterministic period, no logs except the webhook error log mentioned above are shown. 

3. After the driver pod is generated, it is found that within also an nondeterministic period since the pod is generated (or more accurately is that the spark-operator starts to work), new sparkapplications and driver pods can be generated immediately. Same apply to delete action.

For 2 & 3, I suspect is the spark-operator (even for controller) are somehow getting blocked? Because the controller fails to watch the CRD events immediately.

---
All the above issue disappears when we do not enable istio injection. 
However avoiding istio-injection may not be a valid workaround for my case... (even though it seems istio is currently not well-supported by spark-operator). 

Has anyone also encountered similar issue? Any method to debug those issue? Appreciate if anyone in the community could help.

**Comment by aspring** [comment]
These are a few of the things we have done in our cluster to get it working with Istio:

- We exclude the webhook port from istio to allow the API to connect to the port properly
- We run a PeerAuthentication config that makes port 4040, 7078 and 7079 to permissive for matchlabels for spark-role: driver
- We run an internally built operator docker image that runs the entrypoint script with envoy-preflight as well as pulls in a cherry picked gencert.sh script to work around an issue that has been resolved in this repo but hadnt been released yet

**Comment by shinen** [comment]
May ask if you have encounter the long delay issue?
