### ISSUE TITLE
Install without helm chart

### ISSUE THREAD

**Issue by vvavepacket** [kubeflow/spark-operator#1149]
How do we install spark operator if Helm chart is not an option? Where are the yaml files located to just pipe into `kubectl apply`?

**Comment by nikopen** [comment]
@vvavepacket https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/v1beta2-1.2.2-3.0.0/manifest

Can certainly be improved - helm is not universally preferred indeed

**Comment by TomHellier** [comment]
You could install Helm, and then run [helm template](https://helm.sh/docs/helm/helm_template/)? 

that'll spit out the kubernetes manifests
