### ISSUE TITLE
Spark operator not running in one of the examples [Spark-Pi]

### ISSUE THREAD

**Issue by vvavepacket** [kubeflow/spark-operator#1151]
I followed the quick start guide and use the [spark-pi ](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml)application in the samples.

The problem are the following:
1. All computation is run on the driver pod instead of the executor pod.
2. No executor pod/s has been spinned up

![image](https://user-images.githubusercontent.com/8295642/106700485-f1307180-65b2-11eb-91d5-266836958b0a.png)

My understanding is the driver pod will just get the results from executor pod. In the yaml, we defined 1 executor but it looks like its not being used. Why is the executor pod not created and the driver pod doing all the work?

**Comment by kz33** [comment]
Hi, @vvavepacket.
executor pods will be killed when jobs is finished. so you can't see the executor pods. 

You can set `arguments`.
eg:
```
arguments:
- "10000"
```

it will run long time  so that you can find executor pods
