### ISSUE TITLE
Master address when running on k8s

### ISSUE THREAD

**Issue by vvavepacket** [kubeflow/spark-operator#1158]
In a typical spark application (without k8s), there is a master address we need to configure, something like this

```
  val spark = SparkSession.builder()
    .appName("Popular Items")
    .master("local[2]")
    .getOrCreate()
```

Which means point the master to localhost with 2 threads running..

Now when running and using spark-on-k8s-operator, what should we use? Should we still use local[2] or shall we use the k8s service name (if yes, where can we find the proper value)?

**Comment by AliGouta** [comment]
This should be hidden for you. You should not need have this in your code, please remove `.master("local[2]")` and let the operator establish the connection to the master
