### ISSUE TITLE
Add enableServiceLinks flag support

### ISSUE THREAD

**Issue by korjek** [kubeflow/spark-operator#1160]
That would be great if we could pass a value to `enableServiceLinks` parameter.

Usecase:
We run a lot of Spark Applications and keep terminated resources for 30 days (so ppl can check them). And with default `enableServiceLinks: true` every pod is prepopulated with a looot of service-related environment variables. So it would be great if there is a possibility to disable this default behavior in case ppl do not need it.

**Comment by indianmifan** [comment]
I also hit the limit. It will be useful if we enable this parameter.
