### ISSUE TITLE
Running different version of spark jobs on a spark-operator cluster

### ISSUE THREAD

**Issue by vvavepacket** [kubeflow/spark-operator#1163]
Is it possible to run multiple spark jobs/spark applications (each having their own version, i.e. SparkApplication 1 uses Spark 2.4 and SparkApplication 2 uses Spark 3.0.0) in a single namespace?

So I will be creating different sparkapplications and submit them to k8s. Will it cause any issue or is it totally fine?

**Comment by jkleckner** [comment]
Yes, just use the appropriate image for your application.  Personally, I build my own spark 2.4.x to get fixes that haven't been released yet such as https://github.com/apache/spark/pull/30283
