### ISSUE TITLE
Configure PriorityClassName

### ISSUE THREAD

**Issue by mcristina422** [kubeflow/spark-operator#1167]
Currently `PriorityClassName` is a configuration under `BatchSchedulerOptions`, but a batch scheduler is not needed for using [priority classes](https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#priorityclass). 

I think that drivers and executers should be able to set their own `PriorityClassName` regardless of volcano or other schedulers. Should this parameter be moved outside of the `BatchSchedulerOptions`? Or should `BatchSchedulerOptions` be renamed to `SchedulerOptions` to make it more generic/clear?

**Comment by HHK1** [comment]
I agree it's pretty confusing to have this inside `BatchSchedulerOptions`. I think it would be clearer to move it outside the `BatchSchedulerOptions` and have a dedicated option for priorities

**Comment by liyinan926** [comment]
I agree that it should be moved outside `BatchSchedulerOptions`.

**Comment by claas-fridtjof-lisowski** [comment]
It would be also good if the spark-operator deployment itself has an option to set a `PriorityClassName`
