### ISSUE TITLE
How to expose spark-ui as node-port 

### ISSUE THREAD

**Issue by satyam130** [kubeflow/spark-operator#1180]
Hi Team,

Problem- currently ingress creation is a manual process in our k8 cluster. It does not get get created as part of helm so for every spark application UI we had to create a sperate ingress entry pointing to its service name which is not a feasible solution.

Query- can we make SPARK-UI service as node port in k8-operator to get rid of the above problem. Or can you provide any feasible solution to expose the SPARK_UI so that i do not have to create separate ingress entry for each sparkapplication.

I am using spark-operator:3.0.0 version .

**Comment by tekumara** [comment]
You can specify a ServiceType of NodePort, see https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1100
