### ISSUE TITLE
Upgrade Helm Chart appVersion Parameter

### ISSUE THREAD

**Issue by Jimmy-Newtron** [kubeflow/spark-operator#1199]
The helm chart use the value **image.tag** during the deployment of the docker image and as the documentation says

>  Overrides the image tag whose **default is the chart appVersion**

This means that the default is appVersion: **v1beta2-1.2.0-3.0.0**

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/1947244ce5f4ea0c39b7fa3707d36287e9922249/charts/spark-operator-chart/Chart.yaml#L5

There is a recurring issue: volumes and configmaps are not mounted from the webhook
The issue has been fixed in latest docker image version, but to be more precise there are 2 new releases

**v1beta2-1.2.1-3.0.0** (latest)
In the [comparison with the previous version](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/compare/v1beta2-1.2.0-3.0.0...v1beta2-1.2.1-3.0.0) there is a [commit that solves the problem](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/f89457020e8ea5849f66392eccc34184fad39fd5) (issue #1027) 

**v1beta2-1.2.2-3.0.0** (docker image not released)
In the [comparison with the previous version](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/compare/v1beta2-1.2.0-3.0.0...v1beta2-1.2.2-3.0.0) there is a [commit that solves the problem](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1058) (issue #1058) 

Can someone push an update and publish a new version of the Helm Chart?

**Comment by yishanhe** [comment]
when will the v1beta2-1.2.2-3.0.0  image be released? Thanks.
