### ISSUE TITLE
Use custom spark app name in spark.ui.proxyBase

### ISSUE THREAD

**Issue by jijosg** [kubeflow/spark-operator#1208]
Hi,

I have configured the `ingressUrlFormat=<hostname>/spark/{{$appName}}(/|$)(.*)`

I am trying to submit a SparkApplication with following config where a new sparkapp name will be created each time its submitted and want to use this newly created sparkapp name in the spark.ui.proxyBase

```
metadata:
    generateName: spark-pi-example-
spec:
    sparkUIOptions:
        ingressAnnotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
    sparkConf:
        spark.ui.proxyRedirectUri                   : <hostname>
        spark.ui.proxyBase                          :  /spark/<spark-app-name>
```
How can i dynamically insert `<spark-app-name>` in spark.ui.proxyBase ?

What are some of the other options for ingressUrlFormat, ie other than {{$appName}} & {{$appNamespace}}

**Comment by ZPerling** [comment]
I also have the same problem, Did you solve it？

**Comment by jijosg** [comment]
No still facing the issue havent tried the latest chart though

**Comment by matschaffer-roblox** [comment]
From reading https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/5f2efd4ff97e7c0bfdb726a066118d3401576730/pkg/controller/sparkapplication/sparkui.go#L46-L63 - it looks like appName and appNamespace are the only two options.
