### ISSUE TITLE
how to create driver and executor pod synchronously

### ISSUE THREAD

**Issue by yiyuanyu17** [kubeflow/spark-operator#1220]
when use spark operator , i found the driver pod will be created immediatly, and after while, the executor pods will be created.  this will result in a situation if we have many sparkapplcations to be created at same time, drivers will be created and all executors will be pending state if all pod all need gpu resource, which leads to a deadlock.

**Comment by yiyuanyu17** [comment]
> when use spark operator , i found the driver pod will be created immediatly, and after while, the executor pods will be created. this will result in a situation if we have many sparkapplcations to be created at same time, drivers will be created and all executors will be pending state if all pod all need gpu resource, which leads to a deadlock.

**Comment by william-wang** [comment]
@yiyuanyu17 
The batch scheduler volcano in spark-operator already supported this in another way.
The driver and executor are created in one podgroup. The podgroup is scheduled as a unit. The resource request in podgroup can be reserved to avoid deadlock issue.

Here are some doc for your reference.
1. The batch scheduler in spark-operator
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/volcano-integration.md
2. The podgroup reserved resource support customization
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-custom-resource.yaml
