### ISSUE TITLE
java11 docker image for sparkoperator 

### ISSUE THREAD

**Issue by suvashishtha** [kubeflow/spark-operator#1223]
Is there a docker image which has java11 installed for spark versions 3.0.0 and above?

**Comment by fcenedes** [comment]
Hi

the base image for Spark 3 has Java11 src : https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile

You can use the image published by the spark-on-k8s-operator project : gcr.io/spark-operator/spark:v3.1.1

**Comment by suvashishtha** [comment]
i am using gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus and the default java is java8. do I need to upgrade spark to 3.1.x?

**Comment by fcenedes** [comment]
No not necessarily.

Maybe you could simply build your own docker image :

`ARG SPARK_IMAGE=gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus
FROM ${SPARK_IMAGE}`

You can inspired by AdoptOpenJDK DockerFiles
and inject an updated JRE of your choice

**Comment by jdonnelly-apixio** [comment]
In most cases java 8 jars will work on java 11. Either you'll hit an incompatibility issue early on or if it works, it should be safe.
