### ISSUE TITLE
The `latest` image tag does not match the default (`latest`) spark operator helm

### ISSUE THREAD

**Issue by swill** [kubeflow/spark-operator#1253]
If I run the following command:
```
helm install sparky spark-operator/spark-operator --namespace spark-operator --create-namespace --set webhook.enable=true
```

This will produce the following deployment (as per the current date):
```
NAME  	NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART               	APP VERSION        
sparky	spark-operator	1       	2021-05-06 16:46:06.237538298 -0400 EDT	deployed	spark-operator-1.1.0	v1beta2-1.2.3-3.1.1
```

However, the actual deployment will fail because the webhook can not come up.  If I get the logs for the `sparky-spark-operator-webhook-init-<hash>` pod, I see the following error.
```
Unrecognized option: -r
```

After some digging, I have found that a new `-r` flag has been added to this file: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/hack/gencerts.sh#L31

If I describe this pod, I can see that it references the image at: `gcr.io/spark-operator/spark-operator:latest`

That all makes sense so far, but when I go and look at which image that is referencing, I find this.

![image](https://user-images.githubusercontent.com/13644/117364696-3b641000-ae8c-11eb-83e3-1c7c3034fbe7.png)

You will notice that the `latest` tag has not been updated to reference the appropriate image that is associated with the helm version.

**Comment by swill** [comment]
I will also note that the current docs associated with the [Mutating Admission Webhook](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#about-the-mutating-admission-webhook) are quite confusing.

Do we always have to run this command?
`kubectl apply -f manifest/spark-operator-with-webhook.yaml`

Is that command used instead of specifying the `--set webhook.enable=true` parameter in the `helm install`?

Do I need to run this command after installing using the `--set webhook.enable=true` parameter?

Lets just say, the current documentation leaves me wondering what is the right way to get the Mutating Admission Webhook functionality working correctly.

**Comment by swill** [comment]
Even though I believe this issue will be short lived, with the tag being updated on the repo, I want to make sure to leave a solution here as well in case others run into this situation and need to move forward.

Here is a command which will specify the appropriate image to target to move past this error:
```
helm install sparky spark-operator/spark-operator --namespace spark-operator --create-namespace --set webhook.enable=true --set image.repository=gcr.io/spark-operator/spark-operator --set image.tag=v1beta2-1.2.3-3.1.1
```

Note: My release is called `sparky`, which is why you see it referenced in my posts.

**Comment by allanhung** [comment]
I think you can pass image.tag="" so the image tag will be the chart appVersion.
```
helm install sparky spark-operator/spark-operator --namespace spark-operator --create-namespace --set webhook.enable=true --set image.repository=gcr.io/spark-operator/spark-operator --set image.tag=""
```
