### ISSUE TITLE
using zeppelin spark interpreter with the operator

### ISSUE THREAD

**Issue by mvu-tk** [kubeflow/spark-operator#1257]
Hi team,

I'm trying to use zeppelin with the operator but I don't know how to use it.
Normally zeppelin interpreter would act as the driver program.
How can this fit into the operator world?

thanks,
-M

**Comment by jdonnelly-apixio** [comment]
I haven't tried setting up zeppelin, but something a little custom like [this](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1116) could probably work. I've had success with running the spark thrift server with this method. If you try this route and are successful, could you post details? At some point, I want to provide notebook functionality for my clusters and am contemplating using zeppelin with the spark thrift work around method as a stop gap before we get to jupyter notebooks provided by kubeflow (kubeflow uses spark on k8s operator for spark stuff, is pretty complex, but incredibly promising).
