### ISSUE TITLE
v3.1.1-gcs-prometheus not available

### ISSUE THREAD

**Issue by michaelschiff** [kubeflow/spark-operator#1266]
Seems like either the documentation was accidentally updated or that the image was unintentionally taken down.  A couple places in the documentation make reference to this image:
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-prometheus.yaml
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#monitoring

**Comment by devender17** [comment]
Yeah. Can't find it at https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark?tag=v3.1.1-gcs-prometheus&gcrImageListsize=30

**Comment by jdonnelly-apixio** [comment]
Not sure if I'm missing any steps, but I'm maintaining my own image built on top of theirs and it's been working for us. I just added this in my dockerfile:
```
RUN mkdir /prometheus -p
ADD jmx_prometheus_javaagent-0.11.0.jar /prometheus/jmx_prometheus_javaagent-0.11.0.jar
ADD jmx_prometheus_javaagent-0.13.0.jar /prometheus/jmx_prometheus_javaagent-0.13.0.jar
```

**Comment by matthewygf** [comment]
Just a note, you can build your own in the "[spark-docker](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/spark-docker)" directory

**Comment by gp5ingh** [comment]
Hi @matthewygf, the https://github.com/kubeflow/spark-operator/tree/master/spark-docker also has reference to gcr.io/spark-operator/spark:v3.1.1 here:
https://github.com/kubeflow/spark-operator/blob/4108f5493706f463cc2ceb823b66b5e6ac8fb1ca/spark-docker/Dockerfile#L17C17-L17C51
is there a place where I can find the source code and build my own image?
