### ISSUE TITLE
Python 3 version is ignored

### ISSUE THREAD

**Issue by Shauli10** [kubeflow/spark-operator#1276]
I set Python version to 3 in the spec
`type: Python
  pythonVersion: "3"`

But when the Python script contains Python 3 features (e.g. f strings) I get an error that indicates the feature isn't recognized.

**Comment by jdonnelly-apixio** [comment]
@Shauli10 What spark version are you on? This works for me using an image built on `gcr.io/spark-operator/spark:v3.1.1-hadoop3`.

**Comment by Alienfeel** [comment]
same issue when we use spark2.4.8
