### ISSUE TITLE
Cannot set paramter ingress-url-format

### ISSUE THREAD

**Issue by chen622** [kubeflow/spark-operator#1285]
I first tried to use command `helm install my-release spark-operator/spark-operator --namespace spark-operator --set ingress-url-format={{$appName}}.k8s.a.com` to install spark-operator, but i can not accsess the driver web ui. I found the spark-operator pod has empty  value of the ingress-url-format paramter.

Finally I changed the [chart config file](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/charts/spark-operator-chart/values.yaml) locally, and used command `helm install my-release /path/spark-on-k8s-operator/charts/spark-operator-chart -f  /path/spark-on-k8s-operator/charts/spark-operator-chart/values.yaml --nam
espace=spark-operator` to install. And I can accsess the driver web ui now.

**Comment by pierre-hamy** [comment]
Could you try
`--set ingressUrlFormat=... `?
