### ISSUE TITLE
Is it possible to run Spark 3.1.2 with the Spark Operator v1beta2-1.1.2-2.4.5

### ISSUE THREAD

**Issue by KlausTele** [kubeflow/spark-operator#1308]
I'm migrating my Spark application from 2.4.5 to 3.1.2 and was wondering if I need to upgrade the spark operator as well?

**Comment by yauhen-sobaleu** [comment]
So can we just set `sparkVersion` to `3.1.2` ?

**Comment by ringtail** [comment]
If you don't want to use the features in spark3.0. I think the answer is 'Yes'.  There are three places need spark release(operator,driver and executor). Even you use 2.4.5 spark kernel,you can also submit a 3.1.2 spark job.
