### ISSUE TITLE
no git tag for v1beta2-1.2.3-3.1.1

### ISSUE THREAD

**Issue by jdonnelly-apixio** [kubeflow/spark-operator#1310]
It doesn't look like there is a git tag for `v1beta2-1.2.3-3.1.1` for this repo:
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tags

We are trying to create a mac brew for sparkctl and we think we might have a harder time getting it approved without a tag.

**Comment by huineng** [comment]
that is in my opinion the tag of the image , not the helm chart 
https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark-operator?gcrImageListsize=30
