### ISSUE TITLE
tolerations feature is not getting enabled even after enabling mutating admission webhook. 

### ISSUE THREAD

**Issue by santoshdevops119** [kubeflow/spark-operator#1315]
I have enabled mutating admission webhook as per documentation , but Tolerations is not being considered while creating spark application driver pod and pod is getting stuck in pending state with error pod did not tolerate node taint .
Can someone please look into it.

**Comment by santoshdevops119** [comment]
it got resolved after redeploying the spark-opeartor from scratch. So closing the issue.

**Comment by santoshdevops119** [comment]
issue appeared again.

**Comment by ringtail** [comment]
Could you describe the MutatingWebhookConfiguration spark-webhook-config
