### ISSUE TITLE
How can I refer to a release as a Go module dependency?

### ISSUE THREAD

**Issue by nickwallen** [kubeflow/spark-operator#1323]
How can I refer to a release as a Go module dependency?

The current tag naming scheme seems to tag the 1.2.2 release as `v1beta2-1.2.2-3.0.0`.  This format does not seem to follow the semantic versioning scheme that Go modules expect, but I could be wrong.

This may just be related to #1198, but here is what I've tried.
```
$ go mod init example.com/m
$ go get k8s.io/client-go
$ go get k8s.io/apiextensions-apiserver
$ go get github.com/GoogleCloudPlatform/spark-on-k8s-operator@v1beta2-1.2.2-3.0.0

go get: github.com/GoogleCloudPlatform/spark-on-k8s-operator@none updating to
	github.com/GoogleCloudPlatform/spark-on-k8s-operator@v0.0.0-20201215015655-2e8b733f5ad0 requires
	k8s.io/apiextensions-apiserver@v0.0.0: reading k8s.io/apiextensions-apiserver/go.mod at revision v0.0.0: unknown revision v0.0.0
```

Alternatively, I tried to use the k8s.io version specified in the v1beta2-1.2.2-3.0.0 release.
```
$ go mod init example.com/m
$ go get k8s.io/client-go@v0.16.6
$ go get github.com/GoogleCloudPlatform/spark-on-k8s-operator@v1beta2-1.2.2-3.0.0

go get: github.com/GoogleCloudPlatform/spark-on-k8s-operator@none updating to
	github.com/GoogleCloudPlatform/spark-on-k8s-operator@v0.0.0-20201215015655-2e8b733f5ad0 requires
	k8s.io/apiextensions-apiserver@v0.0.0: reading k8s.io/apiextensions-apiserver/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**Comment by sairamankumar2** [comment]
Hi @nickwallen 
I also face the same issue and were you able to find the solution to fix this issue. Have attached the go get output.

`go get github.com/GoogleCloudPlatform/spark-on-k8s-operator
go: github.com/GoogleCloudPlatform/spark-on-k8s-operator@v0.0.0-20210822172015-74ea1c86c9a5 requires
        k8s.io/kubernetes@v1.19.6 requires
        k8s.io/api@v0.0.0: reading k8s.io/api/go.mod at revision v0.0.0: unknown revision v0.0.0`
