### ISSUE TITLE
Running multiple transformation/jobs on single spark operator simultaneously 

### ISSUE THREAD

**Issue by anandchangediya** [kubeflow/spark-operator#1326]
I want to run multiple streaming applications on spark using spark operator. I deployed a single application as per guides and can see the resources being allocated but can I have a single spark operator and deploy multiple applications/jobs on to same as we can do with spark submit.

**Comment by gauravbh1** [comment]
Of course you can run multiple spark streaming or non streaming applications on a single spark operator. Just have an individual deployment yaml for each application you wish to deploy.
