### ISSUE TITLE
Use spark master in local intellij idea

### ISSUE THREAD

**Issue by prathmeshvr** [kubeflow/spark-operator#1332]
Hello guys I am running spark operator on AWS eks cluster and everything is working fine .Now I wanted to run spark job by using master on intellij idea .Can anyone give me some ideas how to set it up

**Comment by fcenedes** [comment]
Hi,

have you take a look here : 

https://www.jetbrains.com/help/idea/big-data-tools-spark-submit.html#spark-submit
