### ISSUE TITLE
Spark 3.1.2 support

### ISSUE THREAD

**Issue by simplylizz** [kubeflow/spark-operator#1333]
Hello,

Is there any plans to add Spark 3.1.2 support?

**Comment by prathmeshvr** [comment]
Hey you can create your own docker image which is inside the Apache Spark repo
Path =spark/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/

**Comment by zencircle** [comment]
> Hey @enricorotundo, spark-operator should be built on top of a spark image (as of now default is gcr.io/spark-operator/spark:v3.1.1). To build operator, follow instructions in doc: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/developer-guide.md#build-the-operator In case if you want to use another spark version or custom spark build - you need to build your own image. Refer spark docs for details: https://spark.apache.org/docs/latest/running-on-kubernetes.html#docker-images

Docker-build script (docker-image-tool.sh) - Cannot find Spark JARs. This script assumes that Apache Spark has first been built locally or this is a runnable distribution. 
Can you please point the `Dockerfile` used to build version `gcr.io/spark-operator/spark:v3.1.1`. I can use that as a reference to build my own image
