### ISSUE TITLE
Support labels for SparkUIConfiguration

### ISSUE THREAD

**Issue by themoah** [kubeflow/spark-operator#1342]
Hi,

Is there an option to support additional labels on SparkUIConfiguration? Or an ability to propagate labels from SparkApplication to UI? As now service created by Spark Operator has only these key:
```
    sparkoperator.k8s.io/app-name: 
    sparkoperator.k8s.io/submission-id: 
```

But I'm looking for an option to add custom ones. 

Thanks!

**Comment by Cian911** [comment]
Jumping in here to revive this... 

In my org, we're using [opa gatekeeper](https://github.com/open-policy-agent/gatekeeper) which has restrictions and best practices around labels for k8s manifests. Whilst we _can_ whitelist services from these restrictions, we'd rather not. So having the ability to set labels for services (or anything really) would be very handy.

Short of forking the repo and taking a stab at it myself - Is there any plans to accomodate this? @liyinan926

**Comment by Cian911** [comment]
Ok, I made the change myself: https://github.com/kubeflow/spark-operator/pull/1952
