### ISSUE TITLE
Can't start spark-operator with webhook=enabled

### ISSUE THREAD

**Issue by DanielKorow** [kubeflow/spark-operator#1346]
When I try to start spark-operator with enabled webhook I receive that log
`I0907 10:26:15.465503      11 main.go:177] Enabling metrics collecting and exporting to Prometheus`
`I0907 10:26:15.465675      11 metrics.go:142] Started Metrics server at localhost:10254/metrics`
`I0907 10:26:15.469193      11 webhook.go:218] Starting the Spark admission webhook server`
`I0907 10:26:15.493556      11 webhook.go:412] Creating a MutatingWebhookConfiguration for the Spark pod admission webhook`
`F0907 10:26:15.502685      11 main.go:208] the server could not find the requested resource`
If disable webhook it works well.

**Comment by SunshineOnACloudyDay** [comment]
I had the exact same logs, but was able to start spark-operator when running with Kubernetes < 1.22.
My suspicion is the removal of the ["Beta versions of the ValidatingWebhookConfiguration and MutatingWebhookConfiguration API" in the recent 1.22 release of Kubernetes](https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#api-changes) is causing the webhook to not be able to start up.

**Comment by ofinto** [comment]
Guys do you have any news about it? I saw that chart was updated, but it did not help. I updated kubernetes to v1.22.4 and now, chart doesnt work

**Comment by spanglerco** [comment]
Looks like this is the same as #1375 which has had more discussion.

**Comment by aneagoe** [comment]
@DanielKorow if you're running on a version older than 1.22 you should be fine with some of the older images and the current chart. If deploying on 1.22 you'll need to use `ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.3-3.1.1` which has full support for 1.22, by overriding some of the helm settings: `--set image.tag=v1beta2-1.3.3-3.1.1 --set image.repository=ghcr.io/googlecloudplatform/spark-operator`
