### ISSUE TITLE
Missing image tag

### ISSUE THREAD

**Issue by vqcuong** [kubeflow/spark-operator#1347]
I ' ve read user guide from https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#monitoring. In monitoring section, I've try using image tag:  gcr.io/spark-operator/spark:v3.1.1-gcs-prometheus. But I'm not found this tag (v3.1.1-gcs-prometheus) on the registry: gcr.io/spark-operator/spark

**Comment by ppletscher** [comment]
Duplicate of https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1266
