### ISSUE TITLE
create a spark image with hadoop 3.3.0

### ISSUE THREAD

**Issue by franck-cussac** [kubeflow/spark-operator#1352]
Hello,

I try to run a spark job with your image gcr.io/spark-operator/spark:v3.1.1-hadoop3 but I can't access to my S3 bucket using role IAM.
In this image you are using hadoop 3.2.0 so I have to use hadoop-aws:3.2.0 to be compatible. But this jar includes aws-java-sdk-bundle:1.11.375 which can't use the role IAM assumed by my container.

I try to use aws-sdk embedded by hadoop-aws-3.3.0 and it works but I don't find a gcr.io/spark-operator/spark image with hadoop 3.3.0 so it's not compatible with your image.

Where can I find your Dockerfile to contribute or just rewrite my own image ?

Can you build a new spark image with hadoop 3.3.0 ?

Thank you.

**Comment by dlubomski** [comment]
is there a difference between image gcr.io/spark-operator/spark and this one generated by docker-image-tool.sh ?
