### ISSUE TITLE
serviceaccounts "my-release-spark-operator" already exists

### ISSUE THREAD

**Issue by Oneal65** [kubeflow/spark-operator#1359]
I reinstall operator, the error happen. Before that happened , I use helm uninstall spark-operator/spark-operator.
the command is : 
helm install my-release spark-operator/spark-operator --namespace spark-operator --set enableBatchScheduler=true --set enableWebhook=true
the error message is: 
![image](https://user-images.githubusercontent.com/13121552/135049856-1bb62f2d-a82f-4b4c-966f-222560b189e4.png)
Error: failed pre-install: warning: Hook pre-install spark-operator/templates/serviceaccount.yaml failed: serviceaccounts "my-release-spark-operator" already exists

**Comment by TiansuYu** [comment]
Second this issue. Major road blocker for short-lived deployments. 

I also have tried to `k delete serviceaccount my-release-spark-operator` and `k delete namespace my-namespace` but it seems this error could not go away. The reason could be that for now helm does not mutate certain k8s objects properly (see https://github.com/helm/helm/issues/5473 and related issues). 

Would love to know any workaround. Cuz currently even if I manually delete everything under my namespace, including the service account, helm still complains about the issue shown above when I try to `helm install xxx` again. This applies to the `spark-pi` example in the quick-start tutorial. 

An unmutable / non-upgradable deployment is by all means should be avoided. I think this issue should be addressed somehow.

**Comment by swartz-k** [comment]
Looks like those command need to exec.
```
kubectl -n RELEASE-NAMESPACE delete sa  my-release-spark-operator 
kubectl -n RELEASE-NAMESPACE delete clusterrole  my-release-spark-operator
kubectl -n RELEASE-NAMESPACE delete clusterrolebinding  my-release-spark-operator
```

**Comment by swartz-k** [comment]
I think `templates/rbac.yaml` need add `before-hook-creation` in annotation `helm.sh/hook-delete-policy`.

**Comment by TiansuYu** [comment]
Thx, I have found out the same yesterday.

**Comment by swartz-k** [comment]
> Thx, I have found out the same yesterday.

Maybe you can make a PR to fix it.

**Comment by TiansuYu** [comment]
Would love to do it once I find the time.

**Comment by TiansuYu** [comment]
Thx, I have opened the PR here https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1384.

**Comment by echang0929** [comment]
@swartz-k @TiansuYu @liyinan926, I found this as well, but there is no issue in the tags/**v1beta2-1.2.2-3.0.0**, i.e. 

* remove operator's sa, clusterrole and clusterrolebinding when uninstalling this helm chart
* keep two crd, sparkapp and scheduledsparkapp, so that all of their resources in job namespace are kept. 

Why?
