### ISSUE TITLE
Failed to install CRD on k8s 1.15 

### ISSUE THREAD

**Issue by Oneal65** [kubeflow/spark-operator#1360]
the commend is:
`helm install my-release spark-operator/spark-operator --namespace spark-operator --create-namespace --set enableBatchScheduler=true --set enableWebhook=true`
the error message is:
`Error: failed to install CRD crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"`
k8s version is:
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}`
`Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by ssullivan** [comment]
I have been having similar problems. I've only been able to use spark operator when the Kubernetes version is <1.22.
I think this is related to issue https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1346.
