### ISSUE TITLE
Is it possible to collect detailed logs (stdout / stderr) from workers?

### ISSUE THREAD

**Issue by jose-jurado-empathy** [kubeflow/spark-operator#1361]
Hi team,
So far we managed to integrate the Spark operator to run jobs in Kubernetes.
We are also running a spark-history-server and are able to see event logs from the executions.
Now, we're wondering if it's possible to see stdout logs from executions at the UI.
As far as we can see, these so called "detailed" logs are not being collected into the S3 bucket. So it's normal that the UI doesn't show.
We're especially interested in being able to see the **stdout from driver** once the job is done and the pod is purged from Kubernetes.

Thanks in advance.

**Comment by fcenedes** [comment]
Hi,

one possible solution is to implement your own logger, and save the output to a file (shared FS) for instance.

1. package your app with a log4j configuration file
2. create an logger object like : `val logger: Logger = org.apache.log4j.Logger.getRootLogger`
3.  Set in the Spark Conf values like 

```
"spark.driver.extraJavaOptions": "-Dlog4j.configuration=file:///log4j.properties",  
"spark.executor.extraJavaOptions": "-Dlog4j.configuration=file:///log4j.properties"
```

my log4j file looks like this

```
# Set everything to be logged to the console
log4j.rootCategory=INFO, console
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.err
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Settings to quiet third party logs that are too verbose
log4j.logger.org.eclipse.jetty=OFF
log4j.logger.org.eclipse.jetty.util.component.AbstractLifeCycle=OFF
log4j.logger.org.spark-project.jetty.servlet.ServletHandler=OFF
log4j.logger.org.spark-project.jetty.server=OFF
log4j.logger.org.spark-project.jetty=OFF
log4j.category.org.spark_project.jetty=OFF
log4j.logger.Remoting=OFF
log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=INFO
log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=INFO
log4j.logger.org.apache.parquet=ERROR
log4j.logger.parquet=ERROR

# Setting properties to have logger logs in local file system
log4j.appender.rolling=org.apache.log4j.RollingFileAppender
log4j.appender.rolling.encoding=UTF-8
log4j.appender.rolling.layout=org.apache.log4j.PatternLayout
log4j.appender.rolling.layout.conversionPattern=[%d] %p %m (%c)%n
log4j.appender.rolling.maxBackupIndex=5
log4j.appender.rolling.maxFileSize=50MB
log4j.logger.org.apache.spark=OFF
log4j.logger.org.spark-project=OFF
log4j.logger.org.apache.hadoop=OFF
log4j.logger.io.netty=OFF
log4j.logger.org.apache.zookeeper=OFF
log4j.rootLogger=INFO, rolling
log4j.appender.rolling.file=/data/logs/${logfile.name}.log
```

**Comment by jose-jurado-empathy** [comment]
> Hi,
> 
> one possible solution is to implement your own logger, and save the output to a file (shared FS) for instance.
> 
> 1. package your app with a log4j configuration file
> 2. create an logger object like : `val logger: Logger = org.apache.log4j.Logger.getRootLogger`
> 3. Set in the Spark Conf values like
> 
> ```
> "spark.driver.extraJavaOptions": "-Dlog4j.configuration=file:///log4j.properties",  
> "spark.executor.extraJavaOptions": "-Dlog4j.configuration=file:///log4j.properties"
> ```
> 
> my log4j file looks like this
> 
> ```
> # Set everything to be logged to the console
> log4j.rootCategory=INFO, console
> log4j.appender.console=org.apache.log4j.ConsoleAppender
> log4j.appender.console.target=System.err
> log4j.appender.console.layout=org.apache.log4j.PatternLayout
> log4j.appender.console.layout.ConversionPattern=%d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
> 
> # Settings to quiet third party logs that are too verbose
> log4j.logger.org.eclipse.jetty=OFF
> log4j.logger.org.eclipse.jetty.util.component.AbstractLifeCycle=OFF
> log4j.logger.org.spark-project.jetty.servlet.ServletHandler=OFF
> log4j.logger.org.spark-project.jetty.server=OFF
> log4j.logger.org.spark-project.jetty=OFF
> log4j.category.org.spark_project.jetty=OFF
> log4j.logger.Remoting=OFF
> log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=INFO
> log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=INFO
> log4j.logger.org.apache.parquet=ERROR
> log4j.logger.parquet=ERROR
> 
> # Setting properties to have logger logs in local file system
> log4j.appender.rolling=org.apache.log4j.RollingFileAppender
> log4j.appender.rolling.encoding=UTF-8
> log4j.appender.rolling.layout=org.apache.log4j.PatternLayout
> log4j.appender.rolling.layout.conversionPattern=[%d] %p %m (%c)%n
> log4j.appender.rolling.maxBackupIndex=5
> log4j.appender.rolling.maxFileSize=50MB
> log4j.logger.org.apache.spark=OFF
> log4j.logger.org.spark-project=OFF
> log4j.logger.org.apache.hadoop=OFF
> log4j.logger.io.netty=OFF
> log4j.logger.org.apache.zookeeper=OFF
> log4j.rootLogger=INFO, rolling
> log4j.appender.rolling.file=/data/logs/${logfile.name}.log
> ```

Thank you for sharing it @fcenedes . We'll try this approach.

**Comment by gFazzari** [comment]
Any update on this?

**Comment by jose-jurado-empathy** [comment]
> Any update on this?

Hi @gFazzari ,
We finally applied a different solution, scrapping the stdout from driver and worker pods with `fluentd` and then exporting them to `Kibana`.
We still can't see the logs in the `spark-history-server UI`, but we got accustomed to check then in `Kibana` and that's good enough for us.
