### ISSUE TITLE
Auto scaling not working

### ISSUE THREAD

**Issue by bvkiran** [kubeflow/spark-operator#1371]
I am trying the operator on AKS with autoscale on. If the number of executor is below the current threshold it does not seem to kick in the autoscaler. I tried this with a simple service with replicas and the scaler works as advertised. Is there something different the spark operator does which does not auto scale?

**Comment by jalkjaer** [comment]
if your pods can fit on the existing nodes, then the autoscaler wont scale up.
If you want your spark job to run entirely on new scaled up nodes, you should create a separate node pool with taints and labels and then add nodeSelector / tolerations to driver/executor section in the SparkApp yaml. 
Taints and tolerations ensures that only the pods you specifically allow will be scheduled there, and not some stray pods that will keep your expensive instance from being scaled down
