### ISSUE TITLE
Failed to pull image "gcr.io/spark-operator/spark-operator:latest":

### ISSUE THREAD

**Issue by chlyzzo** [kubeflow/spark-operator#1372]
when i run ：
helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
and then:
helm install spark-operator-test spark-operator/spark-operator

get error:
 Failed to pull image "gcr.io/spark-operator/spark-operator:latest": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

so the image has access?

**Comment by TomHellier** [comment]
I've just seen [my pr was merged](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1422), so the image should exist at [ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.2-3.1.1](https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator)
