### ISSUE TITLE
Is it possible to add a configuration file for a process in the yaml file?

### ISSUE THREAD

**Issue by icuetara** [kubeflow/spark-operator#1374]
Hi everybody,

I'm trying to use kubernetes for launching a spark-submit but using a yaml file.

This would be the spark-submit working for the process:
`spark-submit 
--master k8s://https://$(minikube ip):8443 
--deploy-mode client 
--name kuberpoc 
--class com.jobs.WordCountLauncher 
--conf spark.executor.instances=2 
--executor-memory 1024m 
--conf spark.kubernetes.container.image=spark:latest 
--conf spark.kubernetes.authenticate.driver.serviceAccountName=spark 
file:///opt/spark-3.1.2-bin-hadoop3.2/examples/jars/wordcount-31-0.1.7-jar-with-dependencies.jar 
/opt/spark-3.1.2-bin-hadoop3.2/examples/src/main/resources/application1.conf`

And this is part of the yaml I have for running the code above, but I don't know how to add /opt/spark-3.1.2-bin-hadoop3.2/examples/src/main/resources/application1.conf to it:

> apiVersion: sparkoperator.k8s.io/v1beta2
> kind: SparkApplication
> metadata:
> &nbsp;&nbsp;&nbsp;name: kuberpoc
> &nbsp;&nbsp;&nbsp;namespace: default
> spec:
> &nbsp;&nbsp;&nbsp;type: Scala
> &nbsp;&nbsp;&nbsp;mode: cluster
> &nbsp;&nbsp;&nbsp;image: spark:latest
> &nbsp;&nbsp;&nbsp;mainClass: com.jobs.WordCountLauncher
> &nbsp;&nbsp;&nbsp;mainApplicationFile: file:///opt/spark-3.1.2-bin-hadoop3.2/examples/jars/wordcount-31-0.1.7-jar-with-dependencies.jar

Is there any mainApplicationConfig available? 

Thanks in advance

**Comment by jalkjaer** [comment]
You can volume mount a K8S configmap into the desired location, but be aware that it will hide everything that was in the directory in the image. I.e. if you mount into /opt/spark-3.1.2-bin-hadoop3.2/examples/src/main/application1.conf then that will be the only file in the src/main directory - so mount into some other unrelated location /myconf/application1.conf for instance
