### ISSUE TITLE
Is it possible to run spark driver and executor in separate nodes ?

### ISSUE THREAD

**Issue by parvaths1118** [kubeflow/spark-operator#1376]
Hello,

Is this possible to run the spark drivers and executors in a separate worker nodes in kubernetes.

I have tried using nodeSelector but both driver and executor is being deployed in the same node.

Please can you suggest if this is possible ? Thank you for your help.

**Comment by jalkjaer** [comment]
Yes that is possible.
Inspect the yaml of the started  driver/executor pod and ensure that the nodeSelector is actually there.
If its missing check that the spark-operator webhook is operational. There are cases where the certificate  is `Cg==`
 (base64 of '\n')  - typically after redeploy the spark-operator multiple times (search older issues here)
