### ISSUE TITLE
gpu resource allocation, tolerations for gpu taints on the node and node affinity doesnt work

### ISSUE THREAD

**Issue by roligupt** [kubeflow/spark-operator#1381]
Below is how I have configured for driver and executor in my test and it doesnt apply any of the configurations and my test fails because driver tries to schedule on a cpu and cant find required libraries to run the job. 

I am using spark image built with cuda libraries that has all the required libraries for my test. 

Can someone help me understand why any of the gpu configurations, node affinity and tolerations dont get applied?  

driver:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - <hostname>
    cores: 1
    coreLimit: "1200m"
    memory: "1024m"
    gpu:
      name: nvidia.com/gpu   # GPU resource name
      quantity: 1           # number of GPUs to request
    labels:
      version: 3.1.1
    serviceAccount: spark-job
    env:
    - name: NUMBA_CUDA_DRIVER
      value: /usr/lib/x86_64-linux-gnu/libcuda.so
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists

  executor:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - <hostname>
    # cores: 1
    # coreLimit: "1200m"
    instances: 1
    memory: "1024m"
    labels:
      version: 3.1.1
    serviceAccount: spark-job
    gpu:
      name: nvidia.com/gpu   # GPU resource name
      quantity: 1           # number of GPUs to request
    env:
    - name: NUMBA_CUDA_DRIVER
      value: /usr/lib/x86_64-linux-gnu/libcuda.so
    tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists

**Comment by doctapp** [comment]
Same problem, can we have support for affinity on driver and executor specs?

**Comment by roligupt** [comment]
> 

oh so the affinity doesn't work either, I haven't tested that yet but I will be needing that.

**Comment by doctapp** [comment]
Sorry my bad affinity is working as expected.
