### ISSUE TITLE
Webhook not working

### ISSUE THREAD

**Issue by roligupt** [kubeflow/spark-operator#1385]
I deployed spark operator with webhook enabled. Everything started okay and I don't see any errors anywhere, but none of the functionalities that use webhook are working. 

Setting up pod affinity, tolerations, mounting volumes, configmaps, hadoopConfigMap, requesting gpu resources, none of it is working. 

Where should I look and how should i get webhook working?

I used the latest image - spark-operator:v1beta2-1.2.3-3.1.1.

I1110 19:55:10.437147       9 main.go:144] Starting the Spark Operator
I1110 19:55:10.522995       9 webhook.go:218] Starting the Spark admission webhook server
W1110 19:55:10.529402       9 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
I1110 19:55:10.530652       9 webhook.go:412] Creating a MutatingWebhookConfiguration for the Spark pod admission webhook
W1110 19:55:10.621813       9 warnings.go:67] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
I1110 19:55:10.722093       9 main.go:219] Starting application controller goroutines
I1110 19:55:10.726239       9 spark_pod_eventhandler.go:47] Pod spark-pi-custom-resource-driver added in namespace 182198-spark-job.
I1110 19:55:10.729030       9 controller.go:184] SparkApplication 182198-spark-job/spark-pi-custom-resource was added, enqueuing it for submission
I1110 19:55:10.822390       9 controller.go:165] Starting the workers of the SparkApplication controller
I1110 19:55:10.822443       9 controller.go:97] Starting the ScheduledSparkApplication controller
I1110 19:55:10.822465       9 controller.go:103] Starting the workers of the ScheduledSparkApplication controller

**Comment by gauravbh1** [comment]
What was the command you used to install the operator? This is something I opened this https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1232 sometime back and had some observation about the order of --set webhook.enable and --set image.tag in the command.
