### ISSUE TITLE
IfNotPresent with :latest

### ISSUE THREAD

**Issue by dcharbonnier** [kubeflow/spark-operator#1403]
Using IfNotPresent with `:latest` sounds like a very bad idea and this is the default.
I've seen some issue reported due to this problem.
The chart should contain the image version

**Comment by autarchprinceps** [comment]
Yeah, I have to agree. That misses the entire point of helm chart versions & upgrades.

**Comment by TomHellier** [comment]
I've just seen [my pr was merged](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1422), so the image should exist at [ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.2-3.1.1](https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator)
