### ISSUE TITLE
ClusterRole creation doesn't happen

### ISSUE THREAD

**Issue by autarchprinceps** [kubeflow/spark-operator#1407]
Even when setting rbac.createClusterRole to true, I have never seen the chart create the actual cluster role.
I don't see what the issue is myself in the helm code. That value is default true anyway, but when creating the helm chart, no ClusterRole appears for me, and the pod logs rbac erros. Maybe something to do with the helm hooks? The installation succeeded as far as helm is concerned.
I started with Chart version 1.1.0 and updated to 1.1.13, but ultimately I had to create the cluster role & binding outside of helm to workaround the rbac issues.

**Comment by jehof** [comment]
I think this relates to this PR and my comment https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1379#issuecomment-966284850.

You need to install the ClusterRole and ClusterRoleBinding by yourself, after you perfom the helm upgrade of the operator.

**Comment by cwyl02** [comment]
And I think besides `pre-install`, we would also need `pre-upgrade` in `helm.sh/hook`
