### ISSUE TITLE
[question] Source of the Spark image

### ISSUE THREAD

**Issue by kristopherkane** [kubeflow/spark-operator#1409]
Is the source Dockerfile of https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/Dockerfile#L17 available? If not, do you all know if this deviates from a standard Spark build and or the image builder in Apache Spark source?

**Comment by TomHellier** [comment]
https://kubernetes.slack.com/archives/CALBDHMTL/p1610395150193600?thread_ts=1610395150.193600&cid=CALBDHMTL

I think it is based on the spark image, but built manually
