### ISSUE TITLE
Install error for v1beta2-1.1.2-2.4.5 with flag enable-ui-service

### ISSUE THREAD

**Issue by vin4v** [kubeflow/spark-operator#1419]
#helm install my-spark-operator spark-operator/spark-operator --namespace spark-operator --create-namespace --set sparkJobNamespace=default --set operatorVersion=v1beta2-1.1.2-2.4.5 --set image.tag=v1beta2-1.1.2-2.4.5

NAME READY STATUS RESTARTS AGE
pod/my-spark-operator-5c7d7747bf-8txhs 0/1 CrashLoopBackOff 1 17s

Container crash Error:

exec /usr/bin/tini -s -- /usr/bin/spark-operator -v=2 -logtostderr -namespace=default -enable-ui-service=true -ingress-url-format= -controller-threads=10 -resync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -metrics-prefix= -enable-resource-quota-enforcement=false
flag provided but not defined: -enable-ui-service

Can you fix "-enable-ui-service" flag for this spark version "v1beta2-1.1.2-2.4.5"?

**Comment by jiangjian0920** [comment]
I have the same problem. Is there a solution？
