### ISSUE TITLE
Spark on K8 Operator failed with flag provided but not defined: 

### ISSUE THREAD

**Issue by meetraffic** [kubeflow/spark-operator#1424]
The latest image tag is failing due to the error 
```
kubectl create ns sparkjobs
kubectl create ns spark-operator
kubectl create sa spark -n sparkjobs
kubectl create clusterrolebinding spark-operator-role --clusterrole=cluster-admin  --serviceaccount=sparkjobs:spark
helm install spark-operator/spark-operator --namespace spark-operator --set sparkJobNamespace=sparkjobs --set webhook.enable=true --generate-name
```

The installation fails with 

`flag provided but not defined: -webhook-timeout .`

When we edit the deployment using

`kubectl edit deployment.apps/spark-operator-1638816042`

and removed the -webhook-timeout the spark-operator worked. 

Please fix this issues

**Comment by dcharbonnier** [comment]
duplicate #1392
