### ISSUE TITLE
hostaliases doesn't work

### ISSUE THREAD

**Issue by wanshicheng** [kubeflow/spark-operator#1432]
K8S: 1.21.5
Spark-Operator:  spark-operator-chart-1.1.14

config like that:
hostAliases:
- ip: x.x.x.x
  hostnames:
      - xxx.xxx.com

I run : kubectl exec -it xx-driver  -- cat /etc/hosts

I can't find hosts that I addad.

**Comment by hansmbakker** [comment]
I can confirm this

**Comment by sawyerwu** [comment]
pull the latest docker image works fine
docker pull ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.7-3.1.1
https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator/23862829?tag=v1beta2-1.3.7-3.1.1

**Comment by mohdmsl** [comment]
> enable the webhook and pull the latest docker image works fine https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator/23862829?tag=v1beta2-1.3.7-3.1.1

can you please tell what do you mean by enabling webhook

**Comment by sawyerwu** [comment]
> > enable the webhook and pull the latest docker image works fine https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator/23862829?tag=v1beta2-1.3.7-3.1.1
> 
> @sawyerwu can you please tell what do you mean by enabling webhook

@mohdmsl install the spark-operator by manifest/spark-operator-with-webhook-install instead of manifest/spark-operator-install
