### ISSUE TITLE
Stable/Spark-history-server - completed spark jobs url redirecting https --> http and timing out in chrome/Mozilla

### ISSUE THREAD

**Issue by mshilamk8s** [kubeflow/spark-operator#1435]
Deployed Spark-history-server
version: 1.4.3
appVersion: 2.4.0

While accessing completed jobs in spark history server UI:
Completed spark jobs url redirecting from https --> http and due to which its timing out in Chrome/Mozilla. Where as the redirect to http is not happening in Safari and able to navigate through completed spark job in Spark history server.

Any one experienced this issue and any possible solutions?

**Comment by jdonnelly-apixio** [comment]
This is probably the wrong project for this issue but... I think that might be a browser issue. If you browse to a domain with https once, some browsers will redirect all future requests to http to https. Try it in an incognito window for the browsers that don't work to confirm.
