### ISSUE TITLE
Spark application is not running after redeployment 

### ISSUE THREAD

**Issue by nirdror** [kubeflow/spark-operator#1440]
Hi, 
I have a structured streaming spark application, and I notice an issue that happens sporadically when I run a full deployment cycle (which include a deployment of the spark-operator) of my spark application in my AKS cluster: 
During the deployment the application is killed (as expected), and I can see the following log lines in the spark operator pod:

I1223 13:36:10.226485       9 event.go:282] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark-apps", Name:"rocket-spark-app", UID:"d1f9e88d-192b-478a-b3f9-73ff5ddc4d39", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"43088883", FieldPath:""}): type: 'Normal' reason: 'SparkApplicationDeleted' SparkApplication rocket-spark-app was deleted
I1223 13:36:14.745423       9 spark_pod_eventhandler.go:77] Pod rocket-notification-calculation-app-bae2557de7496ea9-exec-4 deleted in namespace spark-apps.
I1223 13:36:20.570632       9 spark_pod_eventhandler.go:77] Pod rocket-notification-calculation-app-bae2557de7496ea9-exec-3 deleted in namespace spark-apps.
I1223 13:36:21.027443       9 spark_pod_eventhandler.go:77] Pod rocket-notification-calculation-app-bae2557de7496ea9-exec-1 deleted in namespace spark-apps.
I1223 13:36:22.309946       9 spark_pod_eventhandler.go:77] Pod rocket-notification-calculation-app-bae2557de7496ea9-exec-2 deleted in namespace spark-apps.
I1223 13:36:24.478107       9 spark_pod_eventhandler.go:77] Pod rocket-spark-app-driver deleted in namespace spark-apps.
I1223 13:36:24.741365       9 spark_pod_eventhandler.go:77] Pod rocket-notification-calculation-app-bae2557de7496ea9-exec-5 deleted in namespace spark-apps.

Then, I see that my spark application has no status (via `kubectl get sparkapplication`):
```
NAME                           STATUS   ATTEMPTS   START   FINISH   AGE
rocket-spark-app                                                    71m
```

The restart policy I set for my spark application is the following: 
```
  restartPolicy:
    onFailureRetries: 2147483647
    onFailureRetryInterval: 30
    onSubmissionFailureRetries: 2147483647
    onSubmissionFailureRetryInterval: 30
    type: Always
```

Seems like the spark-operator is not aware to the fact that the app is not running, and only a restart to the spark-operator pod solves the issue for me. 

Can you please advise?

**Comment by RamakrishnaHande** [comment]
@nirdror Hey, did you find out the reason for this issue? Looks like I also have same problem
