### ISSUE TITLE
Image pullback off error installing spark-on-k8s-operator

### ISSUE THREAD

**Issue by ghost** [kubeflow/spark-operator#1442]
I tried to install the k8s operator using the 2 helm commands listed here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator

after the `helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator` command I get `"spark-operator" already exists with the same configuration, skipping`

Then `helm install my-release spark-operator/spark-operator --namespace spark-operator --create-namespace` results in 
`NAME: my-release`
`LAST DEPLOYED: Wed Dec 29 14:12:09 2021`
`NAMESPACE: spark-operator`
`STATUS: deployed`
`REVISION: 1`
`TEST SUITE: None`

When I say `kubectl get pods --namespace=spark-operator` I get the following error message about my pod. 
`NAME                                         READY   STATUS             RESTARTS   AGE`
`my-release-spark-operator-756f867bf8-6s8f8   0/1     ImagePullBackOff   0          2m52s` 

Can someone help me resolve this?

**Comment by TomHellier** [comment]
I've just seen [my pr was merged](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1422), so the image should exist at [ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.2-3.1.1](https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator)

**Comment by Nitinram23** [comment]
Oh, I think the error may be because of my mistake. I did not pull the image ahead of running helm install. Would that be a reason for this error?

**Comment by aneagoe** [comment]
@Nitinram23 no, it's not. You don't need to pull image locally before running helm, the configured deployment (via Helm) would take care about pulling the image. You just happened to run your helm deployment when the default image specified in the helm chart did not exist. It would've been sufficient for you to provide a tag and/or registry to override defaults.
