### ISSUE TITLE
Sidecar didn't terminated after the driver finished

### ISSUE THREAD

**Issue by everydots** [kubeflow/spark-operator#1443]
Hey. can anyone help to check why my sidecar container didn't terminated ( pod status is `NotReady`) after the spark job has finished. 
![image](https://user-images.githubusercontent.com/16937202/147677373-f4e2d873-834f-40fd-befc-870f9b73fd35.png)

This is my yaml configuration
![image](https://user-images.githubusercontent.com/16937202/147677437-928dc555-a465-49c0-849b-5ffa473a77ee.png)

Thanks very much

**Comment by aneagoe** [comment]
@everydots can you confirm that the sidecar was running to begin with? As well, it's helpful to report events observed in that namespace around that time.
I would recommend creating a very simple (ie `sleep 5`) sidecar to confirm that this is actually related to spark-operator in the first place.
