### ISSUE TITLE
Webhook API Version Error

### ISSUE THREAD

**Issue by reganmcdonald** [kubeflow/spark-operator#1444]
After upgrading to version v1beta2-1.3.0-3.1.1 with webhook enabled on Kubernetes 1.19, we get this error when operator starts:

main.go:209] MutatingWebhookConfiguration.admissionregistration.k8s.io "spark-operator-webhook-config" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]

**Comment by ArshiAAkhavan** [comment]
i have the same issue 
also the default version ("when you dont specify any tag") `v1beta2-1.3.1-3.1.1` seems to be missing 
can anyone guide me to any temporary patch?

i need hooks so that i can mount production environment configmaps on my spark jobs

**Comment by ArshiAAkhavan** [comment]
the isssu has been resolved and merged in to the repository

for those of you who have the same issue as me, just clone the repository and build your custom image untill the official release is made.

**Comment by sadatnfs** [comment]
@ArshiAAkhavan doesn't look like it's been merged in to master though (last commit was over a month ago). For those of us who doesn't know how to build the custom imge, do you have any guidance on this?

**Comment by aneagoe** [comment]
@sadatnfs Since then, there have been a few images released to github registry, you can see them here: https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator.

**Comment by srikanthnt** [comment]
i was able to resolve the issue by using below options while installing the helm chart:
--set image.tag=v1beta2-1.3.2-3.1.1 --set image.repository=ghcr.io/googlecloudplatform/spark-operator

**Comment by yevsh** [comment]
i just helm installed v1beta2-1.3.3-3.1.1, but i don't see webhooks created, any idea why?

**Comment by aneagoe** [comment]
@yevsh webhooks are not enabled by default (seehttps://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/e91821634deab861f56d5105b186b52749843272/charts/spark-operator-chart/values.yaml#L79), did you enable it at install time? Any logs from the operator?

**Comment by zuotingbing** [comment]
i have the same issue.
 install spark operator with webhook(kubectl apply -f spark-operator-with-webhook.yaml ) successfully with image version **v1beta2-1.2.0-3.0.0**, but upgrade to image version **v1beta2-1.3.0-3.1.1**, we get this error when operator starts:

I0209 06:13:22.008517      10 main.go:145] Starting the Spark Operator
I0209 06:13:22.009263      10 webhook.go:219] Starting the Spark admission webhook server
I0209 06:13:22.020432      10 webhook.go:415] Creating a MutatingWebhookConfiguration for the Spark pod admission webhook
F0209 06:13:22.024687      10 main.go:209] MutatingWebhookConfiguration.admissionregistration.k8s.io "spark-webhook-config" is invalid: [webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun, webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1]

**Comment by zuotingbing** [comment]
oh i see, we use the source code of spark-operator-chart-1.1.15, but  the issue has been resolved after that.

(issue: Resolves an error when deploying the webhook where the k8s api indicated that the webhook config was invalid because of missing SideEffects, and AdmissionReviewVersions (#1413))
