### ISSUE TITLE
Failed to pull image gcr.io/spark-operator/spark-operator:v1beta2-1.3.1-3.1.1

### ISSUE THREAD

**Issue by pingsutw** [kubeflow/spark-operator#1448]
Can't find the image on https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark-operator?tag=v1beta2-1.3.1-3.1.1

```bash
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  36s                default-scheduler  Successfully assigned spark-operator/my-release-spark-operator-756f867bf8-kfgb5 to 11a760adca55
  Normal   Pulling    23s (x2 over 36s)  kubelet            Pulling image "gcr.io/spark-operator/spark-operator:v1beta2-1.3.1-3.1.1"
  Warning  Failed     21s (x2 over 35s)  kubelet            Failed to pull image "gcr.io/spark-operator/spark-operator:v1beta2-1.3.1-3.1.1": rpc error: code = Unknown desc = Error response from daemon: manifest for gcr.io/spark-operator/spark-operator:v1beta2-1.3.1-3.1.1 not found: manifest unknown: Failed to fetch "v1beta2-1.3.1-3.1.1" from request "/v2/spark-operator/spark-operator/manifests/v1beta2-1.3.1-3.1.1".
  Warning  Failed     21s (x2 over 35s)  kubelet            Error: ErrImagePull
  Normal   BackOff    9s (x2 over 34s)   kubelet            Back-off pulling image "gcr.io/spark-operator/spark-operator:v1beta2-1.3.1-3.1.1"
  Warning  Failed     9s (x2 over 34s)   kubelet            Error: ImagePullBackOff
(flytekit-3.9) ➜  flyte-app git:(main) ✗ docker pull gcr.io/spark-operator/spark-operator:v1beta2-1.3.1-3.1.1                                        
Error response from daemon: manifest for gcr.io/spark-operator/spark-operator:v1beta2-1.3.1-3.1.1 not found: manifest unknown: Failed to fetch "v1beta2-1.3.1-3.1.1" from request "/v2/spark-operator/spark-operator/manifests/v1beta2-1.3.1-3.1.1".
```

**Comment by reganmcdonald** [comment]
I also saw that this image doesn't exist in the repository despite being used by chart version 1.1.15.

**Comment by Emmeral** [comment]
I had the same problem. I fixed it by specifying the the operators image tag when installing the helm chart directly using `--set image.tag=v1beta2-1.3.0-3.1.1` as a workaround.

**Comment by TomHellier** [comment]
I've just seen my pr was merged, so the image should exist at https://github.com/googlecloudplatform/spark-on-k8s-operator/pkgs/container/spark-operator

**Comment by vara-bonthu** [comment]
I have hit the similar issue while deploying the latest Helm Chart _release v1.1.15_. This chart is trying to pull the image from `gcr.io/spark-operator/spark-operator` repo however the latest images are available under `ghcr.io/googlecloudplatform/spark-operator`. 

**Fix** -  Changing the `image.repository` to `gcr.io/spark-operator/spark-operator in `values.yaml` fixed the issue for me. There is a pending PR #1454 which should fix this issue related to Helm Charts.

**Comment by sadatnfs** [comment]
> I have hit the similar issue while deploying the latest Helm Chart _release v1.1.15_. This chart is trying to pull the image from `gcr.io/spark-operator/spark-operator` repo however the latest images are available under `ghcr.io/googlecloudplatform/spark-operator`.
> 
> **Fix** Changing the Helm Chart `values.yaml` as follows fixed the issue for me `image.repository` to `ghcr.io/googlecloudplatform/spark-operator` `image.tag` to ` v1beta2-1.3.3-3.1.1`
> 
> There is a pending PR #1454 which should fix this issue related to Helm Charts.

And TIL you can do this inline upon the helm installation instead of changing `values.yaml` (thanks to #1459 )
