### ISSUE TITLE
Code for gcr.io/spark-operator/spark:v3.1.1

### ISSUE THREAD

**Issue by roligupt** [kubeflow/spark-operator#1453]
Can someone help me find the code for image - gcr.io/spark-operator/spark:v3.1.1?

**Comment by sshah90** [comment]
@roligupt [here you go](https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile)

**Comment by roligupt** [comment]
Thanks! you are pointing me to apache/spark

How do i know how really "gcr.io/spark-operator/spark:v3.1.1" image is built? I mean does it have hadoop binaries or just spark-3.1.1. your link doesnt really tell me anything.
