### ISSUE TITLE
Updating to Spark 3.2.0

### ISSUE THREAD

**Issue by jordyperlee** [kubeflow/spark-operator#1464]
We are looking to update to Scala 2.13 (and eventually Scala 3), but that requires us to update Scala to 3.2.0. Is there any plan on updating the Spark base image for the operator?

**Comment by mbaron2** [comment]
Hello,

Any update of this subject ?

**Comment by afranzi** [comment]
We would be interested also in updating to 3.2.X

**Comment by josecsotomorales** [comment]
Hey Team, any plans to release an operator version that officially supports 3.2? I checked that it actually works with a custom image of spark 3.2 and the latest operator image (3.1.1), but did not deeply tested.

**Comment by Felix-neko** [comment]
Hi folks! Can you please offifially support Spark 3.2.0?

**Comment by leandro-rouberte** [comment]
+1

**Comment by sharonorman78** [comment]
Hi

any news regarding this issue?

many Q's here - can you estimate when will it be supported?
thanks :)

**Comment by allenhaozi** [comment]
I built an image based on spark-3.2.1-bin-hadoop3.2
Is that a problem?

**Comment by mbaron2** [comment]
@allenhaozi your image works ? Can you share it ?

**Comment by allenhaozi** [comment]
@mbaron2 

I am currently in the test environment and can work
Because it's still in beta, I can email you if you want, okay?

The main reference is the following items:
+ [spark-docker-file](https://github.com/apache/spark/blob/master/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/Dockerfile)
+ [pyspark-docker-file](https://github.com/jupyter/docker-stacks/tree/master/pyspark-notebook)
+ [spark-operator-docker-file](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master/spark-docker)

**Comment by sergialonsaco** [comment]
Is there any new regarding this update to 3.2.0 officially?

**Comment by wolliq** [comment]
Hi @vburenin I built a Spark 3.2.1 image which works fine but in some cases the Spark application shows this trace

`22/08/18 11:14:17 WARN WatcherWebSocketListener: Exec Failure
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
22/08/18 11:14:18 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed (this is expected if the application is shutting down.)
io.fabric8.kubernetes.client.WatcherException: too old resource version: 12998019 (13034876)`

and hangs for hours without failing.

Could this be somehow related to the image version?
Thx

**Comment by rahulbhatia2702** [comment]
> Spark 3.3.0 was released, I have a custom image of 3.2.1 running with the operator without any issues, and will experiment with 3.3.0 this week.

Hi @josecsotomorales can you share the dockerfile for this?

**Comment by sousaaguilherme** [comment]
I would also be interested in this!

**Comment by allenhaozi** [comment]
I built it myself for testing
`allenhaozi/base-pyspark-3.2.1-py-v3.8`

**Comment by vburenin** [comment]
if anybody curious, it all works just fine if your target execution image is spark 3.3.

**Comment by josecsotomorales** [comment]
I'm actually using the operator with spark 3.3 with a custom image, see this issue: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1559
