### ISSUE TITLE
Launch multiple SparkApplications at same time error.

### ISSUE THREAD

**Issue by carlosliarte** [kubeflow/spark-operator#1466]
Hi,

I try to launch 2 SparkApplications at the same time with the yaml of the guide to execute spark-pi.
Both applications have the same configuration on the yaml but I change the name of applications.

I can see the Sparkapplications were added and enqueuing it for submission but on the next step both applications failed with the error SparkApplicationSubmissionFailed and show the following message:

`failed to submit SparkApplication foo: failed to run spark-submit for SparkApplication fargate/foo: WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int) WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release 22/01/26 16:46:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties 22/01/26 16:46:37 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file 22/01/26 16:47:02 INFO KerberosConfDriverFeatureStep: You have not specified a krb5.conf file locally or via a ConfigMap. Make sure that you have the krb5.conf locally on the driver image.` 

Context: Spark operator was installed on AWS EKS with Fargate.

The idea is to execute spark applications with the same jar, different arguments and app name at the same time on the same cluster.

Yaml used:

Yaml example
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml

**Comment by jdonnelly-apixio** [comment]
Are you trying to use the same spark app name for both? Those have to be unique.

**Comment by carlosliarte** [comment]
No with different name.

**Comment by phyyou** [comment]
@carlosliarte It is computing resource problem. You need upgrade cpu & memory spec in manifest of spark on k8s operator deployment. default spark on k8s operator can't submit 2 application at same time

**Comment by tamis-laan** [comment]
We have the same problem forcing us to manually apply each pipeline which is a chore!!

Is there an easier way to deal with this????
