### ISSUE TITLE
"jarsDownloadDir" looks to be not implemented

### ISSUE THREAD

**Issue by manju369** [kubeflow/spark-operator#1469]
In documentation it is said that dependency jars can be downloaded to specific path - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#specifying-application-dependencies

but whenver I try to create spark application with this option  `.spec.deps.jarsDownloadDir` , sparkapplication creation fails with message   "  **unknown field "jarsDownloadDir"** "

> error: error validating "examples/spark-pi.yaml": error validating data: ValidationError(SparkApplication.spec.deps): unknown field "jarsDownloadDir" in io.k8s.sparkoperator.v1beta2.SparkApplication.spec.deps; if you choose to ignore these errors, turn validation off with --validate=false

My spark-application yaml file 
```  apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "manju369/spark-3.2.0-bin-hadoop3.2:4"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.2.0.jar"
  sparkVersion: "3.2.0"
  deps:
    jars:
    - https://repo1.maven.org/maven2/com/google/cloud/bigdataoss/gcs-connector/hadoop3-2.2.4/gcs-connector-hadoop3-2.2.4-shaded.jar
    jarsDownloadDir:
    - /opt/spark/jars/
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "file:/tmp/"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
    prometheus:
      jmxExporterJar: "/opt/spark/jars/jmx_prometheus_javaagent-0.11.0.jar"

**Comment by guptap11** [comment]
Looks like it got deprecated in v1beta2 api 

**v1beta2**
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L412

**v1beta1**
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta1/types.go#L319

**Comment by tardunge** [comment]
looks like this is based on spark's kubernetes properties `spark.kubernetes.mountDependencies.jarsDownloadDir` which is no longer valid.
One approach would be to use the init containers.
