### ISSUE TITLE
Grafana dashboard for spark metrics

### ISSUE THREAD

**Issue by vaibhavk-cldcvr** [kubeflow/spark-operator#1496]
Hi Folks,

Does someone have a working grafana dashboard for spark operator metrics? Please share.

Thanks.

**Comment by vaibhavk-cldcvr** [comment]
@miande-acxiom This dashboard did not work out of the box. This dashboard tries to find some metrics whose names are changed or removed. You will have to edit the widgets and replace metric names with correct names. Metric names have slight changes, you will be able to get those.

**Comment by thanhnet** [comment]
anyone have dashboard for grafana?
