### ISSUE TITLE
aws libraries compatible with spark operator 3.1.1

### ISSUE THREAD

**Issue by scaladevspark** [kubeflow/spark-operator#1501]
Hi, I have a spark operator with sparkVersion: "3.1.1" and would like to use it for structured streaming to/from minIO. However, I have not been able to find a compatible combination of libraries for anything newer than hadoop 2.7.0.

Is there a compatible set of spark/hadoop/aws libraries for the 3.1.1 version of spark operator?

my current dependencies in sbt should work based on maven dependencies, but they dont (NoSuchMethodError):

scalaVersion := "2.12.0"

lazy val Versions = new {
  val spark = "3.1.1"
  val hadoop = "3.2.0"
}

  "org.apache.spark" %% "spark-core" % Versions.spark % Provided
, "org.apache.spark" %% "spark-sql" % Versions.spark % Provided
, "org.apache.spark" %% "spark-hive" % Versions.spark % Provided
, "org.apache.hadoop" % "hadoop-aws" % Versions.hadoop
, "org.apache.hadoop" % "hadoop-common" % Versions.hadoop
, "org.apache.hadoop" % "hadoop-mapreduce-client-core" % Versions.hadoop
, "org.apache.hadoop" % "hadoop-client" %  Versions.hadoop
, "com.amazonaws" % "aws-java-sdk-bundle" % "1.11.375"

thanks a lot for any help

**Comment by antosha417** [comment]
hi @scaladevspark, which image do using?
Try to use one from this issue:
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1334

**Comment by antosha417** [comment]
@scaladevspark, I think the only reason is for you and me to suffer))
Glad that I could help

**Comment by sebady** [comment]
We've been dealing with this "issue" too. It's not at all clear that an image named `gcr.io/spark-operator/spark:v3.1.1` would be using Spark 3 with Hadoop 2.7.x libraries.  Ideally the image gcr.io/spark-operator/spark:v3.1.1 should really be named `gcr.io/spark-operator/spark:v3.1.1-hadoop-2.7.4` or something similar.
