### ISSUE TITLE
node affinity doesnt work

### ISSUE THREAD

**Issue by ghost** [kubeflow/spark-operator#1519]
This functional requirement is very important. For example, if there are CPU machines and GPU machines in the node, node scheduling must be required！！

![企业微信截图_20220427134954](https://user-images.githubusercontent.com/13087771/165451069-e2d996ee-5e1a-48fa-aae8-243713d95710.png)

**Comment by oscar-dela** [comment]
In my previous experience, that may be caused by mutating-admission-webhook missing.

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#about-the-mutating-admission-webhook

**Comment by josecsotomorales** [comment]
I use `nodeSelector` and it works for me, in case you want to give it a try.

**Comment by elihschiff** [comment]
I had the same issue and was able to get it working using a pod template file without the need to enable the webhook https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1176#issuecomment-1179287656

**Comment by yangqi766** [comment]
> 

can you gibr a example of the pod template  ?

**Comment by yangqi766** [comment]
> I had the same issue and was able to get it working using a pod template file without the need to enable the webhook [#1176 (comment)](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1176#issuecomment-1179287656)

can you gibr a example of the pod template ?

**Comment by elihschiff** [comment]
My pod template has a lot of custom settings for my infrastructure. However, any valid pod yaml file should work. The spark/k8s docs have more details https://spark.apache.org/docs/latest/running-on-kubernetes.html#pod-template https://docs.aws.amazon.com/emr/latest/EMR-on-EKS-DevelopmentGuide/pod-templates.html

**Comment by archongum** [comment]
`--conf spark.kubernetes.node.selector.kubernetes.io/hostname=sz-exa-cpu-10` works for me.

Ref: https://spark.apache.org/docs/latest/running-on-kubernetes.html
