### ISSUE TITLE
OpenJDK Vulnerability in spark images

### ISSUE THREAD

**Issue by vitas** [kubeflow/spark-operator#1522]
https://openjdk.java.net/groups/vulnerability/advisories/2022-04-19

for example docker image 
ghcr.io/googlecloudplatform/spark-operator:3.1.1
uses openjdk 11.0.10 , 
it has to be updated to 11.0.15

**Comment by josecsotomorales** [comment]
Not ideal but you can also build your custom Spark image and use it in the meantime.
