### ISSUE TITLE
No Option to Retrigger/Restart Completed Spark Job

### ISSUE THREAD

**Issue by jaiganesh8** [kubeflow/spark-operator#1529]
Hi, 

I have a use case were we have a set of Spark Batch Applications with a Scheduled Interval, I was able to schedule the batch application by using the kind  "ScheduledSparkApplication". 

But for my Regression Test cases we need to trigger the existing deployed Spark Applications in ad-hoc fashion, as of now I don't see any way to trigger the job again, unless I delete and create the yaml there is no way to retrigger the applications. 

Please help me is there any way which i missing out ?

Thanks & Regards,
Jai

**Comment by success-m** [comment]
@jaiganesh8 - We were able to reboot the sparkapplication by simply changing the config like so.

`kubectl patch sparkapp spark-application-name --type='merge' -p '{"spec":{"dynamicAllocation":{"maxExecutors": 2}}}'`

Hope this helps.
