### ISSUE TITLE
Driver and executor Pods will still be created after spark application has been deleted

### ISSUE THREAD

**Issue by dreamtalen** [kubeflow/spark-operator#1558]
Hi all,

We notice that if a `sparkapplication` is deleted immediately after creation, the driver/executor pods of this `sparkapplication` will still be created and keep running until completed.

To reproduce, we could use `sparkctl` with following commands:
```
> ./sparkctl create ../examples/spark-py-pi.yaml
SparkApplication "pyspark-pi" created
```
After creation, do the deletion immediately with:
```
> ./sparkctl delete pyspark-pi
SparkApplication "pyspark-pi" deleted
```
Although it shows the SparkApplication "pyspark-pi" is deleted, if we check the Pods with `kubectl` we could see that driver Pod is created and running:
```
> kubectl get pods -o wide
pyspark-pi-driver        1/1     Running
```

We would like to confirm with you whether this is expected behavior and do we have approaches to avoid this corner case?
Thanks!

**Comment by mgyboom** [comment]
I also ran into this problem when deleting a running sparkapplicaiton.
waiting for a solution.

**Comment by mgyboom** [comment]
@liyinan926
