### ISSUE TITLE
Executor Pods keep getting removed considering non-existent.

### ISSUE THREAD

**Issue by dp2608** [kubeflow/spark-operator#1560]
Hi I am relatively new to spark and I am trying to implement it on on-prem infrastructure. The spark job gets submitted succesfully but runs only with the driver pod. The executor pods keep getting removed from the cluster. I am not able to monitor the executor logs as well. The driver pod logs show something like below. Earlier I assumed it to be an issue of RBAC but that is also configured with edit, create, watch, list permissions for pods and configmaps.

```
22/06/28 05:31:15 INFO BlockManagerMaster: Removal of executor 3 requested
22/06/28 05:31:15 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Asked to remove non-existent executor 3
22/06/28 05:31:15 INFO BlockManagerMasterEndpoint: Trying to remove executor 3 from BlockManagerMaster.
```

![image](https://user-images.githubusercontent.com/28335305/176104637-f4d86e17-9172-4588-b1ac-8b72ac34155e.png)

**Comment by tahesse** [comment]
@dp2608 Please don't post images of logs but text. What is your setup that led to this situation? Configuration? Did you make sure that there are enough resources?

**Comment by MahadevanHari** [comment]
@dp2608 Hi, were you able to resolve this issue?

**Comment by sendvinh** [comment]
@dp2608 are u able to resolve this yet?

**Comment by sendvinh** [comment]
@tahesse I see u also have some comment on https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1562, do u have any idea on this current issue?

**Comment by tahesse** [comment]
@sendvinh I have no clue because there is no relevant information in this thread which could enable me to help.
FYI this repository looks rather unmaintained.
