### ISSUE TITLE
HELP: How to generate Java crd codes?

### ISSUE THREAD

**Issue by shanhai3000** [kubeflow/spark-operator#1563]
How to generate Java crd codes using https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml ?

I tried everything, all failed.

**Comment by dcoliversun** [comment]
https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md
Maybe it can help you :)
