### ISSUE TITLE
Readiness/liveness probes for spark-operator pod 

### ISSUE THREAD

**Issue by GajaHebbar** [kubeflow/spark-operator#1592]
is there any readiness/liveness probes for the spark-operator itself. we are using the spark-operator for driver and executor pod recovery in case of failure.

as part of the organization policy we need to add readiness/liveness probes for all pods, driver and executor will be monitored by operator, but I would like to know if there is any readiness/liveness probes there for spark-operator pod itself?

**Comment by pofl** [comment]
+1 we also have an organization policy that requires at the bare minimum a readiness probe. Any chance simple, stupid probes could be added to the operator?

**Comment by monotek** [comment]
added a pr for configurable probes in the helm chart: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/pull/1628
