### ISSUE TITLE
Docker user is root

### ISSUE THREAD

**Issue by hajapy** [kubeflow/spark-operator#1601]
In the spark-operator dockerfile, the user is intended to be switched, but spark_uid is not defined. See:

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/244033925a235f6f1c9f0c597e378960794857e5/spark-docker/Dockerfile#L38

The end result is that the user is still root:
```
❯ docker run --rm -it --entrypoint="" gcr.io/spark-operator/spark-operator:v1beta2-1.3.0-3.1.1 /bin/bash
root@ff2aa907910b:/opt/spark/work-dir# id
uid=0(root) gid=0(root) groups=0(root)
```

**Comment by jiangjian0920** [comment]
Is there any way to change the users in the Spark image？

**Comment by julienlau** [comment]
Yes, we can run the sparkpp using non root as you described @AlexNavara .
The question was about the sparkoperator container.
It runs as root and cannot run as non-root so easily due to the manual procedure used in the image to generate certificate on the fly.

**Comment by julienlau** [comment]
The problem is this hack that needs root permissions : 
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/5f2efd4ff97e7c0bfdb726a066118d3401576730/hack/gencerts.sh
