### ISSUE TITLE
Trigger the next scheduled spark application ahead of time

### ISSUE THREAD

**Issue by joseparajelesGL** [kubeflow/spark-operator#1606]
Currently the ScheduledSparkApplication creates a next run on the next window of the cron configuration, could it be possible to have an annotation that tells the controller to trigger a new run?  This will be particularly useful when testing application with long cron schedules.

**Comment by yliu224** [comment]
@joseparajelesGL Did you find any temporary solution for this one?

**Comment by joseparajelesGL** [comment]
> @joseparajelesGL Did you find any temporary solution for this one?

I had to do a patch to the status subresource. You will need an [updated version](https://stackoverflow.com/questions/73363796/kubectl-patch-doesnt-update-status-subresource) of kubectl (1.24+) or a client that can update status

I used this patch
```
kubectl patch --subresource status -n $NAMESPACE  ScheduledSparkApplication $SCHEDULED_SPARK_APPLICATION --type json -p '[{"op":"replace", "path":"/status/nextRun", "value":"2023-01-01T00:00:00Z"}]'
```
That will make the system run it next. If you want an specific time feel free to change it to the proper time
