### ISSUE TITLE
Is there a new image for spark-py:3.2.2 ?

### ISSUE THREAD

**Issue by amir1m** [kubeflow/spark-operator#1639]
Hello,
Can you please point us to the **spark-py:3.2.2** ? Alternatively, if there are instructions to create one would be appreciated.
Also, tried using building Docker images from spark's source code "kubernetes" folder to use with Spark-Operator however it fails with following message after deploying the Spark App:
```
Non-spark-on-k8s command provided, proceeding in pass-through mode...
tini (tini version 0.19.0 - git.de40ad0)
Usage: tini [OPTIONS] PROGRAM -- [ARGS] | --version

Execute a program under the supervision of a valid init process (tini)
```

**Comment by allenhaozi** [comment]
I built it myself for testing
`allenhaozi/base-pyspark-3.2.1-py-v3.8:v0.2.0`

**Comment by josecsotomorales** [comment]
I'm using a custom spark 3.3 image, see this issue: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1559

**Comment by amir1m** [comment]
Thanks @allenhaozi and @josecsotomorales for your reply! 

I am also able to build Spark-operator docker image and deploy it. The issue is with the Application Docker image that is used to packages the app code. 

I am not using Debian based image but Oracle Linux and would like to deploy the app using this OS. Individually/standalone app runs well on it but when I deploy it on K8S it doesn't seems to spawn the Executor.Also, I don't see $SPARK_HOME/conf/spark.properties (ConfigMap?) file generated with custom Oracle Linux image. What is special done with GCR image/base OS that I am missing for my Linux distro?

**Comment by rahulbhatia2702** [comment]
> allenhaozi/base-pyspark-3.2.1-py-v3.8:v0.1.0

Can you share the dockerfile for this?

**Comment by josecsotomorales** [comment]
@rahulbhatia2702 I posted an example dockerfile for 3.3 here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1559

**Comment by allenhaozi** [comment]
>> allenhaozi/base-pyspark-3.2.1-py-v3.8:v0.1.0
> 
> Can you share the dockerfile for this?
hi @rahulbhatia2702 I have uploaded a copy for your reference. Some modifications are needed, such as docker registry
[docker-stacks](https://github.com/allenhaozi/exquisite-mlops-production/tree/master/docker-stacks)
