### ISSUE TITLE
SparkOperator backward compatibility with Spark

### ISSUE THREAD

**Issue by jinojohn92** [kubeflow/spark-operator#1648]
Hello, 

We have installed spark-operator with version v1beta2-1.3.3-3.1.1, our Spark application is running with version 2.4.6.
When tested the jobs does run, but I would like to know if its officially supported.

As per the readme, we could use --set image.tag to set the image for our base spark image, but unfortunately I couldn't find any container images in the repository with below 3.1.1, so the helm install fails.

Also in the overview of readme it mentions 'supports Spark 2.3 and up' does that mean even if latest operator is installed with 3.1.1 the old spark will be supported.

Thank you in advance.

**Comment by bertjanssens93** [comment]
We are having the same issue with using the --set image.tag to an older spark version.
