### ISSUE TITLE
how spark operator will assign executor on new node

### ISSUE THREAD

**Issue by anilnokia** [kubeflow/spark-operator#1651]
Hi,

If I have n nodes in my cluster and spark-operator is installed, it knows how to start executor on all n nodes. Now let's say if I add a new node to kubernetes, how does sparkoperator knows to start executor on new node? Do I have to update any config file? 

Thanks,

Anil

**Comment by shahin43** [comment]
@anilnokia its taken case by k8 cluster manager. Its always recommended to use node labels in your k8 cluster and with spark operator you can define `nodeSelector` for assigning executor/ driver pods on nodes. 
Also with spark dynamic allocation enabled which is by default in > spark 3.0, spark will manage required executor pods in the cluster for your application
