### ISSUE TITLE
driver initContainers  Not effective ，How do you use it?

### ISSUE THREAD

**Issue by lizu18xz** [kubeflow/spark-operator#1654]
driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
    initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

 kubectl describe -f spark-pi2.yaml
Events:
  Type    Reason                     Age                From            Message
  ----    ------                     ----               ----            -------
  Normal  SparkApplicationAdded      75s                spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
  Normal  SparkApplicationSubmitted  72s                spark-operator  SparkApplication spark-pi was submitted successfully
  Normal  SparkDriverRunning         69s                spark-operator  Driver spark-pi-driver is running
  Normal  SparkExecutorPending       60s                spark-operator  Executor [spark-pi-c5f82c84f6015f45-exec-1] is pending
  Normal  SparkExecutorRunning       59s                spark-operator  Executor [spark-pi-c5f82c84f6015f45-exec-1] is running
  Normal  SparkDriverCompleted       54s (x2 over 54s)  spark-operator  Driver spark-pi-driver completed
  Normal  SparkExecutorCompleted     54s                spark-operator  Executor [spark-pi-c5f82c84f6015f45-exec-1] completed
  Normal  SparkApplicationCompleted  53s                spark-operator  SparkApplication spark-pi completed

**Comment by Liftingthedata** [comment]
I recently tried a gitsync init container and it was not being recognized either.

**Comment by rangnar14** [comment]
We are also trying to use initContainer. But Looks like its not being recognized. webhook was enabled as mentioned in the docs. We are using the helm charts 1.1.26 releae.

**Comment by sam-som** [comment]
I was seeing a similar issue with our sparkapplication where the `initContainers` were defined in the yaml file but was not getting created in the pod.
For us, the root cause was the `webhook` not being enabled on that particular cluster. 

You can check to see if the `webhook` is working by checking the log of `spark-operator`
The `spark-operator` should frequently be logging `webhook.go:247] Serving admission request`

**Comment by yougyoung94** [comment]
Same issue here

Using spark-operator chart `1.1.27`

With `webhook.enable=true` set, the spark-operator pod gives only the following logs
```
0530 01:40:21.154915      10 webhook.go:219] Starting the Spark admission webhook server
I0530 01:40:21.158751      10 webhook.go:424] Creating a MutatingWebhookConfiguration for the Spark pod admission webhook
```
No sign of `webhook.go:247] Serving admission request` :(

And the pod created by SparkApplication shows no sign of `initContainer`

**Comment by rahulbhatia2702** [comment]
was anyone able to get this working?

**Comment by ChengJie1053** [comment]
@lizu18xz Hello, was the problem solved later

**Comment by karanalang** [comment]
i'm having the same issue .. initContainer is not being recognized .. how to fix this ?
