### ISSUE TITLE
Spark executor failing with a weird error

### ISSUE THREAD

**Issue by ben5556** [kubeflow/spark-operator#1658]
We are noticing intermittent issues where spark driver and executor pods are failing. We are observing the below error in spark operator logs

`I1221 05:43:21.925839       9 event.go:282] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark-operator", Name:"spark-stream", UID:"704c4b19-d6e8-4e6f-970d-d0ad5d1f9ed4", APIVersion:"sparkoperator.k8s.io/v1beta2", ResourceVersion:"1166660949", FieldPath:""}): type: 'Warning' reason: 'SparkExecutorFailed' Executor [spark-stream-3394cd8533264232-exec-3 %!s(int32=1) Error] failed with ExitCode: %!d(MISSING), Reason: %!s(MISSING)`

**Comment by PavloChechehov** [comment]
Does anybody know something about this strange message?

**Comment by Neerols** [comment]
I also get the same error on some tasks. I have not found a solution yet
