### ISSUE TITLE
spark operator webhook issue

### ISSUE THREAD

**Issue by panyamravi** [kubeflow/spark-operator#1666]
Hi, we are using latest spark-operator and its a microk8s cluster. We are seeing the below error:
webhook: Post "https://spark-operator-webhook.spark-operator.svc:443/webhook?timeout=30s": Service Unavailable
Jan 10 10:38:27 kubenode01 microk8s.daemon-kubelite[2474203]: I0110 10:38:27.582163 2474203 alloc.go:327] "allocated clusterIPs" service="spark-operator/spark-operator-webhook" clusterIPs=map[IPv4:10.152.183.236]
Jan 10 11:12:03 kubenode01 microk8s.daemon-kubelite[2474203]: W0110 11:12:03.658397 2474203 dispatcher.go:180] Failed calling webhook, failing open webhook.sparkoperator.k8s.io: failed calling webhook "webhook.sparkoperator.k8s.io": failed to call webhook: Post "https://spark-operator-webhook.spark-operator.svc:443/webhook?timeout=30s": Service Unavailable
Jan 10 11:12:03 kubenode01 microk8s.daemon-kubelite[2474203]: E0110 11:12:03.658433 2474203 dispatcher.go:184] failed calling webhook "webhook.sparkoperator.k8s.io": failed to call webhook: Post "https://spark-operator-webhook.spark-operator.svc:443/webhook?timeout=30s": Service Unavailable

and due to which the config maps are not getting attached to driver. any help on this please.

**Comment by shahsiddharth08** [comment]
how are you installing `spark-operator`?
