### ISSUE TITLE
Why the least result size sent to sender is 10952?

### ISSUE THREAD

**Issue by dongyunpeng-sjtu** [kubeflow/spark-operator#1687]
I run a spark-on-k8s-operator with remote shuffle service.
but some tasks'  shuffle read size is 0B
but after  Finishing  this kind of task. 10952 bytes result sent to driver
Is there any data?

**Comment by 1511351836** [comment]
![image](https://user-images.githubusercontent.com/34052270/224604203-a1a23ef9-6fc4-4617-b708-a84a57ddd076.png)

**Comment by 1511351836** [comment]
![image](https://user-images.githubusercontent.com/34052270/224605025-116b7152-f981-41df-adc1-d01638b63d84.png)

I wonder if TID 950 has not read the data, or if it has read the data by means of process_locality, but only a small part

**Comment by 1511351836** [comment]
![image](https://user-images.githubusercontent.com/34052270/224605306-ff0771d0-5bc2-4d3a-91e4-62ec36608632.png)
