### ISSUE TITLE
Example using spark-submit

### ISSUE THREAD

**Issue by miande-acxiom** [kubeflow/spark-operator#1689]
When working with the spark-operator we have gotten extremely comfortable building Kubernete deployments for the 'SparkAppliclation'.  However, we have a need to natively (remotely from internal of the Kubernetes cluster) to use "spark-submit".  

Are there any examples of using spark-submit (remotely of the K8 cluster) that leverage the spark-operator?  Do these examples breakdown any new/additional configurations that are needed on the spark-operator?  We have looked online and through the issues here, but have not found the information needed to support this requirement.

**Comment by miande-acxiom** [comment]
Thank you for stating the facts and let me please let me clarify my question.  

While using the spark-operator in the k8 cluster, is there a way for me (outside the K8 cluster) to invoke native spark-submit like:

`./bin/spark-submit --master k8s://http[s]://[hostname]/[uri]:[PORT] --deploy-mode cluster...`

Does the spark-operator expose (web-hook/etc.) the capability for invoking spark on a K8 cluster?

Thank you for your feedback.

**Comment by AlexNavara** [comment]
Yes, you still can use native 'spark-submit' to run spark workloads on k8s cluster, but in this case, spark-operator will not be involved.
I'm a bit confused by your second question... Actually, this is what the operator does: it takes your spark application in form of a SparkApplication custom resource, converts it to a 'spark-submit' command, and executes it. 
Are you asking if you can use the native spark-submit script to submit apps to the spark operator? Then the answer is no. 'spark-submit' will not create a SparkApplication object for you. The operator doesn't expose any endpoints/webhook for imperative spark submission. If you use the operator - your interface is K8S API server, and you interact with the operator only through it by creating/removing/retrieving SparkApplication objects.

**Comment by miande-acxiom** [comment]
I understand the spark-operator uses the CRD of SparkApplication to convert into a 'spark-submit' command and executes it.  I wasn't sure if there was an additional way the spark-operator could be used using 'spark-submit' remotely of the K8 cluster.  I understand now the spark-operator only supports the CRD of SparkApplication objects and not (additionally) directly with spark-submit.

Thank you for clearly separating those use cases for me.
