### ISSUE TITLE
Error webhook-init job "problems making Certificate Request"

### ISSUE THREAD

**Issue by cinesia** [kubeflow/spark-operator#1705]
I noticed an error in the webhook-init job during the installation of the Spark Operator (using Helm). 

The error is relative to the script in _/usr/bin/gencert.sh_ , which is run at the startup of the webhook. If the parameter **-s** is longer than **63 characters**, the script raise an error and the installation stay pending due to an successful job completion.

```
problems making Certificate Request
274909679360:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:../crypto/asn1/a_mbstr.c:107:maxsize=64
```

The line of the script raising the error is the following:
`openssl req -x509 -new -nodes -key ${TMP_DIR}/ca-key.pem -days 100000 -out ${TMP_DIR}/ca-cert.pem -subj "/CN=${SERVICE}.${NAMESPACE}.svc"`
And should be related to this issue https://github.com/certbot/certbot/issues/1915. 

The problem is that /CN can accept at most 64 chars and in the script is not considered that the final string is also composed by the namespaces, the dots and the suffice _.svc._ There should be a sort of truncation to 64 chars at the very start of the script.

**Comment by JonRossEventus** [comment]
related - https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1739
