### ISSUE TITLE
Need custom spark image dockerfile

### ISSUE THREAD

**Issue by kraj007** [kubeflow/spark-operator#1727]
I am looking for custom spark docker image , which runs perfectly on spark-on-k8s-operator.
I found few dockerfile but all have some problems. Can anybody here please help on this

**Comment by JTBS** [comment]
@kraj007  You can change docker image in helm install for Spark operator: https://googlecloudplatform.github.io/spark-on-k8s-operator/#version-matrix

However you really don't have to use Spark Image installed with Spark Operator to build your Spark applications. I have been using latest Binami Spark images for building Spark Applications - that are managed through Spark Operator.
