### ISSUE TITLE
Spark base image used by Spark Operator has security issue

### ISSUE THREAD

**Issue by JTBS** [kubeflow/spark-operator#1730]
Hi,
Although we use Spark Applications with latest Spark docker image from Bitnami that has all security fixes, our deployment still needs "Spark Operator" itself - which is installed through helm chart.

Currently there is no easy way to override specific Spark Image inside this Spark Operator Install?
Is there a reason why we need to ship Spark Operator Docker Image with Base Spark version?

Either removing Spark Base version OR allowing some way to use Spark version of our choice might help?

Only option I have is otherwise: To rebuild Spark-Operator with whatever base image of Spark we use - to avoid getting security alerts.

Any thoughts?

**Comment by AlexNavara** [comment]
Hi,
Spark-operator image must be built on top of spark image. Actually, it requires a spark distribution to be present: operator calls 'spark-submit' script to run applications. So you can't remove spark, but the second option should work: just put the image you want in the dockerfile: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/Dockerfile#L17, and rebuild spark-operator.
