### ISSUE TITLE
describe spark application does not give complete error message

### ISSUE THREAD

**Issue by kraj007** [kubeflow/spark-operator#1732]
My spark application is not starting the pods and does not give complete message while describing.

Below is the output of describe spark application. Below spark status does not give any hint about actual issue.
**Also Its not spinning up driver pod at all**.  The same manifest file applied on another cluster works fine 
Can anybody please help out here 

Status:
  Application State:
    Error Message:  failed to run spark-submit for SparkApplication spark-jobs/sample-job: WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
23/04/21 09:40:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
23/04/21 09:40:55 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file

    State:  FAILED
  Driver Info:
  Last Submission Attempt Time:  2023-04-21T09:41:06Z
  Submission Attempts:           1
  Termination Time:              <nil>
Events:
  Type     Reason                            Age    From            Message
  ----     ------                            ----   ----            -------
  Normal   SparkApplicationAdded             2m34s  spark-operator  SparkApplication sample-job was added, enqueuing it for submission
  Warning  SparkApplicationSubmissionFailed  109s   spark-operator  failed to submit SparkApplication sample-job: failed to run spark-submit for SparkApplication spark-jobs/sample-job: WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
23/04/21 09:40:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
23/04/21 09:40:55 INFO SparkKubernetesClientFactory: Auto-configuring K8S client using current context from users K8S config file
  Warning  SparkApplicationFailed  109s  spark-operator  SparkApplication sample-job failed: failed to run spark-submit for SparkApplication spark-jobs/sample-job: WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/opt/spark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
23/04/21 09:40:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties

**Comment by jalkjaer** [comment]
Try to look at the operator pod logs while submitting the application.

Also the above doesn't look anything like describe output of a SparkApplication resource - seems interleaved with logs.
Also when pasting terminal output, you should mark it as a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to  keep the "formatting"
