### ISSUE TITLE
PR_SET_CHILD_SUBREAPER is unavailable on this platform

### ISSUE THREAD

**Issue by hongbo-miao** [kubeflow/spark-operator#1735]
I have a local k3s Kubernetes created by [Rancher Desktop](https://rancherdesktop.io/) on MacBook Pro with M1 chip.

I try to install spark-on-k8s-operator by

```sh
helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
helm install spark spark-operator/spark-operator --namespace spark-operator --create-namespace
```

However, I got the error for the pod `spark-spark-operator-6964986646-5vctk`:

```sh
++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/bash
+ set -e
+ echo 0
+ echo 0
+ echo root:x:0:0:root:/root:/bin/bash
0
0
root:x:0:0:root:/root:/bin/bash
+ [[ -z root:x:0:0:root:/root:/bin/bash ]]
+ exec /usr/bin/tini -s -- /usr/bin/spark-operator -v=2 -logtostderr -namespace= -enable-ui-service=true -ingress-url-format= -controller-threads=10 -resync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -metrics-prefix= -enable-resource-quota-enforcement=false
[FATAL tini (1)] PR_SET_CHILD_SUBREAPER is unavailable on this platform. Are you using Linux >= 3.4?
```

Any idea? Thanks! 😃

**Comment by sshahar1** [comment]
I'm having the same issue on [colima](https://github.com/abiosoft/colima)

**Comment by nielspardon** [comment]
This comment explains the root cause of the issue: https://github.com/docker/for-mac/issues/6620#issuecomment-1694380189

It seems that this is triggered by the Spark container image using `tini -s` in the `entrypoint.sh` script, e.g. for 3.5.0:
https://github.com/apache/spark-docker/blob/master/3.5.0/scala2.12-java11-ubuntu/entrypoint.sh

**Comment by flowy0** [comment]
If you use `colima` with rosetta emulation or with an amd profile, it should resolve. I previously had this error. See details at [Rosetta 2 emulation](https://github.com/abiosoft/colima#customizing-the-vm) 

```
#AMD profile
colima start --profile amd --arch amd --cpu 4 --memory 8 --disk 80

# or rosetta emulation
colima start --arch aarch64 --vm-type=vz --vz-rosetta --cpu 4 --memory 8 --disk 80
```

**Comment by stefanbethke** [comment]
/reopen I believe this is still an issue. ghcr.io/googlecloudplatform/spark-operator:v1beta2-1.3.8-3.1.1 is available only as an amd64 image, necessitating emulation on non-amd64 systems. And it seems QEMU 7.4 does not properly emulate a system call or similar.

Is there any reason the project does not publish arm64 images?
