### ISSUE TITLE
ErrImagePull/ImagePullBackOff status of spark driver pod is not surfaced to SparkApplication status

### ISSUE THREAD

**Issue by Prad94r** [kubeflow/spark-operator#1737]
When we create a SparkApplication and specify an image that does not exist or if the driver pod is unable to pull the image for some other reason like using a private repository without specifying pull secrets, the driver pod enters ErrImagePull state and eventually gets stuck in ImagePullBackoff state. This status however is not updated in the SparkApplication status which remains in SUBMITTED state. 

The problem with the above is that we have a service that creates SparkApplication objects and then checks the status of that object to know if a job has failed or not. If the image provided is not pullable then the SparkApplication gets stuck in SUBMITTED state indefinitely.

There must be a way to update the SparkApplication to reflect the status of the spark driver pod so that we can see if image pull errors are present when checking the status of the SparkApplication.

**Comment by shivannakarthik** [comment]
@ChenYi015 - Can we please reopen this. Please assign this to me, I can take a look at this.
