### ISSUE TITLE
Spark Submit only starts on Driver but not on executors

### ISSUE THREAD

**Issue by harsoni** [kubeflow/spark-operator#1771]
This is same as this issue: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1562
But,
Hey, I am facing the same issue , I tried your solution by removing the rest of the properties from spark conf, but still it is not working, only driver is coming up, and no logs about ExecutorPodsAllocator.
I had run the spark-submit by following command:

```
spark-submit \
    --master k8s://https://<IP>:<PORT> \
    --deploy-mode cluster \
    --name testingSpark \
    --files local:///opt/spark/service-account.json\
    --jars local:///opt/spark/jars/gcs-connector-hadoop3-latest.jar\
    --class com.test.TestingSpark \
    --conf spark.executor.instances=3 \
    --conf spark.executor.extraJavaOptions="--add-exports=java.base/sun.nio.ch=ALL-UNNAMED"\
    --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark-test \
    --conf spark.kubernetes.namespace=spark\
    --conf spark.kubernetes.container.image=<Image Link> \
    --conf spark.kubernetes.driverEnv.ENV1=Val1\
    --conf spark.kubernetes.driverEnv.ENV2=Val2\
    --conf spark.executorEnv.ENV1=Val1\
    --conf spark.executorEnv.ENV2=Val2\
    local:///opt/spark/test-spark/TestJar.jar

```
<img width="885" alt="Screenshot 2023-06-06 at 11 12 34 PM" src="https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/assets/25179898/2a3407bf-7941-48eb-83c5-53aa1e261b43">
In the driver on port 4040, spark UI is running but there I see, spark.master is set as local, why is it local, when i had set it to k8s, is this the issue.

**Comment by donnysa** [comment]
@harsoni did you ever manage to figure this out? I have the same issue

**Comment by IElgohary** [comment]
@donnysa The issue for me was that the jars path was on an HDFS cluster that was not accessible by the machine and everything worked as expected after moving the jars to an accessible cluster. However, I'm using unmanaged standalone spark but maybe my findings can guide you to fix your issue.
