### ISSUE TITLE
Access to the StreamingQuery status through the ingress

### ISSUE THREAD

**Issue by nickpodobiedov** [kubeflow/spark-operator#1772]
We use SparkOperator and have an issue with access to the detailed stream statistics.
1. Operator configuration: '-ingress-url-format=http://<ingress_url>/spark/{{$appName}}'
2. Sparkapplication configuration:
```
    spark.ui.proxyBase: /spark/pyspark-realtime
    spark.ui.proxyRedirectUri: /spark/pyspark-realtime
    spark.ui.reverseProxyUrl: /spark/pyspark-realtime
```
I can get access to the all application data from UI, for example:   http://<ingress_url>/spark/pyspark-realtime/jobs/ e.t.c. Also I can get `Structured Streaming` page:
![image](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/assets/103495120/d5d3c2f8-d83c-4158-aa44-fa7b3f5e4ad2)
Its URL is https://<ingress_url>/spark/pyspark-realtime/StreamingQuery/.
But when I want to see details for each stream, I got redirect to the https://<ingress_url>/StreamingQuery/statistics/?id=<stream_id> without needed prefix.
I think `spark.ui.proxyRedirectUri` param is responsive for this, but I cannot rewrite it, even with my configuration (when I setup this parameter directly) I get the `spark.ui.proxyRedirectUri=/` in driver configmap.
Thank you for help!

**Comment by puneetloya** [comment]
I was just looking into it. This is the piece of code that does this:
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/5f2efd4ff97e7c0bfdb726a066118d3401576730/pkg/controller/sparkapplication/controller.go#L699-L705

That is the reason your settings are being overwritten. If you want you can disable this by using --ingress-url-fomrat but then you may have to create the ingress yourself.
