### ISSUE TITLE
Image gcr.io/spark-operator/spark:v3.1.1 with vulnerabilities

### ISSUE THREAD

**Issue by FlavioOdas** [kubeflow/spark-operator#1800]
Hi all, the current image from Spark Operator gcr.io/spark-operator/spark:v3.1.1 is full of vulnerabilities and hasn't been updated in a while, are there any alternatives from this image?

**Comment by dlorenc** [comment]
I just asked over here if the repo is maintained: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1829

We're working on an image with fewer cves, but it's hard to tell if it's worth forking or trying to contribute back here.

**Comment by oschrenk** [comment]
Is there an alternative to this image?

```
docker pull gcr.io/spark-operator/spark:v3.1.1
Error response from daemon: manifest for gcr.io/spark-operator/spark:v3.1.1 not found: manifest unknown: Failed to fetch "v3.1.1" from request "/v2/spark-operator/spark/manifests/v3.1.1".
```
Or latest

```
❯ docker pull gcr.io/spark-operator/spark
Using default tag: latest
Error response from daemon: manifest for gcr.io/spark-operator/spark:latest not found: manifest unknown: Failed to fetch "latest" from request "/v2/spark-operator/spark/manifests/latest".

```

To be honest to have a migration path for my application I would also be happy to pull the `gcr.io/spark-operator/spark:v3.1.1 ` image despite the vulnerabilities. currently I can't a legacy application because the image is gone.
