### ISSUE TITLE
Need Help in building Spark Operator for Scala code.

### ISSUE THREAD

**Issue by bubbybharath** [kubeflow/spark-operator#1809]
Need Help in building Spark Operator for Scala code.

We have built an image for the spark operator with python. and able to spin up the driver and executors. We need similar image to be built for scala code.

1) Docker file not listed for scala. It is available only for R and python.

**Comment by OneCricketeer** [comment]
Did you see the example file that runs Scala code?

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml
