### ISSUE TITLE
high-privilege service account in Driver Pods cause attack

### ISSUE THREAD

**Issue by tingweiwu** [kubeflow/spark-operator#1814]
[About the Service Account for Driver Pods](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/quick-start-guide.md#about-the-service-account-for-driver-pods)

Use the service account  in driver pod, you can create pod with any spec.

If PodSecurityPolicy or  PodSecurityAdmission is not restricted, attacker can directly create a permission container mount machine shares the host namespace and directly obtains the computing node control permission. Even though PodSecurityPolicy or  PodSecurityAdmission is restricted, may cause number of unrelated  pods created

is there any suggestions for security protection?

is there a way to restrict the creation of pods by user code, or restrict executor pod spec which craete by driver pod

**Comment by 0marq** [comment]
+1
