### ISSUE TITLE
deploy-mode "cluster" ignored, launching a Spark Job using Helm chart for spark operator

### ISSUE THREAD

**Issue by ddevidence** [kubeflow/spark-operator#1817]
Logs from the k8s pod

`+ SPARK_CLASSPATH='/opt/spark/conf::/opt/spark/jars/*'
+ case "$1" in
+ shift 1
+ CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
+ exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=100.xyz.xyz.xyz --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class com.xxx.yyy.zzz.StreamingApplication local:///opt/spark/jars/my-job.jar`

After specifying the sparkApplication.yaml/spec/mode: cluster and sparkApplication.yaml/spec/sparkConf/spark.master as "k8s://https://" still seeing the spark job when launch starting in client mode instead of the cluster mode as specified in the sparkApplication.yaml. 

In addition also added an /opt/spark/conf/spark-defaults.conf with the same options to the docker image created however it leads to the same. 

It appears the options are being superseded by some spark-submit options that get passed at startup, its not clear where this is coming from as I have tried performing a search without much success 

Appreciate any help!

**Comment by AlexNavara** [comment]
@ddevidence This is expected spark behavior, and it's not related to spark operator. Do not look at the driver pod logs, it will always run in 'client' mode: https://github.com/apache/spark/blob/branch-3.4/resource-managers/kubernetes/docker/src/main/dockerfiles/spark/entrypoint.sh#L84

"spark-submit" is a multipurpose script that's used not just for app submission, but for driver process startup as well. When you run an app in cluster mode, 'spark-submit' is called at least twice: on app submission and on driver startup. In spark operator case, app submission happens inside operator container itself. So if you want to look at initial spark-submit command - check out operator pod logs.

Regarding 'spark.master' conf property, you don't need to set it explicitly if you use spark operator. Operator will set it for you automatically here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/submission.go#L97 And here is how it will compute the endpoint: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/controller/sparkapplication/submission.go#L201-L211
