### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by dlorenc** [kubeflow/spark-operator#1829]
It has a lot of usage, but I'm unable to tell how active it is. A lot of the go modules are starting to trigger vulnerability scanners, so I'm curious if this is still maintained and worth recommending/using.

**Comment by liyinan926** [comment]
I have not been able to allocate enough time to actively maintain this repo, so any help updating the go modules from the community will be highly appreciated. I'm happy to review any PR.

**Comment by vara-bonthu** [comment]
Linking the issue #1892
