### ISSUE TITLE
[Bug] Helm failed to add spark operator repo

### ISSUE THREAD

**Issue by cnCloXie** [kubeflow/spark-operator#1842]
Hi team,

Please help advise how to resolve this issue when adding spark operator repo

helm version
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}

`helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
Error: looks like "https://googlecloudplatform.github.io/spark-on-k8s-operator" is not a valid chart repository or cannot be reached: Get "https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml": tls: failed to verify certificate: x509: “googlecloudplatform.github.io” certificate is not trusted`

**Comment by Rohitrajak1807** [comment]
> Hi team,
> 
> Please help advise how to resolve this issue when adding spark operator repo
> 
> helm version version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.5"}
> 
> `helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator Error: looks like "https://googlecloudplatform.github.io/spark-on-k8s-operator" is not a valid chart repository or cannot be reached: Get "https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml": tls: failed to verify certificate: x509: “googlecloudplatform.github.io” certificate is not trusted`

@cnCloXie please check https://github.com/kubeflow/spark-operator/issues/1940
