### ISSUE TITLE
When will operator support spark 3.3.0 or above?

### ISSUE THREAD

**Issue by jhonnli** [kubeflow/spark-operator#1857]
When will operator support spark 3.3.0 or above?

**Comment by kori73** [comment]
We are using it with Spark 3.3.2 as well

**Comment by jhonnli** [comment]
> We are using it with Spark 3.3.2 as well


Which version are you using that supports v3.3.2?

**Comment by jhonnli** [comment]
> Which version are you using

Which version are you using

**Comment by jhonnli** [comment]
Sorry, I missed it. I read the documentation carefully today. The latest releases support Spark 2.3 and up.

**Comment by daniel-mueller** [comment]
So can we assume that 

> Spark 2.3 and up

includes all stable major versions of Spark, like 3.5? We already run it successfully with 3.3, but I'd appreciate it if the docs would give a bit more clarity on this.

**Comment by truongbk24** [comment]
I'm running the Spark 3.2.1 with the latest operator but when i use the spark-avro 3.2.0, it said i'm running on the LEGACY spark and failed the job, do you have any idea? I'm running locally within Spark 3.2.1 with library is fine.
