### ISSUE TITLE
Reject spark application submit when cluster capacity is reached

### ISSUE THREAD

**Issue by hiradha** [kubeflow/spark-operator#1863]
We use spark operator to submit spark jobs on our k8s cluster.
However many times the cluster will have no capacity or will have capacity to run only one of out the three requested executors.

We need the  functionality to reject such spark job submissions - rather than accepting them and the executors stay Pending.

Is such a functionality available? If not, which files do I need to start taking a look at in case I can contribute a PR.

**Comment by jacobsalway** [comment]
Take a look at the resource quota enforcement built into the operator https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#enabling-resource-quota-enforcement. Although I'd also encourage you to take a look at alternative Kubernetes schedulers that fit better with batch workloads such as [Volcano](https://volcano.sh/en/) or [Yunikorn](https://yunikorn.apache.org/).
