### ISSUE TITLE
Move Spark-on-K8s-operator repository to Kubeflow

### ISSUE THREAD

**Issue by mwielgus** [kubeflow/spark-operator#1892]
Based on the discussions in https://github.com/kubeflow/community/issues/648 and https://github.com/kubeflow/community/pull/672, there is a strong interest in the Kubeflow community in pushing the Spark-on-k8s-operator forward, contributing new features and continuing with its maintenance. Given the slow down under the current org structure, the project and its users will greatly benefit from the expanded, vendor-neutral community where people from both Google and other companies can easily contribute.

cc: @andreyvelich @vara-bonthu @yuchaoran2011

**Comment by vgkowski** [comment]
I would prefer to have an independent project outside of Kubeflow's influence

**Comment by mwielgus** [comment]
@vgkowski What are your concerns regarding Kubeflow?

**Comment by nttq1sub** [comment]
@mwielgus I strongly agree with you, for the community interest. It's almost half a year that this repo does not release any new version.

**Comment by vara-bonthu** [comment]
The repository has been moved to Kubeflow, and this issue can now be marked as resolved.
