### ISSUE TITLE
Intermittent failures to create K8s resources by Sparkoperator due to suddenly missing K8s API permissions 

### ISSUE THREAD

**Issue by jgoeres** [kubeflow/spark-operator#1894]
Hi,
we have been running Spark applications via the Spark operator for a while now. We recently updated from K82 v1.25 to v1.27 (AWS EKS, to be precise) and on one of our prod systems (the one making the most use of Spark applications) we are now seeing intermittent problems of the Spark operator to create K8s resources for a new SparkApplication CR, e.g.

    failed to create UI service for SparkApplication myns/xyzabc-mysparkapp-k93nb0: services is forbidden: User "system:serviceaccount:myns-spark:myns-spark-spark-operator" cannot create resource "services" in API group "" in the namespace "myns"

or

    Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.20.0.1/api/v1/namespaces/myns/pods. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. pods is forbidden: User "system:serviceaccount:myns-spark:myns-spark-spark-operator" cannot create resource "pods" in API group "" in the namespace "myns".

Attached, find a (sanitized) Spark operator log snippet with the full logs during such a situation

This usually happens for all K8s resource creation attempts during a short time interval and then it starts working again.
Currently, our best guess that this might be related to the change in service account token lifetime, which originally was unlimited, but starting with K8s 1.21 (?) this was changed to one hour. (but on EKS clusters, the life time of these tokens has been (and probably still is, there is no clear info on that) extended to 90 days to allow a smoother transition). 
We guess that the tokens expire now more rapidly (or now even hourly), are eventually refreshed by the Spark operator's K8s client, but with some delay, during which requests fail. 
We currently still use 1.3.3, I was looking for changes that might fix this in the newer versions but couldn't find any release notes (or any new entries in this project's releases for the operator, only for the Helm chart).

Any hints appreciated.

J

[Log_Sanitized.txt](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/files/13684959/Log_Sanitized.txt)

**Comment by jgoeres** [comment]
We actually made some progress on the root cause of this behavior. We deploy our app and also the Spark Operator itself with ArgoCD. ArgoCD maps the Helm hooks that are used for Sparkoperator's service account, RBAC and the webhook init job to its own hooks. In particular 

  "helm.sh/hook-delete-policy": (hook-failed, ) before-hook-creation

is mapped to ArgoCD's 
    
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation 

and 

     "helm.sh/hook": pre-install, pre-upgrade

is mapped to 

    argocd.argoproj.io/hook: PreSync

This appears to result in every ArgoCD sync (and this also seems to include syncs that are effectively a no-op) ArgoCD will first delete all these "hook-created" resources and then to recreates them.
So there is a short time where the serviceaccount, clusterrole or CRB might not be there during a sync, which would explain the behavior.
I assume the reason for having the spark operator's RBAC resources (SA, CR, CRB) created by the hook is to be able to use them also from the webhook-init-job (which IIRC mainly creates a bunch of secrets with keys and CA certs which are then used for TLS in the sparkl operator's webhook endpoint and which are also passed to K8s with the creation of the mutatingadmission webhook resource to make K8s trust the webhook endpoint) and later the same SA+CR+CRB are reused for "runtime use" by the spark operator.
Since Argo does not seem to offer a way to run the hooks only on "non-no-op" syncs, I guess the proper solution to this problem would be to have dedicated SA+CR+CRB for the webhook init job (which would probably require fewer permissions) and "runtime" SA+CR+CRB for the sparkoperator which would be created as regular resources, and thus would not be victim of the ArgoCD hook-delete-policy.

Thoughts?

**Comment by yebolenko** [comment]
any progress on this?
we have the same problem when we moved spark operator to be managed by argo

**Comment by diegs** [comment]
I'm hitting this with Rancher Fleet as well. I have to do some combination of forcing another helm no-op run and then manually deleting the operator pod to restart it (the logs show TLS certificate errors until I do) and then the webhook starts working again.

**Comment by fjammes** [comment]
I also met this issue with spark-operator + argoCD, I have to restart the spark-operator pod manually

**Comment by fjammes** [comment]
Disabling serviceAccount and RBAC creation in the argoCD app solves this issue:
```apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-operator
  namespace: argocd
spec:
  project: default
  source:
    chart: spark-operator
    repoURL: https://kubeflow.github.io/spark-operator
    targetRevision: 1.3.2
    helm:
      releaseName: spark-operator
      valuesObject:
        webhook:
          enable: true
        sparkJobNamespaces: {{ .Values.spec.sparkJobNamespaces }}
        # FIXME: Creating rbac and sa in argocd prevent correct startup of spark-operator
        serviceAccounts:
          spark:
            create: false
            name: spark
          sparkoperator:
            create: false
            name: spark-operator
        rbac:
          createClusterRole: false
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: spark-operator
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
```
