### ISSUE TITLE
Docker Image Not Found

### ISSUE THREAD

**Issue by jasonlai1218** [kubeflow/spark-operator#1899]
I execute this cmd: `docker pull gcr.io/spark-operator/spark-py:v3.1.0`
> Error response from daemon: manifest for gcr.io/spark-operator/spark-py:v3.1.0 not found: manifest unknown: Failed to fetch "v3.1.0" from request "/v2/spark-operator/spark-py/manifests/v3.1.0".

**Comment by acherla** [comment]
Use the official spark docker repo instead, confirmed it works.  https://hub.docker.com/_/spark/tags
