### ISSUE TITLE
Request for Dockerfile Definition or Guidelines for Base Image gcr.io/spark-operator/spark:v3.1.1

### ISSUE THREAD

**Issue by ruslanguns** [kubeflow/spark-operator#1913]
I am reaching out regarding an issue we are currently facing due to restricted access to the public registry. This limitation has impacted our ability to work effectively with the Spark Operator. To address this, I kindly request if you could provide the Dockerfile definition for the base image `gcr.io/spark-operator/spark:v3.1.1`. 

Thank you in advance for your support and understanding.

**Comment by ahululu** [comment]
+域名即将到期

**Comment by mattssll** [comment]
+1
