### ISSUE TITLE
Provide  a prefix for executor's pods

### ISSUE THREAD

**Issue by TKul6** [kubeflow/spark-operator#1916]
HI, 

I'm using `spark-on-k8-operator` to run multiple spark applications on the same Kubernetes cluster at the same time.
I have a couple of spark job that runs simultaneously and I want to understand for each `driver` pod, what are a the associated `executor` pods.

I can see there is some uuid associated with each executor and I wanted to know if there is a way for me to provide this uuid, or to provide a better prefix  (including a uuid).

Alternatively, if there is a way to connect between the uuid in the `executor` pod's  name to the associated `driver` it would be enough for me.

Thanks.

**Comment by rkrao89** [comment]
You can use this Spark config to set a prefix for your executor pods. `spark.kubernetes.executor.podNamePrefix`
