### ISSUE TITLE
Helm install the operator failed with error message "timed out waiting for the condition"

### ISSUE THREAD

**Issue by pangtg** [kubeflow/spark-operator#1922]
Hi,

I am evaluating spark on k8s operator but not able to get it installed. Could you take a look at and possibly fix the issue?

My commans are:
helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
helm install k8s-spark spark-operator/spark-operator --namespace spark-operator --create-namespace --set sparkJobNamespace=default --set webhook.enable=true

My kubernetes version is:
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3

Thanks

**Comment by glongrais** [comment]
I had the same issue while trying to install it on a local Minikube. I believe it's related to [this issue](https://github.com/helm/charts/pull/15487#issuecomment-510917892). Setting the `webhook.enable` to `false` did the trick if you don't need it.

**Comment by pangtg** [comment]
Thanks glongrais. By disabling  webhook the operator works

**Comment by hogiabao2601** [comment]
@glongrais do you know why do we need to disable `webhook`, in case we need the webhook then how can we enable that?

**Comment by leticiasss** [comment]
I've been trying to activate the webhook, but  unsuccess, any updates on that?

**Comment by nelsonrogers** [comment]
/reopen
I aslo get the issue with the webhook. Any solutions to enable it ?
