### ISSUE TITLE
Support dnsPolicy and dnsConfigs for operator and webhook in Helm chart.

### ISSUE THREAD

**Issue by messerzen** [kubeflow/spark-operator#1924]
Hello. I'm trying to use the spark-on-k8s-operator using a different `dnsConfig`  and `dnsPolicy`  due to some restrictions and limitations of k8s cluster that I'm using.

Something like this in `values.yaml` of helm chart:

```
dnsConfig:
          nameservers:
          - XXX.XX.X.XXX
dnsPolicy: ClusterFirstWithHostNet
```

This is necessary because, in my case, if I don't set `dnsPolicy: ClusterFirstWithHostNet` for the pods in my cluster, it's not solving the dns `kubernetes.default.svc` used to initialize the webhook. The image below shows the error if I don't set dnsPolicy: ClusterFirstWithHostNet (it happens for both `init-webhook` and `clean-up-webhook`)  

![image](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/assets/39966249/e917b830-96bc-41e9-b99f-af5a09bf834c)

 I need to use the webhook activated in order to some customizations in SparkApplication take effect (like also, configure `dnsConfig` and `dnsPolicy`) for driver and executors, otherwise, it will not take effect.

Thanks!

**Comment by messerzen** [comment]
Hi @leticiasss. In my case, the k8s cluster network was fixed and it started to work ( the webhook ). I think one possible workaround for it is to generate the yaml mafinests files from the helm chart, edit the manifests network configs and deploy it manually.

**Comment by leticiasss** [comment]
Hi @messerzen. Thank you for updated. Initially the installation unsuccessful, but did it again, then worked as expected.
