### ISSUE TITLE
404 Not Found https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml 

### ISSUE THREAD

**Issue by leviem1** [kubeflow/spark-operator#1926]
Can't pull the `spark-on-k8s-operator` Helm chart as of 6 hours ago with the latest environment deployment. Seems to have been triggered by @zijianjoy. Did the deployment not run from the correct branch or something?

404: https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml

**Comment by afer4152** [comment]
Getting same error 

```
# [2024-03-13T18:58:30.175Z] Error:: looks like "https://googlecloudplatform.github.io/spark-on-k8s-operator" 
# is not a valid chart repository or cannot be reached: failed to fetch https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml : 404 Not Found
```

**Comment by SandipGorde-TomTom** [comment]
I am also getting same error since few hours ago

**Comment by ksemele** [comment]
same...

**Comment by ksemele** [comment]
https://charts.helm.sh/incubator/ works too... but what is correct repo address now?

**Comment by kimisu1** [comment]
Probably this one https://kubeflow.github.io/spark-operator/  because [spark-operator](https://github.com/kubeflow/spark-operator) not in [GoogleCloudPlatform](https://github.com/googlecloudplatform) currently it in [kubeflow](https://github.com/kubeflow)

**Comment by robwithhair** [comment]
Changing to the following helm dependency worked for me this morning.  Version omitted as I'm on an old version.
```
dependencies:
- name: spark-operator
  repository: https://kubeflow.github.io/spark-operator
  version: ?.?.?
  condition: spark-operator.enabled
```
Would be good to know if this is correct moving forward as others have said.

**Comment by Miller-5** [comment]
> Look like in this [deployment ](https://github.com/kubeflow/spark-operator/actions/runs/8269669981) it deployed into https://kubeflow.github.io/spark-operator/ instead https://googlecloudplatform.github.io/spark-on-k8s-operator/

This worked for us too, thanks!!

**Comment by EliranTurgeman** [comment]
same here: this one worked for me : 
`resource "helm_release" "main" {
    depends_on      = [ var.module_depends_on, kubernetes_namespace.main, kubernetes_namespace.spark_apps ]

    chart           = "spark-operator"
	
    repository      = "https://kubeflow.github.io/spark-operator"
    version         = "1.1.27"


    name      		= "spark-operator"`
![ScreenShot 14-March-2024 at 12 25 35 UTC Code-helm tf (Working Tree) (helm tf) — csi@2x](https://github.com/kubeflow/spark-operator/assets/98872315/0bf19d17-1826-40bf-9bd8-25a6e17b5dee)

![ScreenShot 14-March-2024 at 12 25 35 UTC Code-helm tf (Working Tree) (helm tf) — csi@2x](https://github.com/kubeflow/spark-operator/assets/98872315/c35cb5dc-5f5a-488d-88ab-4cf37c8bda3a)

**Comment by vara-bonthu** [comment]
Thanks for reporting the issue. Yes, this issue is due to the repo migration to Kubeflow org. We will create a PR to update the Helm chart and verify the Github workflows. 
FYI... @yuchaoran2011

**Comment by zijianjoy** [comment]
Hello everyone, 

yes I triggered the repo migration from googlecloudplatform to kubeflow, thus causing https://kubeflow.github.io/spark-operator/index.yaml being the new endpoint. You can find more detail about this move in https://github.com/kubeflow/community/issues/684.

Thanks for taking the effort to migrate the rest of related artifacts. cc @andreyvelich to coordinate those changes.

**Comment by leviem1** [comment]
Thanks for the guidance! I'll close this ticket, but please consider pinning this issue afterwards so that other people can more easily find the resolution to this issue.

There was no mention of this change in this repo. Additionally, I personally had no idea kubeflow/community even existed (no mention in README or anything), let alone to look there for issues like this.
