### ISSUE TITLE
Action items for adoption of Spark Kubernetes Operator in Kubeflow

### ISSUE THREAD

**Issue by andreyvelich** [kubeflow/spark-operator#1928]
Related: https://github.com/kubeflow/community/issues/648, https://github.com/kubeflow/community/pull/672, https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1892

We have to follow these action items to transfer [Spark Operator](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/tree/master) to Kubeflow.

- [x] Get approval from Kubeflow Steering Committee to accept Spark Operator as a Kubeflow core component.
- [x] Transfer https://github.com/GoogleCloudPlatform/spark-on-k8s-operator repository to https://github.com/kubeflow/spark-operator.
- [x] Configure [`tide` for the new repository.](https://github.com/kubeflow/community/blob/master/repository-setup.md#setup-prow)
- [x] Add Spark Operator maintainers: @vara-bonthu @yuchaoran2011 @mwielgus to the Kubeflow Org: https://github.com/kubeflow/internal-acls?tab=readme-ov-file#joining-kubeflow-github-organization
- [x] Create OWNERS file with the maintainers: @vara-bonthu @yuchaoran2011 @mwielgus in the new Kubeflow repository.
- [x] Modify [the contributing](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/CONTRIBUTING.md) doc to follow Kubeflow contributing guidelines (e.g. licence agreement if that is required).
- [x] Attend to repo migration side effect in https://github.com/kubeflow/spark-operator/issues/1926.
- [x] Update docs with new helm charts link. (For example, https://github.com/kubeflow/spark-operator/tree/master?tab=readme-ov-file#installation)
- [x] Fix GitHub actions for helm charts.
- [x] Add Docker Hub Token to Spark Operator repo
- [x] Fix GitHub actions for container registry (Kubeflow DockerHub).
- [x] Migrate Spark Operator docs to [Kubeflow Website.](https://www.kubeflow.org/).
- [x] Improve the release process: https://github.com/kubeflow/spark-operator/issues/1975

Please let me know if I missed something @jbottum @james-jwu @zijianjoy.
Excited to see this moving forward 🎉

**Comment by zevisert** [comment]
Update to the spark-website repo: https://github.com/apache/spark-website/pull/553

**Comment by andreyvelich** [comment]
Since all of the items have been completed, we can close it.
Thanks everyone for your contributions 🎉
