### ISSUE TITLE
Update Release Workflows: Change Container Registry to Kubeflow's ghcr.io

### ISSUE THREAD

**Issue by vara-bonthu** [kubeflow/spark-operator#1930]
**Description:**
Following the migration of our project from the _GoogleCloudPlatform_ organization to the _Kubeflow_ organization, there is a need to update our release GitHub workflows. This update involves changing the Docker container registry references within our Github workflows to align with our new organizational repository.

**Current Configuration:**
The GitHub Actions workflows are currently configured to push Docker images to the following registry:

`ghcr.io/googlecloudplatform/spark-operator`

**Required Changes:**
All references to the Docker container registry within our GitHub Actions workflows need to be updated to the new location under the Kubeflow organization:

`ghcr.io/kubeflow/spark-operator`

**`Scope of the Update:`**

1. Identify and modify all instances in GitHub Actions workflows (*.yml files within the `.github/workflows/` directory) where the container registry is referenced.
2. Ensure that Docker push commands, image tags, and any other relevant configurations reflect the new registry path.
3. Review and test the updated workflows to confirm that images are correctly being pushed to the new registry location.

**Comment by zevisert** [comment]
We may have permanently lost existing docker images from [`ghcr.io/googlecloudplatform/spark-on-k8s-operator`](https://explore.ggcr.dev/?repo=ghcr.io/googlecloudplatform/spark-on-k8s-operator). I'm not seeing anything there anymore, it seems like they were never retagged into [`ghcr.io/kubeflow/spark-operator`](https://explore.ggcr.dev/?repo=ghcr.io/kubeflow/spark-operator). 

While trying to track down existing images to help get them migrated to the (canonical, I think) kubeflow registry mentioned in this issue, I found a few images at [`ghcr.io/googlecloudplatform/spark-operator`](https://explore.ggcr.dev/?repo=ghcr.io/googlecloudplatform/spark-operator), but given that the `googlecloudplatform/spark-operator` github repo never existed as far as I know, I'm not sure how long these images might be there for before being garbage collected. I thought ghcr registries had to match the repository names, but I could be wrong about that. 

I also found old mentions of [gcr.io/spark-operator/spark-operator](https://console.cloud.google.com/gcr/images/spark-operator/GLOBAL/spark-operator), but I also don't see any old images there.

**Comment by zevisert** [comment]
Actually, checking out old tags from the repo shows that existing builds and charts did in-fact reference `ghcr.io/googlecloudplatform/spark-operator`, so I think it'd be good to retag any images from there into `ghcr.io/kubeflow/spark-operator`. An admin in this repo could do that with something like this:

```bash
# Using cli tools: 
# crane: https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane.md
# gh: https://cli.github.com/
crane auth login ghcr.io --username zevisert --password $(gh auth token);

for tag in $(crane ls ghcr.io/googlecloudplatform/spark-operator); do
   crane copy "ghcr.io/googlecloudplatform/spark-operator:$tag" "ghcr.io/kubeflow/spark-operator:$tag"; 
done
```

**Comment by vara-bonthu** [comment]
Thanks for looking into this, @zevisert! 👍🏼

@AndrewChubatiuk, could you point us to someone in the Kubeflow org who could handle the step suggested by @zevisert?

This might be connected to issue #1991.

**Comment by andreyvelich** [comment]
As I said before: https://github.com/kubeflow/spark-operator/pull/1974, initially we agreed to publish operator images to the Kubeflow DockerHub.
I think, right now you publish controller image only when you make a new release.

For the old images, we can also push them to the new registry (`docker.io/kubeflow/spark-operator`) if community agreed on this.
@vara-bonthu @zevisert Let's discuss in our first Spark Operator community call ?

**Comment by zevisert** [comment]
Having the existing images along with any new images in one registry is something that'd help people regardless of which registry we choose long term. The script I suggested above would just need to 
a) login to dockerhub as well, and
b) have the destination argument to `crane copy` changed to `"docker.io/kubeflow/spark-operator:$tag"`

**Comment by AndrewChubatiuk** [comment]
suppose most people will be using image defined in a helm chart, but anyway makes sense to keep them both especially due to dockerhub rate limits
