### ISSUE TITLE
Is the repo actively taking contributions?

### ISSUE THREAD

**Issue by jacobsalway** [kubeflow/spark-operator#1936]
Hey, glad to see some activity on the repo. I haven't kept up to date with the transfer from Google to Kubeflow and am unsure of the roadmap - are you (the new maintainers) open to contributions even if they're not Kubeflow specific?

At ROKT we run quite an extensive Spark on Kubernetes set-up and have an internal fork and associated learnings from running 1000+ Spark pods in production. We'd be keen to upstream some of these changes back to the community

**Comment by josecsotomorales** [comment]
I would like to contribute as well, as it is widely used here at Qualytics!

**Comment by josecsotomorales** [comment]
We are maintaining our fork here at Qualytics, updated the operator image to Spark 3.5, with some security patches, and also re-pointed the docker images registry. Feel free to contribute there until we get some traction at Kubeflow.
Repo:
https://github.com/Qualytics/spark-operator
