### ISSUE TITLE
Support extended kube-scheduler as batch scheduler

### ISSUE THREAD

**Issue by KunWuLuan** [kubeflow/spark-operator#1943]
[Extended kube scheduler](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/config/crd/bases/scheduling.x-k8s.io_podgroups.yaml) support coscheduling.

Can we support creating podgroups.scheduling.x-k8s.io in batch scheduler?

**Comment by ChenYi015** [comment]
@KunWuLuan It is a good point to integrate extended kube-scheduler as batch scheduler besides volcano and yunikorn, and I will do it. 
/reopen
