### ISSUE TITLE
Documentation is not upto date

### ISSUE THREAD

**Issue by sharangaian** [kubeflow/spark-operator#1944]
The repository for the Spark operator has transitioned from its original location at googlecloudplatform.github.io/spark-on-k8s-operator to github.com/kubeflow/spark-operator/. However, the documentation has not been updated to reflect this change, leading to difficulties in utilizing the operator due to outdated instructions and links.

sharan@sharan:~/Documents/vs_code/Z_COmmands/Kind-test$ helm repo add spark-operator https://github.com/kubeflow/spark-operator/releases/tag/spark-operator-chart-1.1.26
Error: looks like "https://github.com/kubeflow/spark-operator/releases/tag/spark-operator-chart-1.1.26" is not a valid chart repository or cannot be reached: error converting YAML to JSON: yaml: line 180: mapping values are not allowed in this context

**Comment by JWDobken** [comment]
I experience the same:

```cmd
$ helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
Error: looks like "https://googlecloudplatform.github.io/spark-on-k8s-operator" is not a valid chart repository or cannot be reached: failed to fetch https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml : 404 Not Found
```

**Comment by JWDobken** [comment]
This works:

```cmd
helm repo add spark-operator https://kubeflow.github.io/spark-operator/
```

from https://github.com/kubeflow/spark-operator/issues/1940:
