### ISSUE TITLE
Unable to add Helm Chart

### ISSUE THREAD

**Issue by anandlingaraj** [kubeflow/spark-operator#1953]
Error: looks like "https://googlecloudplatform.github.io/spark-on-k8s-operator" is not a valid chart repository or cannot be reached: failed to fetch https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml : 404 Not Found

**Comment by ivanpfalcao** [comment]
Same problem here. I´m using version 1.1.27 of spark-on-k8s-operator. It´s Failing to fetch https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml. It seems that the repo has been closed or removed.

**Comment by ChenYi015** [comment]
> Error: looks like "https://googlecloudplatform.github.io/spark-on-k8s-operator" is not a valid chart repository or cannot be reached: failed to fetch https://googlecloudplatform.github.io/spark-on-k8s-operator/index.yaml : 404 Not Found

The helm repo has moved from `https://googlecloudplatform.github.io/spark-on-k8s-operator` to `https://kubeflow.github.io/spark-operator`, you can do as following:

```shell
# Remove old helm repo
helm repo remove spark-operator

# Add new helm repo
helm repo add spark-operator https://kubeflow.github.io/spark-operator

# Update helm repo
helm repo update

# Install the chart
helm install spark-operator spark-operator/spark-operator
```
