### ISSUE TITLE
SparkApplication in version "v1beta2" cannot be handled as a SparkApplication

### ISSUE THREAD

**Issue by morningcafe** [kubeflow/spark-operator#1965]
I just follow quick start guild and fail at step 2:
https://github.com/kubeflow/spark-operator/blob/master/docs/quick-start-guide.md

```
kubectl apply -f examples/spark-pi.yaml
```
somebody please help :(

**Comment by morningcafe** [comment]
Error from server (BadRequest): error when creating "examples/spark-pi.yaml": SparkApplication in version "v1beta2" cannot be handled as a SparkApplication: strict decoding error: unknown field "spec.sparkUIOptions.serviceLabels"

**Comment by bharathk005** [comment]
Please check the version
```shell
kubectl get crd sparkapplications.sparkoperator.k8s.io -o yaml
```

**Comment by wajeehulhassanvii** [comment]
I removed the field "spec.sparkUIOptions.serviceLabels", and it worked. The field is optional but I am not sure what effect is it going to have on the application.
