### ISSUE TITLE
[QUESTION] Failed to resolve dependencies in GoLand

### ISSUE THREAD

**Issue by EricGao888** [kubeflow/spark-operator#2005]
- [x] ✋ I have searched the open/closed issues and my issue is not listed.

#### Please describe your question here

I opened the project with GoLand, and got some errors like 

```
go: k8s.io/controller-manager@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/endpointslice@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/mount-utils@v0.0.0: invalid version: unknown revision v0.0.0
go: k8s.io/pod-security-admission@v0.0.0: invalid version: unknown revision v0.0.0
```

After I commented out `k8s.io/kubernetes v1.29.3` in `go.mod`, errors disappeared and all dependencies got resolved. Not sure whether it is a bug or I missed something. 

Any help will be appreciated.

#### Provide a link to the example/module related to the question

https://github.com/kubeflow/spark-operator/blob/333ee0bcb220862ec76df607e091d72c165c2d13/go.mod#L29

#### Additional context

I found some issues might be related to this one:

https://github.com/kubeflow/spark-operator/issues/1197

https://github.com/kubernetes/kubernetes/issues/79384

**Comment by Wangdaoshuai** [comment]
I recently encountered the same problem, and I solved it in the following way.
Create script get.sh in the go.mod directory.
Then execute bash get.sh v1.20.4 (here select the k8s version you need to use)
```
#!/bin/sh
set -euo pipefail

VERSION=${1#"v"}
if [ -z "$VERSION" ]; then
    echo "Must specify version!"
    exit 1
fi
MODS=($(
    curl -sS https://raw.githubusercontent.com/kubernetes/kubernetes/v${VERSION}/go.mod |
    sed -n 's|.*k8s.io/\(.*\) => ./staging/src/k8s.io/.*|k8s.io/\1|p'
))
for MOD in "${MODS[@]}"; do
    V=$(
        go mod download -json "${MOD}@kubernetes-${VERSION}" |
        sed -n 's|.*"Version": "\(.*\)".*|\1|p'
    )
    go mod edit "-replace=${MOD}=${MOD}@${V}"
done
go get "k8s.io/kubernetes@v${VERSION}"
```

**Comment by EricGao888** [comment]
> I recently encountered the same problem, and I solved it in the following way. Create script get.sh in the go.mod directory. Then execute bash get.sh v1.20.4 (here select the k8s version you need to use)
> 
> ```
> #!/bin/sh
> set -euo pipefail
> 
> VERSION=${1#"v"}
> if [ -z "$VERSION" ]; then
>     echo "Must specify version!"
>     exit 1
> fi
> MODS=($(
>     curl -sS https://raw.githubusercontent.com/kubernetes/kubernetes/v${VERSION}/go.mod |
>     sed -n 's|.*k8s.io/\(.*\) => ./staging/src/k8s.io/.*|k8s.io/\1|p'
> ))
> for MOD in "${MODS[@]}"; do
>     V=$(
>         go mod download -json "${MOD}@kubernetes-${VERSION}" |
>         sed -n 's|.*"Version": "\(.*\)".*|\1|p'
>     )
>     go mod edit "-replace=${MOD}=${MOD}@${V}"
> done
> go get "k8s.io/kubernetes@v${VERSION}"
> ```

@Wangdaoshuai Thanks, I will give a try later.

**Comment by iheme** [comment]
please add replace in go.mod 

replace (
        k8s.io/dynamic-resource-allocation => k8s.io/dynamic-resource-allocation v0.29.3
	k8s.io/endpointslice => k8s.io/endpointslice v0.29.3
        k8s.io/mount-utils => k8s.io/mount-utils v0.29.3
	k8s.io/controller-manager => k8s.io/controller-manager v0.29.3
	k8s.io/pod-security-admission => k8s.io/pod-security-admission v0.29.3
)

**Comment by onebox-li** [comment]
> please add replace in go.mod
> 
> replace ( k8s.io/dynamic-resource-allocation => k8s.io/dynamic-resource-allocation v0.29.3 k8s.io/endpointslice => k8s.io/endpointslice v0.29.3 k8s.io/mount-utils => k8s.io/mount-utils v0.29.3 k8s.io/controller-manager => k8s.io/controller-manager v0.29.3 k8s.io/pod-security-admission => k8s.io/pod-security-admission v0.29.3 )

Thanks, it works for me. Is there a need to add these to the default replace?

**Comment by jacobsalway** [comment]
/close

This was solved in https://github.com/kubeflow/spark-operator/pull/2107/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6
