### ISSUE TITLE
[FEATURE] Upgrade default image to Spark 3.5.1

### ISSUE THREAD

**Issue by peter-mcclonski** [kubeflow/spark-operator#2020]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

We should maintain a default image that aligns with the most recent stable release of Spark, including bug fixes and IA fixes.

#### Describe the solution you would like

The default `spark-operator` image, as well as our examples, should migrate from building atop Spark 3.5.0 to Spark 3.5.1

#### Describe alternatives you have considered

We should still highly consider building the operator against a larger set of Spark versions.  However, until discussions are held on this, we should at minimum keep up with the latest release.

#### Additional context

/good-first-issue

**Comment by ChenYi015** [comment]
@peter-mcclonski  The spark version has been bumped to 3.5.2 by #2154. This issue can be closed then.
