### ISSUE TITLE
Helm chart references non-existent version `v1beta2-1.4.2-3.5.0`

### ISSUE THREAD

**Issue by tasgon** [kubeflow/spark-operator#2034]
## Description

#1998 set the Helm chart's default `appVersion` to `v1beta2-1.4.2-3.5.0`, which fails to pull and does not appear to be listed on https://hub.docker.com/r/kubeflow/spark-operator/tags.

## Reproduction Code [Required]

```
helm repo add spark-operator https://kubeflow.github.io/spark-operator
helm install spark spark-operator/spark-operator --namespace spark-operator --create-namespace
```

Install the spark operator through Helm as described in the README.

## Expected behavior

The spark-operator pod starts successfully.

## Actual behavior

```
Failed to pull image "docker.io/kubeflow/spark-operator:v1beta2-1.4.2-3.5.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/kubeflow/spark-operator:v1beta2-1.4.2-3.5.0": failed to resolve reference "docker.io/kubeflow/spark-operator:v1beta2-1.4.2-3.5.0": docker.io/kubeflow/spark-operator:v1beta2-1.4.2-3.5.0: not found
```

**Comment by alstjs37** [comment]
Did you solved it ?
I have same problem too,,

**Comment by tasgon** [comment]
You can clone the repo locally and modify `Chart.yaml` to use the correct `appVersion` or you can override `image.tag` using either `--set image.tag=<correct_tag>` or a custom `values.yml` file.

**Comment by alstjs37** [comment]
Thanks!!
