### ISSUE TITLE
[BUG] volumes configmap not find in driver pod

### ISSUE THREAD

**Issue by zhang5059T** [kubeflow/spark-operator#2055]
## Description
I used helm to install the spark-operator, and the installed version is v1beta2-1.4.5-3.5.0.

k8s version： v1.21.14

Resource 
(base) [root@bogon spark]# kubectl get all -n spark-operator
NAME                                               READY   STATUS      RESTARTS   AGE
pod/spark-pi-driver                                0/1     Completed   0          4m21s
pod/spark-release-spark-operator-5bd4f7654-ctm62   1/1     Running     0          3h25m

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/spark-pi-ui-svc   ClusterIP   192.8.223.117   <none>        4040/TCP   4m23s

NAME                                           READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/spark-release-spark-operator   1/1     1            1           3h25m

NAME                                                     DESIRED   CURRENT   READY   AGE
replicaset.apps/spark-release-spark-operator-5bd4f7654   1         1         1       3h25m
(base) [root@bogon spark]# kube
kubeadm               kubectl               kubectl-ko            kubelet               kubelet-pre-start.sh  

## running a example
I have submitted a 'park-pi-configmap.yaml' to the cluster, in which there is a configuration to bind a ConfigMap to the driver and executor.

It can calculate pi, but when I look at the configuration file of the driver pod, I find that the volumeMounts configured earlier do not appear in it. 

## driver log
24/06/11 06:48:42 INFO TaskSetManager: Finished task 0.0 in stage 0.0 (TID 0) in 336 ms on 10.16.2.103 (executor 1) (1/2)
24/06/11 06:48:42 INFO TaskSetManager: Finished task 1.0 in stage 0.0 (TID 1) in 18 ms on 10.16.2.103 (executor 1) (2/2)
24/06/11 06:48:42 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
24/06/11 06:48:42 INFO DAGScheduler: ResultStage 0 (reduce at SparkPi.scala:38) finished in 0.561 s
24/06/11 06:48:42 INFO DAGScheduler: Job 0 is finished. Cancelling potential speculative or zombie tasks for this job
24/06/11 06:48:42 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage finished
24/06/11 06:48:42 INFO DAGScheduler: Job 0 finished: reduce at SparkPi.scala:38, took 0.640141 s
Pi is roughly 3.142475712378562
24/06/11 06:48:42 INFO SparkUI: Stopped Spark web UI at http://spark-pi-be42d090060e2e47-driver-svc.spark-operator.svc:4040
24/06/11 06:48:42 INFO KubernetesClusterSchedulerBackend: Shutting down all executors
24/06/11 06:48:42 INFO KubernetesClusterSchedulerBackend$KubernetesDriverEndpoint: Asking each executor to shut down
24/06/11 06:48:42 WARN ExecutorPodsWatchSnapshotSource: Kubernetes client has been closed.
24/06/11 06:48:42 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
24/06/11 06:48:42 INFO MemoryStore: MemoryStore cleared
24/06/11 06:48:42 INFO BlockManager: BlockManager stopped
24/06/11 06:48:42 INFO BlockManagerMaster: BlockManagerMaster stopped
24/06/11 06:48:42 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
24/06/11 06:48:42 INFO SparkContext: Successfully stopped SparkContext
24/06/11 06:48:42 INFO ShutdownHookManager: Shutdown hook called
24/06/11 06:48:42 INFO ShutdownHookManager: Deleting directory /tmp/spark-ceb77270-2f52-4c47-9462-ef88f0a3757a
24/06/11 06:48:42 INFO ShutdownHookManager: Deleting directory /var/data/spark-a5ab2f0d-663d-4d90-8cb9-28af5c8eb431/spark-2a1d4361-2978-4e08-88af-5efb7ce353e7
## driver pod  volumeMounts config
    volumeMounts:
    - mountPath: /var/data/spark-a5ab2f0d-663d-4d90-8cb9-28af5c8eb431
      name: spark-local-dir-1
    - mountPath: /opt/spark/conf
      name: spark-conf-volume-driver
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-gzrrf
      readOnly: true

##  park-pi-configmap volumeMounts config
  volumes:
    - name: config-vol
      configMap:
        name: dummy-cm
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.0
    serviceAccount: spark-release-spark
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.0
    volumeMounts:
      - name: config-vol
        mountPath: /opt/spark/mycm

**Comment by imtzer** [comment]
Hi @zhang5059T , it seens that your pi job has finished and successfully exited and driver pod turns into completed status?

**Comment by zhang5059T** [comment]
Hi @imtzer，  Thank you for your answer.
Yes, it can complete and exit normally, but the volumeMounts: configuration item in the pi example does not appear in the driver's pod configuration file.
Why I want to test this is  I need to pass some configuration items to the Spark task when I submit it, and these configuration items are dynamically generated and cannot be generated in advance. So I want to pass them to the driver through ConfigMap.

**Comment by zhang5059T** [comment]
I found that the logic of setting configmap and volumeMounts is in the webhook part, but the spark-operator does not  to enabling the webhook default. I tried to modify it and add the startup parameter -enable-webhook=true, but it threw an exception.
## EXCEPTION
goroutine 143 gp=0xc000a80fc0 m=nil [select]:
runtime.gopark(0xc00060efa8?, 0x2?, 0x60?, 0x0?, 0xc00060ef5c?)
        /usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00060ee00 sp=0xc00060ede0 pc=0x44094e
runtime.selectgo(0xc00060efa8, 0xc00060ef58, 0x1e13040?, 0x0, 0x0?, 0x1)
        /usr/local/go/src/runtime/select.go:327 +0x725 fp=0xc00060ef20 sp=0xc00060ee00 pc=0x451e65
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1()
        /go/pkg/mod/k8s.io/client-go@v0.29.3/tools/record/event.go:390 +0xfe fp=0xc00060efe0 sp=0xc00060ef20 pc=0x16465de
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00060efe8 sp=0xc00060efe0 pc=0x473721
created by k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher in goroutine 1
        /go/pkg/mod/k8s.io/client-go@v0.29.3/tools/record/event.go:387 +0xff

goroutine 291 gp=0xc000582e00 m=nil [runnable]:
github.com/kubeflow/spark-operator/pkg/client/informers/externalversions.(*sharedInformerFactory).Start.gowrap2()
        /workspace/pkg/client/informers/externalversions/factory.go:119 fp=0xc0009f6fe0 sp=0xc0009f6fd8 pc=0x16947c0
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0009f6fe8 sp=0xc0009f6fe0 pc=0x473721
created by github.com/kubeflow/spark-operator/pkg/client/informers/externalversions.(*sharedInformerFactory).Start in goroutine 511
        /workspace/pkg/client/informers/externalversions/factory.go:119 +0x1a5

rax    0x0
rbx    0xa
rcx    0x40708e
rdx    0x6
rdi    0xa
rsi    0x1f
rbp    0xc00078dac0
rsp    0xc00078da80
r8     0x0
r9     0x0
r10    0x0
r11    0x216
r12    0x0
r13    0x0
r14    0xc0000061c0
r15    0x7ffffff
rip    0x40708e
rflags 0x216
cs     0x33
fs     0x0
gs     0x0

**Comment by zhang5059T** [comment]
## Add the exception information
++ id -u
+ myuid=0
++ id -g
+ mygid=0
+ set +e
++ getent passwd 0
+ uidentry=root:x:0:0:root:/root:/bin/bash
+ set -e
+ echo 0
+ echo 0
+ echo root:x:0:0:root:/root:/bin/bash
0
0
root:x:0:0:root:/root:/bin/bash
+ [[ -z root:x:0:0:root:/root:/bin/bash ]]
+ exec /usr/bin/tini -s -- /usr/bin/spark-operator -v=2 -logtostderr -namespace= -enable-ui-service=true -ingress-url-format= -controller-threads=10 -resync-interval=30 -enable-batch-scheduler=false -label-selector-filter= -enable-metrics=true -metrics-labels=app_type -metrics-port=10254 -metrics-endpoint=/metrics -enable-webhook=true -metrics-prefix= -enable-resource-quota-enforcement=false
I0611 08:58:50.588285      10 main.go:152] Starting the Spark Operator
I0611 08:58:50.603940      10 capabilities.go:50] There is an orphaned API service. Server reports: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
I0611 08:58:50.603981      10 main.go:189] Enabling metrics collecting and exporting to Prometheus
I0611 08:58:50.604043      10 metrics.go:142] Started Metrics server at localhost:10254/metrics
F0611 08:58:50.604360      10 main.go:212] open /etc/webhook-certs/server-cert.pem: no such file or directory
