### ISSUE TITLE
[FEATURE] different priorityClass in driver and executor

### ISSUE THREAD

**Issue by liujin1993** [kubeflow/spark-operator#2094]
When driver pod is preempted，whole sparkapplication will fail. So we want to set high priorityClass to all drivers，and low priorityClasses to executors

**Comment by ChenYi015** [comment]
@liujin1993 Thanks for raising this feature request. The priorityClass field of driver/executor pod has already been added by PR #2146. This issued can be closed then.

**Comment by ChenYi015** [comment]
Close this issue by #2146.
