### ISSUE TITLE
[BUG] sparkctl build stanza is broken due to dependency on alpine builder image

### ISSUE THREAD

**Issue by lokkju** [kubeflow/spark-operator#2117]
## Description
`make build-sparkctl` fails as it currently depends on the `apk` package manager. Recently, in commit https://github.com/kubeflow/spark-operator/commit/0dc641bd1d7d262e4a8c5564c926fc4716bcf722 , the builder image in `Dockerfile` was switched from `golang:1.22-alpine` to `golang:1.22.5`; that latter, newer, image uses the `apt` package management rather than `apk`, breaking the sparkctl build.

- [ x] ✋ I have searched the open/closed issues and my issue is not listed.

**Comment by ChenYi015** [comment]
@lokkju Thanks for reporting this issue, I will fix it.
