### ISSUE TITLE
[BUG] helm chart crds are invalid in chart versions >=1.4.5

### ISSUE THREAD

**Issue by dada-engineer** [kubeflow/spark-operator#2151]
## Description
When Running the kubectl apply command to install custom resource definitions for spark-operator I get an error that metadata.annotations are too long. It worked in 1.4.4 of the chart but not in newer versions.

The error is:

`The CustomResourceDefinition "sparkapplications.sparkoperator.k8s.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

```bash
kubectl apply -f https://raw.githubusercontent.com/kubeflow/spark-operator/spark-operator-chart-1.4.4/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
# customresourcedefinition.apiextensions.k8s.io/sparkapplications.sparkoperator.k8s.io created
kubectl apply -f https://raw.githubusercontent.com/kubeflow/spark-operator/spark-operator-chart-1.4.6/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
# The CustomResourceDefinition "sparkapplications.sparkoperator.k8s.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

Execute the above statements in terminal

## Expected behavior

The crds should be installable without an issue

## Actual behavior

Installing CRDs fails hard

## Environment & Versions

- Spark Operator App version: Irrelevant
- Helm Chart Version: 1.4.6
- Kubernetes Version: 1.29
- Apache Spark version: Irrelevant

**Comment by ChenYi015** [comment]
@dada-engineer  For client-side apply, it will fail since the definition of the whole CRD will be patched as an annotation, which exceeds the size limit. You can install the CRDs with `kubectl create -f`:

```bash
kubectl create -f https://raw.githubusercontent.com/kubeflow/spark-operator/spark-operator-chart-1.4.4/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
kubectl create -f https://raw.githubusercontent.com/kubeflow/spark-operator/spark-operator-chart-1.4.6/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
```

Or use server-side apply:

```bash
kubectl apply --server-side -f https://raw.githubusercontent.com/kubeflow/spark-operator/spark-operator-chart-1.4.4/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
kubectl apply --server-side -f https://raw.githubusercontent.com/kubeflow/spark-operator/spark-operator-chart-1.4.6/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml
```

**Comment by dada-engineer** [comment]
Oh thanks a lot. this makes a lot of sense ❤️

**Comment by noahshpak** [comment]
In ArgoCD you can add the following to your `ApplicationSet` (you might need to force recreate)
```yaml
syncOptions:
          - ServerSideApply=true
```
