### ISSUE TITLE
[FEATURE] Add CI to scan docker image vulnerabilities

### ISSUE THREAD

**Issue by ChenYi015** [kubeflow/spark-operator#2169]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ImpSy** [comment]
Hey 👋 

I've already a fully functioning scanning pipeline on my [company fork](https://github.com/spotinst/spark-on-k8s-operator/blob/ocean-spark/.github/workflows/trivy-image-scanning.yaml), would you be interested in a contribution for this ?
It's build around [trivy](https://github.com/aquasecurity/trivy-action?tab=readme-ov-file#using-trivy-with-github-code-scanning)

I important think to note before activating it: you'll mostly pickup security error from the spark base image 
Patching JVM related issue could be out-of-scope for this project

A daily/weekly rebuild of the image + a dependabot like tool to upgrade the base spark image to the latest version could also replace/compliment this feature

**Comment by ChenYi015** [comment]
@ImpSy It would be great if you are willing to contribute this CI, there is an issue #2152 related to the image vulnerabilities.

> A daily/weekly rebuild of the image + a dependabot like tool to upgrade the base spark image to the latest version could also replace/compliment this feature

Totally agree, we should use the latest spark base image to rebuild spark operator images.

**Comment by jacobsalway** [comment]
I'd need to research whether there's anything else in the `apache/spark` image that the operator depends on, but it's possible we may be able to construct a different base image that downloads the Spark JARs separately (from Maven for example). This may reduce the surface area of CVEs but would obviously be more effort to maintain.

**Comment by ChenYi015** [comment]
Close this issue by #2177.
