### ISSUE TITLE
How I can change extensions/v1beta1 to networking.k8s.io/v1?

### ISSUE THREAD

**Issue by Nearyou46** [kubeflow/spark-operator#2194]
I deployed the last version of operator chart and when I created kind: SparkApplication it return an error
Error Message:  failed to create web UI ingress: failed to create ingress development/spark-test-ui-ingress: no matches for kind "Ingress" in version "extensions/v1beta1" 
It should use networking.k8s.io/v1 for ingress. 
I can't find where I can change it

**Comment by jacobsalway** [comment]
Thanks for reporting and you're not doing anything wrong: this is a bug I'm able to reproduce locally. This function that populates the ingress functionality cache is never run: https://github.com/kubeflow/spark-operator/blob/73caefd0d39ab208a2d4ebbba066344d72d05ed4/pkg/util/capabilities.go#L45-L52

I'll get a fix up for this.

**Comment by Nearyou46** [comment]
I Updated the chart, but I still have the same issue. Maybe something is wrong with SparkApplication.
Warning  SparkApplicationFailed  16s   spark-application-controller  SparkApplication spark-test1 failed: failed to create web UI ingress: failed to create ingress playground/spark-test1-ui-ingress: no matches for kind "Ingress" in version "extensions/v1beta1"

**Comment by missedone** [comment]
@Nearyou46 , one possible cause could be that you have the old ingress API version in the helm chart manifest while the kubernetes cluster has upgraded to the newer version that has old API version deleted.
you may check the ingress API version with command below: 
```shell
$ kubectl api-resources | grep ingresses
ingresses                          ing                                             networking.k8s.io/v1                         true         Ingress
```

also, check the ingress API version in helm manifest: 
```shell
helm get manifest spark-operator
```

**Comment by Nearyou46** [comment]
I checked all of this info, And I saw you didn`t release a new image with these changes. The last update for the operator on docker hub was 5 days ago

**Comment by ChenYi015** [comment]
> @ChenYi015 we should probably do a 2.0.2 release for this fix

Agree. I will do it as soon as possible.

**Comment by jacobsalway** [comment]
@ChenYi015 what do you think about closing issues as completed from the release PR rather than the PR to master?
