### ISSUE TITLE
[BUG] CRD update error

### ISSUE THREAD

**Issue by yuzhouliu9** [kubeflow/spark-operator#2212]
## Description
I'm currently on spark-operator helm-chart 1.1.17 and would like to upgrade to latest 2.0.1.

The CRDs in cluster are the v1beta2-1.3.3-3.1.1 tag version from [here](https://github.com/kubeflow/spark-operator/blob/v1beta2-1.3.3-3.1.1/charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml) and [here](https://github.com/kubeflow/spark-operator/blob/v1beta2-1.3.3-3.1.1/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml).

Running a diff against the latest v2.0.1 CRDs [here](https://github.com/kubeflow/spark-operator/blob/v2.0.1/charts/spark-operator-chart/crds/sparkoperator.k8s.io_scheduledsparkapplications.yaml) and [here](https://github.com/kubeflow/spark-operator/blob/v2.0.1/charts/spark-operator-chart/crds/sparkoperator.k8s.io_sparkapplications.yaml) results in error:
```
> kubectl diff -f sparkoperator.k8s.io_scheduledsparkapplications.yaml -f sparkoperator.k8s.io_sparkapplications.yaml
The CustomResourceDefinition "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```

So I add this to both CRDs.
```
spec:
  preserveUnknownFields: false
```

Now `kubectl diff` works but `kubectl apply` results in this error:
```
> kubectl apply -f sparkoperator.k8s.io_scheduledsparkapplications.yaml -f sparkoperator.k8s.io_sparkapplications.yaml
...
for: "sparkoperator.k8s.io_scheduledsparkapplications.yaml": error when patching "sparkoperator.k8s.io_scheduledsparkapplications.yaml": CustomResourceDefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
...
for: "sparkoperator.k8s.io_sparkapplications.yaml": error when patching "sparkoperator.k8s.io_sparkapplications.yaml": CustomResourceDefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

- [X] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

See Description

## Expected behavior
CRDs should not fail to apply.

## Actual behavior
CRD patch fails.

### Terminal Output Screenshot(s)
N/A

## Environment & Versions

- Spark Operator App version: v1beta2-1.3.3-3.1.1
- Helm Chart Version:  1.1.17
- Kubernetes Version: v1.26.15
- Apache Spark version: N/A

## Additional context
N/A

**Comment by ha2hi** [comment]
Hi,

Would you like to try it?
```
kubectl apply --server-side=true -f sparkoperator.k8s.io_scheduledsparkapplications.yaml
```

**Comment by yuzhouliu9** [comment]
Thanks that worked. But I had to do the following:

`kubectl apply --server-side=true` on the [v2.0.1 CRDs](https://github.com/kubeflow/spark-operator/tree/v2.0.1/charts/spark-operator-chart/crds) will fail with
```
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
Error from server (Invalid): CustomResourceDefinition.apiextensions.k8s.io "scheduledsparkapplications.sparkoperator.k8s.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema
```

I added `preserveUnknownFields: false` to the CRDs. Ran apply again, got the conflict error:
```
Apply failed with 1 conflict: conflict with "before-first-apply" using apiextensions.k8s.io/v1: .spec.preserveUnknownFields
```

Ran `kubectl apply --server-side=true --force-conflicts ...`, and that worked.
I removed the `preserveUnknownFields: false` and re-ran `kubectl apply --server-side=true` again.

Now `kubectl diff` is clean.

My question is: I know this is more of the k8s CRD management than spark-operator. But do you have clear guidance on what should be done in the case to update CRDs from v1.x.x to v2.x.x?

**Comment by josecsotomorales** [comment]
I'm also getting this when updating from v1 to v2:
```
CustomResourceDefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

**Comment by ChenYi015** [comment]
> I'm also getting this when updating from v1 to v2:
> 
> ```
> CustomResourceDefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
> ```

@josecsotomorales Have you tried using `kubectl replace -f` or server side apply (`kubectl apply --server-side=true -f`) to update the CRDs? For client side apply (`kubectl apply -f`) the whole definition of the CRD will be patched as annotations which will fail the updating due to the size exceeded the limit.

**Comment by josecsotomorales** [comment]
@ChenYi015 `kubectl apply --server-side=true` fixes this 🚀
