### ISSUE TITLE
Release 2.0.2

### ISSUE THREAD

**Issue by Nearyou46** [kubeflow/spark-operator#2224]
I would like to know when you can release 2.0.2 which has very important changes with API ingress for me

**Comment by ChenYi015** [comment]
@Nearyou46 We will release `v2.0.2` ASAP, hopefully in the next two days.

**Comment by ChenYi015** [comment]
Close this for [v2.0.2](https://github.com/kubeflow/spark-operator/releases/tag/v2.0.2) has already been released.
