### ISSUE TITLE
[QUESTION] Can the Spark Operator Run in a Single Namespace Without Cluster-Level Permissions?

### ISSUE THREAD

**Issue by josecsotomorales** [kubeflow/spark-operator#2240]
#### Please describe your question here

I'm running the Spark Operator in a Kubernetes environment and would like to configure it to operate entirely within a single namespace. Specifically, I want to avoid granting cluster-level permissions (i.e., avoiding using a `ClusterRoleBinding`) and only provide all necessary permissions within the operator's namespace.

Is there a recommended way to configure the Spark Operator to manage SparkApplications and other related resources (such as `ScheduledSparkApplications` and `pods`) within a single namespace without needing cluster-wide permissions?

#### Additional context

The operator runs with a `ClusterRoleBinding`, which grants it the necessary cluster-wide permissions. However, I would prefer to restrict its scope to a specific namespace. Any guidance on limiting the operator's permissions to a single namespace would be appreciated.

**Comment by ChenYi015** [comment]
I think `ClusterRole`/`ClusterRoleBinding` cannot be avoided, we have already restricted the permissions in ClusterRole to non-namespaced resources like node, event and CustormResourceDefinitions.
https://github.com/kubeflow/spark-operator/blob/a8b5d644b54328e25cf9b70d4ec4d4948d715ee2/charts/spark-operator-chart/templates/controller/rbac.yaml#L29-L49

**Comment by josecsotomorales** [comment]
Yeah that makes sense, thank you! Closing this issue.
