### ISSUE TITLE
[BUG] Disabling Web UI service in the Helm chart has no effect

### ISSUE THREAD

**Issue by Roberdvs** [kubeflow/spark-operator#2260]
## Description

We are encountering problems when auto-generated service names go beyond 63 characters and wanted to disable the Web UI service creation since we don't really need it.
- As a side note: this wasn't a big issue on previous versions since the SparkApplication continued to be created anyway even if the Service creation failed due to character limitations, but it seems that on v2 the application is not submitted when the Service creation has an error (which might be considered a separate issue).

> 2024-10-17T12:13:31.168Z	ERROR	sparkapplication/controller.go:260	Failed to submit SparkApplication	{"name": "omitted-spark-application-name", "namespace": "foo", "error": "failed to create web UI service: Service \"omitted-spark-application-service-name-longer-than-63-characters\" is invalid: metadata.name: Invalid value: \"omitted-spark-application-service-name-longer-than-63-characters\": must be no more than 63 characters"}

We found out that setting `controller.uiService.enable: false` in the Helm chart [removes the flag](https://github.com/kubeflow/spark-operator/blob/master/charts/spark-operator-chart/templates/controller/deployment.yaml#L67-L69) `--enable-ui-service=true` on the Deployment but since the [default is true](https://github.com/kubeflow/spark-operator/blob/master/cmd/operator/controller/start.go#L154), this doesn't really have any effect. 

Instead, the flag should be set to `false` when `controller.uiService.enable` is set to `false`.

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

## Reproduction Code [Required]

Set `controller.uiService.enable: false` to false in the Helm chart and watch the spark-operator create K8s services for SparkApplications.

## Expected behavior

Setting `controller.uiService.enable: false` in the Helm chart should disable the creation of K8s services when submitting SparkApplications

## Environment & Versions

- Spark Operator App version: 2.0.2
- Helm Chart Version: v2.0.2
- Kubernetes Version: 1.29
- Apache Spark version: N/A

**Comment by jacobsalway** [comment]
@Roberdvs I'll probably raise a fix to truncate the UI service name if over 63 chars. The service object created by the driver is similarly truncated in Spark core https://github.com/apache/spark/blob/7e9017ec8f6e6895a3251cc7250d6a72d63aed49/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/KubernetesConf.scala#L102-L116
