### ISSUE TITLE
helm repo update doesn’t fetch the latest Spark Operator version (v2.1.0-rc.0 Pre-release)

### ISSUE THREAD

**Issue by TheDevilDan** [kubeflow/spark-operator#2289]
### What question do you want to ask?

Hello,

When I run helm repo update, I can’t seem to fetch the latest version of Spark Operator (v2.1.0-rc.0, which is a pre-release). I expected it to show up so I could test it, but it doesn’t seem to be available in the repo.

Is it normal for this version not to appear, even after running helm repo update? Is there a setting or additional step needed to retrieve pre-release versions with Helm?

Thanks in advance for your help!

### Have the same question?

Give it a 👍 We prioritize the question with most 👍

**Comment by ChenYi015** [comment]
@TheDevilDan 

Helm will install the latest non pre-release version by default, if you want to try the latest pre-release version, you can either specify the chart version by `--version` flag:

```bash
helm install spark-operator spark-operator/spark-operator \
    --namespace spark-operator \
    --create-namespace \
    --version v2.1.0-rc.0
``` 

Or use the `--devel` flag to install the latest development version:

```bash
helm install spark-operator spark-operator/spark-operator \
    --namespace spark-operator \
    --create-namespace \
    --devel
```

**Comment by TheDevilDan** [comment]
Thank you, very simple :D thanks a lot.

```
helm search repo spark-operator --versions --devel
NAME                            CHART VERSION   APP VERSION             DESCRIPTION
spark-operator/spark-operator   2.1.0-rc.0      2.1.0-rc.0              A Helm chart for Spark on Kubernetes operator.
spark-operator/spark-operator   2.0.2           2.0.2                   A Helm chart for Spark on Kubernetes operator.
```

```
helm search repo spark-operator --version v2.1.0-rc.0
NAME                            CHART VERSION   APP VERSION     DESCRIPTION
spark-operator/spark-operator   2.1.0-rc.0      2.1.0-rc.0      A Helm chart for Spark on Kubernetes operator.
```
