### ISSUE TITLE
Disabling uiService does not work

### ISSUE THREAD

**Issue by BCantos17** [kubeflow/spark-operator#2291]
### What happened?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

### Reproduction Code

Set `controller.uiService.enable: false`

### Expected behavior

Spark uiService does not get created

### Actual behavior

uiService attempts to get created

### Environment & Versions

- Kubernetes Version: 1.29
- Spark Operator Version: 2.0.2
- Apache Spark Version: 3.5.1

### Additional context

Trying to disable the uiService as we are getting an error stating the service name is too long

```
Error stack: failed to create web UI service: Service "<REDACTED>-oyl61mhd-ui-svc" is invalid: metadata.name: Invalid value: "<REDACTED>-oyl61mhd-ui-svc": must be no more than 63 characters
```

I do not see `controller.uiService.enable: false` in the controller deployment spec which seems to be the expected behavior according to this [line](https://github.com/kubeflow/spark-operator/blob/v2.0.2/charts/spark-operator-chart/templates/controller/deployment.yaml#L67-L68)

Separately I noticed in the [_helpers.tpl](https://github.com/kubeflow/spark-operator/blob/ef9a2a134b80f8c5368db53615d9aa766c67ad0a/charts/spark-operator-chart/templates/_helpers.tpl#L26-L28) file that you are truncating the name of the name of the deployment. I think a similar logic on the service file would also help here

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍

**Comment by ChenYi015** [comment]
@BCantos17 Thanks for reporting this issue, it is duplicated with #2260 and has already been fixed.  The pre-release version `v2.1.0-rc.0` have been published with this fix.

> Separately I noticed in the [_helpers.tpl](https://github.com/kubeflow/spark-operator/blob/ef9a2a134b80f8c5368db53615d9aa766c67ad0a/charts/spark-operator-chart/templates/_helpers.tpl#L26-L28) file that you are truncating the name of the name of the deployment. I think a similar logic on the service file would also help here

Make sense, would you like to raise another feature request issue on this?

**Comment by BCantos17** [comment]
Thanks @ChenYi015. Sure I will open a feature request. Seems like @jacobsalway mentioned something similar but I am unaware if this has been implemented or recorded so I will open it regardless
