### ISSUE TITLE
[FEATURE] Truncate Webui Service name

### ISSUE THREAD

**Issue by BCantos17** [kubeflow/spark-operator#2300]
### What feature you would like to be added?

Truncate the service name of the web ui if the name reaches the character limit of 63

### Why is this needed?

Kubernetes has a character limit for the names of their service and will fail to create if the limit is reached

### Describe the solution you would like

Either truncate the name similar as seen in this file [_helper.tpl](https://github.com/kubeflow/spark-operator/blob/ef9a2a134b80f8c5368db53615d9aa766c67ad0a/charts/spark-operator-chart/templates/_helpers.tpl#L26-L28) file or what we see in [spark kubernetes core](https://github.com/apache/spark/blob/7e9017ec8f6e6895a3251cc7250d6a72d63aed49/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/KubernetesConf.scala#L102-L116)

### Love this feature?

Give it a 👍 We prioritize the features with most 👍

**Comment by jacobsalway** [comment]
I'll take on this feature request. I've run into a similar issue before and copied the logic that Spark core uses https://github.com/apache/spark/blob/b6c569fe4d702e91c47ed7848b3c5cc173e59b19/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/KubernetesConf.scala#L102-L116

**Comment by leticiasss** [comment]
Is there any update on this feature?

**Comment by jacobsalway** [comment]
@leticiasss I've raised a pull request that should fix this issue.
