### ISSUE TITLE
Upgrade volcano.sh/apis to 1.10.0-alpha.0 or above

### ISSUE THREAD

**Issue by GajaHebbar** [kubeflow/spark-operator#2318]
### What happened?

- [ yes ] ✋ I have searched the open/closed issues and my issue is not listed.

### Reproduction Code

Spark operator code works as expected but there is a critical vulnerability https://github.com/advisories/GHSA-5g3x-8g2v-r8x8 reported 9.3/10

Insecure permissions in volcano v1.8.2 allows attackers to access sensitive data and escalate privileges by obtaining the service account's token.

### Expected behavior

There should not be any vulnerability . Upgrade  volcano.sh/apis to 1.10.0-alpha.0 or higher

### Actual behavior

a critical vulnerability https://github.com/advisories/GHSA-5g3x-8g2v-r8x8 reported 9.3/10

### Environment & Versions

- Kubernetes Version: 1.16+
- Spark Operator Version: v2.0.x/v1beta2-1.3.x-3.1.1 any other version 
- Apache Spark Version: 3.1.1 +  /3.5.2 + 

### Additional context

As ANCHOR report identifies a https://github.com/advisories/GHSA-5g3x-8g2v-r8x8 which is a Critical vulnerability,  volcano.sh/apis needs to be upgraded to 1.10.0-alpha.0 or above

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍

**Comment by GajaHebbar** [comment]
@jacobsalway I see this is in master, but can you tell me in which release it will be updated?

**Comment by jacobsalway** [comment]
@ChenYi015 we should probably do another release soon given it's been nearly 2 months since the last one.

**Comment by ChenYi015** [comment]
I will release `v2.1.0` ASAP.
