### ISSUE TITLE
 Is leader election configurable in the Kubeflow Spark Operator Helm chart?

### ISSUE THREAD

**Issue by rampanwar97** [kubeflow/spark-operator#2359]
### What question do you want to ask?

 Hello ,

I have a question regarding the Kubeflow Spark Operator Helm chart. Is it possible to enable leader election using the current Helm chart? If yes, could you provide guidance or examples? If not, are there any plans to add this feature in the future?

Thank you!

**Comment by ChenYi015** [comment]
@rampanwar97 No, you cannot disable the leader election by using the Helm chart, even though there is a `--leader-election` flag to toggle the leader election for the Spark Operator binary. Why do you want to disable the leader election?

**Comment by ramsinghtmdc** [comment]
No disable, I want to enable it

**Comment by rampanwar97** [comment]
I don't want to disable it; I want to enable it through the Helm chart, but I couldn't find any related configurations in the Helm values file

**Comment by jacobsalway** [comment]
In older versions of the operator this was configurable, however in the more recent versions it's been enabled by default: https://github.com/kubeflow/spark-operator/blob/master/charts/spark-operator-chart/templates/controller/deployment.yaml#L92

**Comment by rampanwar97** [comment]
Got it, Thanks @jacobsalway.

**Comment by rampanwar97** [comment]
Got it, Thanks @jacobsalway
