### ISSUE TITLE
how to set IngressUrl for each sparkapplication

### ISSUE THREAD

**Issue by Nearyou46** [kubeflow/spark-operator#2372]
### What question do you want to ask?

how to set IngressUrl for each spark-application. now it creates the same URL that I set for spark operator helm chart
sparkApplications:
  - name: spark-app-1
    ui:
      enable: true
      urlFormat: "{{ .Release.Name }}-spark-app-1-ui.test.com"
 this config isn`t working

### Have the same question?

Give it a 👍 We prioritize the question with most 👍

**Comment by ChenYi015** [comment]
@Nearyou46 You can install the spark-operator as follows to configure the ingressUrlFormat:

```bash
helm repo add spark-operator https://kubeflow.github.io/spark-operator --force-update

helm install spark-operator spark-operator/spark-operator \
    --namespace spark-operator \
    --create-namespace \
    --set controller.uiIngress.enable=true \
    --set controller.uiIngress.urlFormat='{{$appName}}-spark-app-1-ui-test.com' \
    --set controller.uiIngress.ingressClassName=nginx
```

**Comment by Nearyou46** [comment]
Thank you, I will test it

**Comment by Nearyou46** [comment]
it works, thank you so much)
