### ISSUE TITLE
Configuring driver.podName causes Pod already exists error in `ScheduledSparkApplication`

### ISSUE THREAD

**Issue by spjegan** [kubeflow/spark-operator#300]
Configuring `driver.podName` causes Pod already exists error when the job gets triggered second time. 

One way to solve this (as per the discussion in the Slack channel) is, in case of a scheduled job, the configured `podName` could be treated as a prefix and the trigger could be appended to the `podName` prefix.

The work-around is to remove the `driver.podName`.

`
E0928 21:20:27.031886       1 submission_runner.go:93] failed to run spark-submit for SparkApplication gw-agg-1h-1538169624818944620 in namespace insights: Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.20.0.1/api/v1/namespaces/insights/pods. Message: pods "gw-agg-hourly" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=pods, name=gw-agg-hourly, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=pods "gw-agg-hourly" already exists, metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:470)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:409)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:379)
`

**Comment by liyinan926** [comment]
One potential solution is to treat `driver.podName` as a prefix that the `ScheduledSparkApplication` controller will use to construct the actual driver pod name, with a suffix that differs it between different runs.

**Comment by samarthkansal** [comment]
has anyone been able to resolve this issue ? i am facing this too

**Comment by zhaohc10apple** [comment]
we are facing the similar issue now,  any progress on this thread,  or should we upgrade kubernetes-client version and use createOrReplace method for the pod creation ?
