### ISSUE TITLE
[bug] executor pod memory overhead

### ISSUE THREAD

**Issue by chenqin** [kubeflow/spark-operator#401]
Step to reproduce, adding new node pool for executors with 5 n1-highmem-96 instances.
Wait til cluster update succeed, run kubectl get nodes and verify.

run spark operator yaml states run 5 executor pod on newly provisioned nodes.
Expected, the total memory assignment should be same as kubectl describe node xxx stated allocatable What I observed was have to leave 15% of overhead beyond memory+memoryoverhead in order to get executor pod running.

**Comment by liyinan926** [comment]
Can you elaborate more on the issue? It's unclear to me from reading the description above what's the problem.

**Comment by chenqin** [comment]
The yaml file requests executors with 600GB (executor.memory + executor. MemoryOverhead ) memory container.
The number of node is sam as number of executor pods I requested.

node description tells me those nodes allocatable memory of 623.876288Ki ~ 623.876288GB. 
` 
Allocatable:
 cpu:                95690m
 ephemeral-storage:  5596173889514
 hugepages-2Mi:      0
 memory:             623876288Ki
 pods:               110
`
What I expected is all executor pods get allocation. What I have been seeing was all executors we pending status until I reduce executors memory  (executor.memory + executor. MemoryOverhead ) 
 to 550GB
