### ISSUE TITLE
Improve attributes given by Prometheus monitoring

### ISSUE THREAD

**Issue by ghost** [kubeflow/spark-operator#480]
Maybe I overlooked the attributes but I noticed that it's hard to get a list of failed job names with the current Prometheus options (GCP).

You can either get: 
* JVM settings that don't give errors about the actual job
* Generic error/success counts from the spark operator
```
spark_app_executor_failure_count{app_kubernetes_io_name="sparkoperator",app_kubernetes_io_version="v2.4.0-v1beta1-latest",app_type="Unknown",instance="IP",job="kubernetes-pods",kubernetes_namespace="spark",kubernetes_pod_name="spark-operator-6cb49bfd54-mm2lr"}
```
Is there a way to get a list of failed job names?

**Comment by austinnichols101** [comment]
Try this one:

`sum(spark_app_status{status=~"running|failing|failed"}) by (status)`

**Comment by zwennesm** [comment]
@austinnichols101 `spark_app_status` is not a metric that is exposed in my environment. 

Running `gcr.io/spark-operator/spark:v2.4.4-gcs-prometheus`
with `/prometheus/jmx_prometheus_javaagent-0.11.0.jar`

**Comment by zwennesm** [comment]
For the people who are interested in this. For now I went with the approach of returning an exit code 1 in case of failure, and then I use the following Prometheus query to retrieve the failed pods:

```
sum by (phase, pod) ( 
  increase(kube_pod_status_phase{namespace="spark", phase="Failed", pod=~".*driver"}[30m]) 
)
```
