### ISSUE TITLE
Airflow Integration

### ISSUE THREAD

**Issue by ashishwrt** [kubeflow/spark-operator#502]
Has anyone use this operator with Airflow? ie Schedule jobs via airflow instead of built in Cron?
Any Suggestions on how to go about doing it?

Only way I could find to rerun an existing job (SparkApplication CRD) is to do:
1) kubectl delete -f  <sparkapplication.yaml>
2) kubectl apply -f  <sparkapplication.yaml>

**Comment by mrow4a** [comment]
Just out of curiosity, what would be the use-case / benefit of using workflow engine instead of cron?

**Comment by ashishwrt** [comment]
1) If this spark job is part of multistage workflow, may be across different tools/environments, then it is easier to use something like Airflow to compose and manage the whole pipeline.
2) Better management UI, alerting. logs etc.
(If it is a standalone spark job then probably not much to gain except for much nicer management tools/UI.)

**Comment by liyinan926** [comment]
I tried to build a custom Airflow operator/executor for creating `SparkApplication` resources a long time ago but never completed it. The draft code is here https://github.com/liyinan926/incubator-airflow/commit/d9e8fd7e68ed88d942a7e16473462d14886ae5ea. Let me know if this is close to what you were thinking of.

**Comment by GrigorievNick** [comment]
Please look on this.
https://github.com/nikkatalnikov/bigkube/tree/master/airflow/operators
I use this code, in produciton. 
Ok not exactly this one, but very similar

**Comment by kodelint** [comment]
@GrigorievNick will you be able to share a sample `dag` using the operator. Are you passing the entrie `YAML` to the python_operator to submit it sparkoperator? I am wondering that if it is even feasible to write a `dag` as well as the `yaml` to run the job.

**Comment by roitvt** [comment]
we've written airflow integration including kubernetes_hook, airflow operator and sensor.
I opened a Jira issue at the airflow project https://issues.apache.org/jira/browse/AIRFLOW-6542 in order to contribute it to airflow contrib. 
I'll be glad if you'll try it and share your thoughts.
@liyinan926 can you support me at the Jira issue? thanks

**Comment by mik-laj** [comment]
Hello,

I am a committer in the Apache Airflow project. 
How can I help you?

Best regards,
Kamil

**Comment by mik-laj** [comment]
PS. Airflow is used by Google Cloud Composer, so if a team from this project contacts the other team they can get direct support from Airflow experts.
@liyinan926

**Comment by liyinan926** [comment]
@roitvt sure, I would be glad to support. Thank you for the contribution!

**Comment by roitvt** [comment]
Hey, I wanted to let you know that my effort to create a native Airflow integration for Spark-on-K8s operator (https://issues.apache.org/jira/browse/AIRFLOW-6542) was just merged, and will be a part of the next Airflow version!
This will allow you to migrate your Airflow-based Spark jobs to K8s, with minimal changes to the DAGs.
Thanks to Airflow committers who helped with this effort - @mik-laj  , @kaxil, @ash

**Comment by liyinan926** [comment]
@roitvt Wow, this is awesome! Thank you for the effort!

**Comment by roitvt** [comment]
can we add this to the docs?

**Comment by liyinan926** [comment]
Sure, can you create a PR for the doc changes?

**Comment by roitvt** [comment]
for sure will start working on it tomorrow
