### ISSUE TITLE
Move the Spark Operator to the controller-runtime

### ISSUE THREAD

**Issue by skonto** [kubeflow/spark-operator#547]
This will provide several benefits:
a) high level abstractions to manage code easier, the controller runtime is based on shared-informers but it has its own cache/client implementation and a high level api that makes things cleaner. It is actively maintained and it is the next generation sdk for building operators right now, imho.
b) several features for free like leader election, multi-namespace support, status subresource support
c) supports go modules (will be default in go 1.13), we are moving away from GOPATH
d) enforces one place for the Reconsiler code as a best practice (https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md), eg. no need to separately re-act to pod CRUD events.

me and @yuchaoran2011 have started working on this, and the idea is to propose this with the following migration plan:
Support Spark 3.0.0 + controller runtime in one release, so we dont have to support 2.4.x and two different runtimes.
Plus remove the webhook dependency (or make it optional for issues like the recent one we saw with the virtual kubelet) and support internally all operations via the pod template. Webhook has become an issue in several occasions such as OLM support, pod security policy (depends on webhook ordering or may come too late). @liyinan926 fyi, these are our thoughts let me know if you have any objections.

Controller-runtime links:
https://book.kubebuilder.io/
https://github.com/kubernetes-sigs/controller-runtime

**Comment by liyinan926** [comment]
It's good to migrate to using controller-runtime. However, we cannot remove the webhook as it is still needed for Spark 2.3.x and 2.4.x. I am also not a fan of the pod template approach of configuring Spark driver/executor pods (it needs additional logic to manage the template file even though the file is generated in this context), although that seems the only viable approach for supporting arbitrary configuration options in a Spark way.

**Comment by skonto** [comment]
@liyinan926 We are still working this. The branch we use is: https://github.com/lightbend/spark-on-k8s-operator/tree/controller-runtime (needs update, but there we moved to go modules as most projects are doing). I understand the need for the webhook, there are new things coming like cert-manager for assigning the webhook etc. Btw there are some things that stops us from moving all parts to use kubebuilder eg. https://github.com/kubernetes-sigs/controller-tools/issues/245 but thats ok.  
However, we controller-runtime migration is possible anyway.
