### ISSUE TITLE
Add checksum support for SparkApplication to enable rerun after configmap changes.

### ISSUE THREAD

**Issue by ryanli-me** [kubeflow/spark-operator#548]
Hi, we've been working with helm with `Deployment` and `ConfigMap` extensively and the trick to trigger a new deployment with configmap change is extremely helpful. 

The trick is stated here https://github.com/helm/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change

I think it's also useful to trigger a rerun of spark application if the configmap is changed. Just adding the support for `annotations` in `metadata` might work but I'm not really sure about how CRD works in detail.

**Comment by liyinan926** [comment]
That's an interesting idea. It seems the annotation-based approach should work here.

**Comment by skonto** [comment]
That is a nice idea that has come up recently, if we were to implement this would that mean that we had to watch the configmap for changes as Spark does not use help for deploying its pods?
