### ISSUE TITLE
Having a dedicated website for documentation

### ISSUE THREAD

**Issue by liyinan926** [kubeflow/spark-operator#590]
Currently the documentation is in the form of a bunch of markdown files under the `docs` folder of the repo. It will be great to have a dedicated website for the project to host the documentation and announcement like releases.

**Comment by skonto** [comment]
@liyinan926 should this be on github?

**Comment by liyinan926** [comment]
That can be an option.

**Comment by vara-bonthu** [comment]
@liyinan926 I would be happy to collaborate on creating a comprehensive documentation website using `Docusaurus` and GitHub workflows. 

Please confirm if this aligns with your plans, and I'll kick things off by outlining the website's structure in a document. Once we've reached a consensus on the structure, we can proceed with raising a pull request to get the project underway. 

Looking forward to working together!

**Comment by ChenYi015** [comment]
Close this issue for the docs have already been moved to the [Kubeflow](https://www.kubeflow.org/docs/components/spark-operator/) website.
