### ISSUE TITLE
Can't install webhook with helm --wait or --atomic operation

### ISSUE THREAD

**Issue by AceHack** [kubeflow/spark-operator#597]
The webhook fails to install if setting the helm --wait or --atomic operation

Seems like
https://github.com/helm/charts/blob/8d3a4ce49bf751447e8cdc3ae3596d732928a38b/incubator/sparkoperator/templates/webhook-init-job.yaml#L8

Should be a pre-install hook instead of a post-install

works
```
helm upgrade spark-operator sparkoperator -f spark-on-k8s-operator/values.yaml --namespace spark-operator --install --force --debug --repo http://storage.googleapis.com/kubernetes-charts-incubator
```

both fail
```
helm upgrade spark-operator sparkoperator -f spark-on-k8s-operator/values.yaml --namespace spark-operator --install --wait --force --debug --repo http://storage.googleapis.com/kubernetes-charts-incubator

helm upgrade spark-operator sparkoperator -f spark-on-k8s-operator/values.yaml --namespace spark-operator --install --atomic  --force --debug --repo http://storage.googleapis.com/kubernetes-charts-incubator
```

values.yaml
```
sparkJobNamespace: "spark-jobs"
enableWebhook: true
enableMetrics: true
logLevel: 2
```

**Comment by yuchaoran2011** [comment]
@AceHack Someone tried to solve this issue [here](https://github.com/helm/charts/pull/15487#issuecomment-510917892) but he didn't finish. Feel free to work on it.

**Comment by AceHack** [comment]
Even with the latest update --atomic fails around 25% of the time when updating values.yaml.  Many times the pod never comes up and the rollback fails.  I have not been able to fully track down the issue.  This is using the latest helm chart that makes the job a regular job with no post-install hook.
