### ISSUE TITLE
How to run docker image outside K8s locally

### ISSUE THREAD

**Issue by AceHack** [kubeflow/spark-operator#598]
How do I run the docker container in as a unit test?  No need to spin up any executors, just do it all on the driver like when you set host to local[*] when calling spark-submit.

**Comment by AceHack** [comment]
Does anyone know how to run the docker container locally?

**Comment by jkleckner** [comment]
@ace-n You can use spark-submit using the container with a master of local.  Alternatively you can run the tests in a cluster using a hack to wait and retrieve the status as mentioned here: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/732#issuecomment-569356284

See also https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/719

**Comment by AceHack** [comment]
Can you write out the docker command to call spark-submit?  Thanks.
