### ISSUE TITLE
Apply common pod labels to submitted applications

### ISSUE THREAD

**Issue by akirillov** [kubeflow/spark-operator#685]
Hi everyone. This is more of a question than an issue: we're looking for a way to apply common pod labels to submitted applications. Currently, it's possible to specify additional labels on a per-application basis but it would be great to provide some default labels applied to all the application pods (Drivers and Executors) launched by a single Operator instance by default.

Does having `--defaultPodLabels=key1:value1,key2:value2` flag (or something similar) sound like an acceptable solution for that? If so, I'd be happy to create a PR for that.

The use-case we're having is related to enabling Prometheus Operator metrics scraping. For this purpose, we use `ServiceMonitor` and additional Services for the Operator and Applications metrics endpoints. Having default pod labels applied to all Driver and Executor pods would allow more flexible selector configuration for metrics endpoint services.

**Comment by liyinan926** [comment]
Sounds like this is a reasonable approach to consider. An alternative is to use what's proposed in #661.

**Comment by akirillov** [comment]
Thanks for the quick response, @liyinan926! Just to clarify, do you mean the JSON format of the flag value or something else? 

I think both common service (and pod) annotations, and common pod labels for submitted applications make sense especially when it comes to multi-instance installations.

**Comment by akirillov** [comment]
Sorry, my bad, reading through the `SparkApplicationClass` [proposal](https://docs.google.com/document/d/1G9Kvi3ptf4mobrK2I5rPB_uAvFOymOLJsobuuPvCkS8/edit#) now

**Comment by akirillov** [comment]
Hi @liyinan926, really liked the idea from the design doc, however, it addresses a little bit different use-case. With `SparkApplicationClass` users can define standard application templates containing shared properties specific for the environment. However, this approach is application-centric, not operator-centric.

In our use-case, we'd like to label (distinguish) applications launched by different operator controllers which is not achievable with `SparkApplicationClass` because essentially we'll need to define a `SparkApplicationClass` for each of the instances which is not very different from specifying labels on per-application basis.

Also, having default/shared labels set by the Operator allows avoiding copying of these labels between multiple `SparkApplicationClass` instances.

WDYT?

**Comment by liyinan926** [comment]
Got it. In that case, having a flag for common labels seems a reasonable approach.
