### ISSUE TITLE
Reliably wait for spark application to start and then to finish

### ISSUE THREAD

**Issue by jkleckner** [kubeflow/spark-operator#732]
See discussion in #719 with this last open issue.  Moving to a separate issue for clarity.

> > How can you launch a spark application and then reliably wait for it to finish?
> 
> I would explore extending `sparkctl` to support this kind of launch-and-wait use cases.

That could work, but it would be nice if the underlying api had this as a primitive so that there is no need to install another tool but the spark application could be waited on from `kubectl`.

_Originally posted by @jkleckner in https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/719#issuecomment-565088850_

**Comment by jkleckner** [comment]
Here is a workaround script for waiting for a test to complete and fetching the status.
Success is obtained when app_status is COMPLETED

```
spark_namespace=spark
APP_TEST_TIMEOUT=80
APP_TEST_NAME=app-test-${CI_JOB_ID}
app_status="UNDEFINED"

function check_app_test_status(){
  local counter
  counter=0
  app_status=$(kubectl get -n $spark_namespace sparkapplications ${APP_TEST_NAME} -o jsonpath='{.status.applicationState.state}')

  until [[ "${app_status}" = "COMPLETED" || "${app_status}" = "FAILED" ]]; do
    sleep 5

    if [ "${counter}" -ge "${APP_TEST_TIMEOUT}" ]; then
      echo "####### ERROR: reached timout - app test did not finish"
      kubectl -n $spark_namespace describe sparkapplications ${APP_TEST_NAME}
      app_status="TEST_TIMEOUT"
      break
    else
      counter=$((++counter))
    fi
    app_status=$(kubectl get -n $spark_namespace sparkapplications ${APP_TEST_NAME} -o jsonpath='{.status.applicationState.state}')
    echo '###' counter: ${counter} app_status:"${app_status}"
  done
}

...


kubectl apply --validate=true -f app-test.yaml
check_app_test_status

if [ "${app_status}" != "COMPLETED" ] ; then
  echo '################  ERROR RUNNING TEST CASE'
else
  echo '################  SUCCESS RUNNING TEST CASE'
fi

```

**Comment by holdenk** [comment]
So I'm not seeing the appStatus field using the 2.4.5 version?

**Comment by saimadineni** [comment]
@jkleckner  Has this issue been ever resolved natively or you've just been using this hack? 
Thanks

**Comment by jkleckner** [comment]
@saimadineni  I'm not aware of any in-built synchronization mechanism and I continue to use the script above to wait with a timeout.

**Comment by renjigeorge** [comment]
what are these resources used for "sparkapplications/status" ?

**Comment by marzigolbaz** [comment]
@jkleckner do you know if this issue has ever been resolved? 
Thanks!

**Comment by ToanP** [comment]
I think we can wait for "kubectl log -f" done and get Spark Application status from "kubectl get -n $spark_namespace sparkapplications ${APP_TEST_NAME} -o jsonpath='{.status.applicationState.state}'"
