### ISSUE TITLE
Spark SQL support

### ISSUE THREAD

**Issue by liyinan926** [kubeflow/spark-operator#744]
@KoopaKing @krousey 

A minimum set of tasks to start with:

* [ ] support deployment of the Thrift JDBC/ODBC server on Kubernetes
* [ ] support specification and execution of SQL queries through Kubernetes custom resources

**Comment by pengye91** [comment]
Hi guys, 
I'm wondering what's the status of this ticket, is it still ongoing?

**Comment by arijitdey** [comment]
@liyinan926 Any update on the support for Thrift JDBC/ODBC server on Kubernetes?

**Comment by KptMarchewa** [comment]
I would also be interested in this.

**Comment by jbguerraz** [comment]
Same here, a JDBC/ODBC support would be cool! :+1: I didn't dig it yet but I'm ready to help!

**Comment by jhonnli** [comment]
How do I use a shell script to submit a Spark Sql task, you can give an example
