### ISSUE TITLE
Support log4j configuration in SparkApplication

### ISSUE THREAD

**Issue by liyinan926** [kubeflow/spark-operator#753]
Currently using a custom log4j.properties works in two ways:
1. Bake the custom log4j.properties into a custom Spark image.
2. Create a ConfigMap storing the custom log4j.properties and mount it into the Spark driver and/or executor pods, and then add `-Dlog4j.configuration=<path to log4j.properties>` into the `extraJavaOptions` field for the driver and/or executors.

We can make it easier to use custom log4j.properties by adding a dedicated field in `SparkApplicationSpec` for configuring logging.

**Comment by abhisrao** [comment]
Hi @liyinan926 
Just a thought. Another way could be to fix the issue with mounting spark config map onto SPARK_CONF_DIR (Issue #216 ).  Then we can pass log4j.properties as part of spark config map and solve the log4j configuration issue.

**Comment by liyinan926** [comment]
@abhisrao that works.

**Comment by pitouteng** [comment]
How to proceed with method 1 Bake the custom log4j.properties into a custom Spark image?

**Comment by amitme10** [comment]
Hey , 
I'm using a Graylog appender in my log4j.properties (which works just fine the way you mentioned above)
however it tells me at logs : java.lang.ClassNotFoundException about the appender class (which finds at pom.xml and works fine localy) could you advice please?

**Comment by vanhoale** [comment]
@liyinan926 I think if we can let the user defines a unique configmap (optional) that is included log4j.properties, spark.properties, core-site.xml, hive-site.xml .etc like:
```
data:
  log4j.properties: |
    key=value
    key=value
  spark.properties: |
    key=value
    key=value
  hive-site.xml: |
    <configuration>
        <property>
            <name>hive.imetastoreclient.factory.class</name>
            <value>com.amazonaws.glue.catalog.metastore.AWSGlueDataCatalogHiveClientFactory</value>
        </property>
        <property>
          <name>aws.region</name>
          <value>REGION</value>
        </property>
    </configuration> 
```
and then spark-operator can map those to /opt/spark/conf (that can be exposed to the classpath). it will be easier to manage the config in one place.

As of now, if I try to use `spark.driver.extraJavaOptions` and `spark.executor.extraJavaOptions` with prometheus option, it will overwrite each other.
