### ISSUE TITLE
Webhook does not work as expected

### ISSUE THREAD

**Issue by alessioale** [kubeflow/spark-operator#819]
Hello,

We decided to use Spark Operator to manage multi-tenant environment on an Openshift cluster 4.2.

For this reason we chose to deploy a spark operator in a namespace called tenant-admin that watches Spark Applications on another namespace called tenant-worker.

We launched the spark operator on tenant-admin namespace with the following configuration:

```
image: gcr.io/spark-operator/spark-operator:v2.4.4-v1beta2-latest
args:
        - '-v=4'
        - '-logtostderr'
        - '-stderrthreshold=INFO'
        - '-enable-metrics=true'
        - '-metrics-labels=app_type'
        - '-namespace=tenant-worker'
        - '-ingress-url-format={{$appName}}.tenant-worker.apps.my.cluster.net'
        - '-enable-webhook=true'
        - '-enable-resource-quota-enforcement=true'
        - '-controller-threads=10'
        - '-resync-interval=30'
        - '-webhook-fail-on-error=true'
        - '-webhook-svc-name=spark-op'
        - '-webhook-svc-namespace=tenant-admin'
        - '-webhook-namespace-selector=namespace-name=tenant-worker'
```

The Spark Operator works fine and we validated it launching several applications in the tenant-worker namespace.

After several sequential submissions of the same application, we face up a recurrent issue: 
**the webhook does not seem work anymore and each new attempt of application fails because the configMap is not mounted**

In the logs, we don't have a lot of information. We noticed only the present of the following lines when the webhook works correctly

```
I0224 09:09:17.725312      10 webhook.go:246] Serving admission request
I0224 09:09:17.725706      10 webhook.go:556] Pod spark-test-app-driver in namespace tenant-worker is subject to mutation
```

Only restarting the spark Operator pod seems to resolve temporarily the issue.

How could we debug the issue ? Is it possible to change the log level for webhook ?

Thanks
Alessio

**Comment by liyinan926** [comment]
You might need to dig into the logs of the k8s API server to find out what happened when calling the webhook for mutating requests. This sounds to me like an environment issue.

**Comment by jkleckner** [comment]
Cross-posting here that #815 has a potentially related issue with the web hook that may have a common source problem.  That issue has a test case that exhibits behavior regression with the `enableWebhook` feature.

**Comment by ankur-gupta-guavus** [comment]
@liyinan926 we are also observing this same issue . We checked API server logs and there are connection refused messages seen in API server logs while trying to call webhook, restart of spark operator pod resolves the problem. Can you help in isloting this issue ?
