### ISSUE TITLE
Reload sparkapplication when configmap changes?

### ISSUE THREAD

**Issue by apkerr** [kubeflow/spark-operator#850]
This is probably an enhancement request, unless I'm missing something.

We have a kubernetes cluster deployed via kubespray, which means that I don't have easy access to the sparkapplication yaml files, as helm charts are installed on the fly using whatever values are in the chart stored in the repository. 

I'd like to be able to edit a configmap (to change log4j setting, for example) and have the sparkapplication restart itself using the new configmap. Is that possible?

**Comment by liyinan926** [comment]
Seems duplicated with #548.

**Comment by apkerr** [comment]
Yes, it looks like a duplicate.
