### ISSUE TITLE
Call from API server to webhook fails because of self-signed certificate

### ISSUE THREAD

**Issue by scheleaap** [kubeflow/spark-operator#855]
Hello, I installed the operator on our cluster, but the mutating admission webhook does not modify the pods (setting the security context, in my case).

## Environment
* Kubernetes v1.16.2
* Spark Operator v1beta2-1.1.0-2.4.5
* Helm v2.14.3
* Helm chart v0.6.8

Operator installation:
```
helm upgrade "${HELM_RELEASE_NAME}" incubator/sparkoperator \
  --install \
  --namespace "${NAMESPACE}" \
  --version "0.6.8" \
  --values spark-operator-values.yaml
```
values:
```yaml
operatorVersion: v1beta2-1.1.0-2.4.5
enableWebhook: true
securityContext:
  runAsUser: 10000
```

## Analysis

I confirmed that the webhook is installed and running. The API server does try to call the webhook but fails with the following error:

kube-apiserver-stg-k8s-002 kube-apiserver W0401 15:45:55.047126       1 dispatcher.go:168] Failed calling webhook, failing open webhook.sparkoperator.k8s.io: failed calling webhook "webhook.sparkoperator.k8s.io": **Post https://spark-operator-webhook.spark-operator.svc:443/webhook?timeout=30s: x509: certificate signed by unknown authority** (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "spark-operator-webhook_ca")

I believe that the call from the API server to the webhook fails because it tries to verify the self-signed certificate generated by [gencerts.sh](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/hack/gencerts.sh).

## Questions

* Has anyone encountered this before?
* Are there any known solutions? For example:
  * disabling certificate validation, 
  * using HTTP instead of HTTPS, or
  * signing the certificate with the CA provided by Kubernetes?

Thank you!

**Comment by liyinan926** [comment]
Yes, we currently use a self-signed certificate.  The key doesn't need to be signed with the cluster CA.  My understanding is the API server will use the CA bundle in the `MutatingWebhookConfiguration`.

**Comment by scheleaap** [comment]
For some reason, our cluster does not accept the self-signed certificate and the webhook call fails. I was able to get the webhook to work by having the Kubernetes CA sign the certificate using the  [Certificates API](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/).

I wrote the following script to do so (based on [gencerts.sh](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/d41e1c93f798cbaa30084af912e2f582e8990383/hack/gencerts.sh)):
```bash
#!/usr/bin/env bash

set -e

TMP_DIR=$(mktemp -d)

SERVICE="spark-operator-webhook"
NAMESPACE="spark-operator"

cat > ${TMP_DIR}/server.conf << EOF
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth, serverAuth
EOF

openssl genrsa -out ${TMP_DIR}/server-key.pem 2048

# Note the CN is the DNS name of the service of the webhook.
openssl req \
  -new \
  -key ${TMP_DIR}/server-key.pem \
  -out ${TMP_DIR}/server-csr.pem \
  -subj "/CN=${SERVICE}.${NAMESPACE}.svc" \
  -config ${TMP_DIR}/server.conf

kubectl delete csr spark-operator-webhook-csr
cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: spark-operator-webhook-csr
spec:
  request: $(cat ${TMP_DIR}/server-csr.pem | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

kubectl certificate approve spark-operator-webhook-csr

kubectl get csr spark-operator-webhook-csr -o jsonpath='{.status.certificate}' \
    | base64 --decode > ${TMP_DIR}/server-cert.pem

kubectl get secrets spark-operator-sparkoperator-token-qxz44 -o yaml \
| grep ca.crt | cut -d' ' -f4 | base64 -d > ${TMP_DIR}/ca-cert.pem

echo "Creating a secret for the certificate and keys"
# Base64 encode secrets and then remove the trailing newline to avoid issues in the kubectl command
ca_cert=$(cat ${TMP_DIR}/ca-cert.pem | base64 | tr -d '\n')
server_key=$(cat ${TMP_DIR}/server-key.pem | base64 | tr -d '\n')
server_cert=$(cat ${TMP_DIR}/server-cert.pem | base64 | tr -d '\n')

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: spark-webhook-certs
  namespace: ${NAMESPACE}
data:
  ca-cert.pem: $ca_cert
  server-cert.pem: $server_cert
  server-key.pem: $server_key
EOF
```

In our particular case, the user executing this script has the permission to call `kubectl certificate approve test-csr`. If the user does not and there is no automated approval process in place, you might need to break this script up into two parts (one that creates the CSR, one that takes the approved CSR and creates the secret).

**Comment by scheleaap** [comment]
I propose creating a PR for the [Helm chart](https://github.com/helm/charts/tree/master/incubator/sparkoperator) to disable the creation of the webhook secret. WDYT?

**Comment by scheleaap** [comment]
I tried reproducing the problem, but had a hard time reproducing it in a deterministic way. I observed two problems while deleting and reinstalling the operator:
1. sometimes, deploying the operator itself fails (Kubernetes reports 0 out of 1 replicas are available for the deployment)
2. sometimes, the webhook certificate is not accepted by the API server (original problem of this issue)

I tried deleting and reinstalling the operator several times, but never got a consistent outcome. Sometimes one of the problems occurs, sometimes they don't. There must be some other factor at play here.

I noticed the mutating webhook configuration does not get deleted on `helm delete --purge`. Since this config contains a CA bundle, could this cause on of the problems I encountered?

**Comment by aneagoe** [comment]
Saw the same issue on a fresh deployment (chart: sparkoperator-0.8.2, app: v1beta2-1.2.0-3.0.0). I had to manually delete the MutatingWebhookConfiguration and HelmRelease then let flux re-deploy.

**Comment by richerve** [comment]
Same issue here. I think that relying on helm hooks that spawn Jobs is a bad decision for this. In our case, the Secret with the certs was deleted and not recreated. Why? I don't now but there are potential issues like the call for the Job timing out, for example.

What we did instead is use cert-manager to issue a self-signed certificate, and added support for that in our fork of the spark-operator chart. I know that this depends on having cert-manager but is definitively less hacky than the bash script and helm hooks.

**Comment by adityasundaramurthy-maersk** [comment]
I'm not sure if the issue I'm running into is related to this one, but this is what seems to happen.
```
2021/02/08 10:17:23 http: TLS handshake error from 10.200.6.54:37242: remote error: tls: bad certificate 
```
I've narrowed it down to the fact that I have the operator replica count bumped up to 3, so there's a leader election to pick an active operator. I've also figured out that the leader generates a TLS certificate and updates the MutatingWebhookConfiguration with the certificate, so the control plane can call the active operator pod to mutate the envFrom bits. It looks this update fails periodically. 

The above situation seems to be a case where the leader election happened and a leader was picked but the webhook config was not updated (or the other way around). Deleting the active leader pod helped fix the issue as the next leader updated the webhook configuration. Is this a known problem?

**Comment by korjek** [comment]
in our case `TLS handshake error from ****: remote error: tls: bad certificate` was related to a fact, that somehow we get with two mutating webhook configuration for spark operator (likely we were playing with the chart and missed to do cleanup properly) causing API server to use wrong CA bundle.
Once we removed the stale mutating webhook configuration we do not see similar records in logs anymore.
