### ISSUE TITLE
[proposal] Add volumeClaimTemplates to executor spec.

### ISSUE THREAD

**Issue by ringtail** [kubeflow/spark-operator#864]
We are running spark on ECI (similar with aws fargate). And we want to mount cloud disk as volumes for executors. So `volumeClaimTemplates` would be helpful for this case. Implement is on the way.

**Comment by ringtail** [comment]
@liyinan926 @Jeffwan Is this a common case for GKE and AWS?

**Comment by Jeffwan** [comment]
@ringtail We do have cases using cloud disks for shuffle scratch space, Input & output data. 
Webhook allow us specify PV and PVC for driver and executors. Trying to understand anything different in `volumeClaimTemplates` ? Do I miss something?

**Comment by ringtail** [comment]
@Jeffwan Do you mean `SparkLocalDirVolumePrefix` feature?

**Comment by ringtail** [comment]
How to add each one pod with a independent cloud disk?

**Comment by Jeffwan** [comment]
@ringtail 

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L422

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi.yaml#L31

All volume types are supported.

**Comment by ringtail** [comment]
What if i want to run each executor with a independent cloud disk.

**Comment by themoah** [comment]
@ringtail @Jeffwan I have similar workflow, each pod needs its own PVC (stateful streaming). There is also autoscaling and pods are running on spots; thus need some automation to create cloud disks (with defined storageClass).

**Comment by ringtail** [comment]
> @ringtail @Jeffwan I have similar workflow, each pod needs its own PVC (stateful streaming). There is also autoscaling and pods are running on spots; thus need some automation to create cloud disks (with defined storageClass).

I have made it in our release. (https://github.com/AliyunContainerService/spark-on-k8s-operator/blob/alibabacloud-v1beta2-1.1.0-2.4.5/pkg/apis/sparkoperator.k8s.io/v1beta2/types.go#L284). If helpful, I'll open a pr to patch this feature.

**Comment by themoah** [comment]
@ringtail yes, please!
