### ISSUE TITLE
custom serviceAccount for executor

### ISSUE THREAD

**Issue by cwei-bgl** [kubeflow/spark-operator#885]
Hi thanks for the work, spark-on-k8s-operator really makes thing easier.

It seems the operator currently does not support specifying a custom serviceAccount for executors. I tried both serviceAccount and serviceAccountName fields on executor node, which did not work and it was always being set to 'default'. I need a custom serviceAccount for executors so that they can access AWS resources. Alternatively, at least executors use the same serviceAccount from driver so that security can be controlled to a reasonable level. Thanks.

**Comment by liyinan926** [comment]
The operator doesn't support custom service account for the executor pods. Spark on Kubernetes will support it in the future in 3.1 (see https://github.com/apache/spark/pull/27034). We can definitely add support for this.

**Comment by cwei-bgl** [comment]
Great! thanks @liyinan926

**Comment by batCoder95** [comment]
> The operator doesn't support custom service account for the executor pods. Spark on Kubernetes will support it in the future in 3.1 (see [apache/spark#27034](https://github.com/apache/spark/pull/27034)). We can definitely add support for this.

@liyinan926 - The pull request (27034) in above reply is in state closed. Does that mean that a new version has been released with custom service account support ? Checking this in relation to the issue: [IAM Role for Driver and Executor Pods? #1002](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1002)

**Comment by bbenzikry** [comment]
Issue can be closed :)
@batCoder95 This is now available via #1322
