### ISSUE TITLE
Got error when update crd

### ISSUE THREAD

**Issue by ycwdaaaa** [kubeflow/spark-operator#937]
error message:
I0531 07:30:32.834326      11 main.go:137] Starting the Spark Operator
I0531 07:30:32.896951      11 crd.go:66] Updating CustomResourceDefinition sparkapplications.sparkoperator.k8s.io
F0531 07:30:32.920040      11 main.go:163] failed to create or update CustomResourceDefinition sparkapplications.sparkoperator.k8s.io: CustomResourceDefinition.apiextensions.k8s.io "sparkapplications.sparkoperator.k8s.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta2": must appear in spec.versions

helm version: 3

install commnad : helm install incubator/sparkoperator --generate-name --namespace spark-operator --set sparkJobNamespace=default --set operatorImageName=psschwei/spark-operator --set operatorVersion=2.4.5

**Comment by ycwdaaaa** [comment]
hello? anybody here?

**Comment by liyinan926** [comment]
Which version of k8s are you running, and where are your running your k8s cluster?

**Comment by ycwdaaaa** [comment]
@liyinan926  
k8s version: 1.16
I run this in the master node with kubectl command ennable

**Comment by liyinan926** [comment]
So you already had the CRDs in the cluster before you ran helm install?

**Comment by ycwdaaaa** [comment]
@liyinan926 no,  i just run the helm install command
