### ISSUE TITLE
Query on handling of CRD upgrades

### ISSUE THREAD

**Issue by abhisrao** [kubeflow/spark-operator#949]
I would like to know how are we planning to handle sparkApplication and scheduledSparkApplication CRD upgrades when spark applications are running.
Let us say we have installed sparkApplication CRD version v1beta1 in our cluster and few streaming spark jobs are running (using this sparkApplication)
Now if we want to upgrade sparkApplication CRD to v1beta2. Our understanding is that we have to delete the v1beta1 version and then install v1beta2. Is this correct understanding?
If so, we observe that the running spark jobs are stopped (because all the sparkApplications are deleted when CRD is deleted).
Do we have any view on this?

**Comment by RonBarabash** [comment]
Hey @abhisrao any conclusions on how to handle upgrades?

**Comment by abhisrao** [comment]
@RonBarabash 
No, I've not seen any conclusion yet. However, K8S recommends the below approach to handle CRD upgrade. 

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/

We might have to follow similar approach. If there is any better approach, we can discuss.
