### ISSUE TITLE
ScheduledSparkApplications configmap doesn't work after upgrading to spark 3.0

### ISSUE THREAD

**Issue by karankale** [kubeflow/spark-operator#972]
On submitting the `scheduledSparkApplication` seeing the below error in the spark operator logs :
```
I0709 08:34:14.680377      11 webhook.go:246] Serving admission request
E0709 08:34:14.680755      11 webhook.go:323] internal error: failed to get SparkApplication spark-application/qa-jtp-hourly: sparkapplication.sparkoperator.k8s.io "qa-jtp-hourly" not found
```
This is causing the configmap not be attached to the driver pod.
Seems the `sparkapplication` name is not being reflected properly. The name should be `qa-jtp-hourly-timestamp`

We are using the official spark operator 3.0 image for our testing.

Note: Normal `sparkApplication` is working without any issues

**Comment by karankale** [comment]
On checking the pod spec found that one of the labels for the spark app pod is `sparkoperator.k8s.io/app-name=qa-jtp-hourly`, this is not correct

reference code:
```
// Try getting the SparkApplication name from the annotation for that.
	appName := pod.Labels[config.SparkAppNameLabel]
```

**Comment by liyinan926** [comment]
What does the status section of your `ScheduledSparkApplication` look like?
