### ISSUE TITLE
Error running prometheus example

### ISSUE THREAD

**Issue by shardulsrivastava** [kubeflow/spark-operator#982]
When m trying to run [prometheus example](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-pi-prometheus.yaml) , m getting this error:

```
Error opening zip file or JAR manifest missing : prometheus/jmx_prometheus_javaagent-0.11.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```

In this example , image is :

```bash
gcr.io/spark-operator/spark:v3.0.0
```

however this image doesn't seem to have the **prometheus Jar** and in the user guide's [monitoring section](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/user-guide.md#monitoring), it has been advised to use image with this tag :

```
gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus
```

however this image doesn't exist too.

**Comment by liyinan926** [comment]
`gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus` should be available now.

**Comment by shardulsrivastava** [comment]
@liyinan926 tried the new image , however error remains the same:

```
Error opening zip file or JAR manifest missing : /prometheus/jmx_prometheus_javaagent-0.11.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
```


Here is the error:

```
shardulsrivastava@MYMAC083 cdp % kubectl get pods spark-pi-driver -n spark -o json| jq -r '.spec.containers[].image'
gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus
shardulsrivastava@MYMAC083 cdp % kubectl logs -f spark-pi-driver -n spark|tail -10
+ '[' '' == 3 ']'
+ '[' -n '' ']'
+ '[' -z ']'
+ case "$1" in
+ shift 1
+ CMD=("$SPARK_HOME/bin/spark-submit" --conf "spark.driver.bindAddress=$SPARK_DRIVER_BIND_ADDRESS" --deploy-mode client "$@")
+ exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.89.157.31 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.examples.SparkPi local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar 100000
Error opening zip file or JAR manifest missing : /prometheus/jmx_prometheus_javaagent-0.11.0.jar
Error occurred during initialization of VM
agent library failed to init: instrument
shardulsrivastava@MYMAC083 cdp % 
```

**Comment by liyinan926** [comment]
Somehow the recent version bump incorrectly changed the image tag in the example. Fixed it just now. Please give it a try.

**Comment by moskvax** [comment]
@liyinan926 The prometheus jar got added to the image by root with 600 permissions, preventing Spark running as uid 185 from seeing it:
```console
$ docker run -it --rm gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus /bin/bash
185@7d6fd4c87ada:/opt/spark/work-dir$ id
uid=185(185) gid=0(root) groups=0(root)
185@7d6fd4c87ada:/opt/spark/work-dir$ ls -l /prometheus
total 364
-rw------- 1 root root 368881 Jan 16  2019 jmx_prometheus_javaagent-0.11.0.jar
185@7d6fd4c87ada:/opt/spark/work-dir$ cat /prometheus/jmx_prometheus_javaagent-0.11.0.jar > /dev/null
cat: /prometheus/jmx_prometheus_javaagent-0.11.0.jar: Permission denied
```

**Comment by jdonnelly-apixio** [comment]
I saw the issue that @moskvax hit so I built a container on top of spark:v3.0.0-gcs-prometheus and chmod 644'd the prometheus jar, but I got this exception next:

```
+ exec /usr/bin/tini -s -- /opt/spark/bin/spark-submit --conf spark.driver.bindAddress=10.1.131.140 --deploy-mode client --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.examples.SparkPi local:///opt/spark/examples/jars/spark-examples_2.12-3.0.0.jar 100000
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Preconditions
        at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:328)
        at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:341)
        at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:423)
        at org.apache.spark.deploy.SparkHadoopUtil$.newConfiguration(SparkHadoopUtil.scala:426)
        at org.apache.spark.deploy.SparkSubmit.$anonfun$prepareSubmitEnvironment$2(SparkSubmit.scala:342)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:342)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:871)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Preconditions
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 14 more
```

The dockerfile:
```
FROM gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus
USER root
RUN chmod 644 /prometheus/jmx_prometheus_javaagent-0.11.0.jar
USER 185
```

**Comment by shardulsrivastava** [comment]
@jdonnelly-apixio how did you build your image using docker-image tool of Spark or plain docker build command ??

**Comment by moskvax** [comment]
@jdonnelly-apixio the same permissions issue exists with the bigquery/hadoop/guava jars added to `/opt/spark`; after the permissions on these jars are fixed, the container should work fine.

**Comment by liyinan926** [comment]
Will fix the Dockerfile and rebuild the image.

**Comment by liyinan926** [comment]
The image  `gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus` has been rebuilt and pushed.

**Comment by shardulsrivastava** [comment]
@liyinan926  will test it out.

**Comment by Fixmetal** [comment]
> Will fix the Dockerfile and rebuild the image.

Would you please share the steps to fix this? And backport this on 2.4.5 docker image too? It just shares the same issue and a `chmod 644` will run into https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/982#issuecomment-668301244

**Comment by shardulsrivastava** [comment]
@Fixmetal  there is a problem with available version of guava library , you gotta do this :

https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/spark-docker/Dockerfile#L24-L26

**Comment by Fixmetal** [comment]
> @Fixmetal there is a problem with available version of guava library , you gotta do this :
> 
> https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/spark-docker/Dockerfile#L24-L26

Thanks, I saw that all ADD stuff would get 0600 permissions and just fixed it by using a more generic:
```
chmod 0644 /prometheus/* ${SPARK_HOME}/jars/*
```

@liyinan926 : I encourage you (and the team) to use [hadolint](https://github.com/hadolint/hadolint) to avoid getting errors. Plus I suggest a review of [Dockerfile best practices] (https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy).
