### ISSUE TITLE
"Legacy monitoring is not supported..." deploying  gcr.io/ynli-k8s/spark:v2.3.0-gcs

### ISSUE THREAD

**Issue by adamlefevre** [kubeflow/spark-operator#991]
I'm attempting to deploy the gcr.io/ynli-k8s/spark:v2.3.0-gcs container to Google Kubernetes Engine and the deploy fails with error: "Legacy monitoring is not supported in clusters running Kubernetes 1.15 or above."

I was following documentation at spark-on-k8s-operator/docs/gcp.md

**Comment by liyinan926** [comment]
Looks like the container image you are using is too old. Could you please try `gcr.io/spark-operator/spark:v3.0.0-gcs-prometheus`?
